MODULE DECLARATION	
!--------------------------------------------------------------------------------------------------------------------------!
!HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH!
!_____________________________________________ START HEADER OF MODULE______________________________________________________!
!FUNCTION: IS TO COLLECT ALL THE GLOBAL VARIABLES, AND DATA TYPES OF THE CODE IN ONE MODULE
!////////////////////////////////////RESPONSIBLE TSOUTSANIS PANAGIOTIS/////////////////////////////////////////////////////! 
!**************************************LAST EDITED ON THE 12-02-2014*******************************************************!
!_____________________________________________ END HEADER OF MODULE________________________________________________________!
!--------------------------------------------------------------------------------------------------------------------------!

IMPLICIT NONE

!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.1.   INTEGER  VARIABLES HERE                  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!

INTEGER::pdim,M2,DIMENSIONA,LOWMEM,binio,nof_variables,CHUNK_N,dims,IRES_TURB,CODE_PROFILE,IRES_UNSTEADY,LAMPS,itotalb,totiw,number_of_dog,B_CODE,ICONS_S,ICONS_E,ICOMPACT,EES,iscoun,itold,lmach_style,WEIGHT_LSQR	!DIMENSIONS OF PROBLEM
integer::governingequations,guassianquadra,temporder,iboundary,wenocnschar,required,nodes_i,SWIRL,IADAPT,TECPLOT,STENCIL_IO,SURFSHEAR,ISSF,n_node,ELEM_DEC,n_boundaries,NUMBER_OF_NEI,FASTEST_Q,STATISTICS
integer,allocatable,DIMENSION(:,:)::jtot1,jtot2,jtot3,jtot
integer::jtotAL,JTOTAL1,JTOTAL2,JTOTAL3,compwrt,varcons,pointx,llx
INTEGER::KILL,INSTEN			  		!FLAG FOR KILLING A SIMULATION
INTEGER::NDERIVATIVE		  		!INDEX OF THE NUMBERING OF THE COMPONENT OF THE POLYNOMIALS 
INTEGER::IXXFF					!INTEGER TO BE PASSED IN ROUTINE FOR WRITING THE OUTPUT FILES
INTEGER::ICONSI					!INTEGER FOR CONSIDERED CELL
INTEGER::FACEX					!INDEX FOR IDENTIFYING WHICH FACE 
INTEGER::ICONSR					!INDEX FOR IDENTIFYING THE CONSIDERED ELEMENT 
INTEGER::IVGT					!INDEX FOR INVERTING MATRIX 
INTEGER::INWHICHEL				!INDEX FOR IDENTIFYING THE CONSIDERED ELEMENT WITHIN A STENCIL 
INTEGER::IXX					!INDEX FOR IDENTIFYING THE ELEMENT
INTEGER::JXX					!INDEX FOR IDENTIFYING THE ELEMENT OF THE STENCIL
INTEGER::KXX					!INDEX FOR IDENTIFYING THE DEGREE OF FREEDOM OF POLYNOMIALS
INTEGER::LXX					!INDEX FOR IDENTIFYING THE STENCIL 
INTEGER::ELTYPE					!INDEX FOR IDENTIFYING THE ELEMENT TYPE
INTEGER::LXX1					!INDEX FOR IDENTIFYING THE STENCIL 
INTEGER::NUMBER					!INDEX FOR THE NUMBER OF DEGREES OF FREEDOM
INTEGER::ICONSIDERED				!INDER FOR THE CONSIDERED CELL
INTEGER::SUBDIV					!INDEX FOR THE NUMBER OF SUBDIVISIONS OF A FACE
INTEGER::ICONSGVQ				!INDEX FOR CONSIDERED CELL
INTEGER::IGIANAGRAPS				!INDEX FOR CONSIDERED CELL
INTEGER::IT					!NUMBER OF ITERATIONS
INTEGER::ICONIMP				!INDEX FOR CONSIDERED CELL
INTEGER::IBCODE					!INDEX FOR BOUNDARY CONDITION CODE
INTEGER::IBSIDE					!INDEX FOR WHICH SIDE OF CELL IS BOUNDED
INTEGER::CFW					!INDEX FOR DETERMINING FROM THE WHICH SECTION THE BOUNDARY SUBROUTINE IS CALLED
INTEGER::LOWMEMORY				!MEMORY USAGE FLAG
INTEGER::FASTEST				!FASTEST MODE FLAG FOR THE CODE
INTEGER::EMETIS					!TYPE OF METIS PARTITIONING
INTEGER::ALLNODESGLOBALL			!TOTAL NUMBER OF NODES IN THE DOMAIN
INTEGER::SPATILADISCRET				!SPATIAL DISCRETISATION
INTEGER::SPATIALORDER    			!SPATIAL ORDER
INTEGER::JK					!INDEX
INTEGER::NUMNEIGHBOURS,NUMNEIGHBOURS2				!NUMBER OF NEIGHBOURS IN THE STENCILS EVENTUALLY WILL BE LOCAL
INTEGER::RESTART				!FLAG FOR DETERMINING IF A RESTART FILE IS PRESENT			
INTEGER::IHYBRID				!HYBRID MODE WHERE SOME PART OF THE DOMAIN IS SOLVED WITH LOWER ORDER AND ANOTHER WITH HIGHER ORDER SCHEMES				!
INTEGER::RESIDUALFREQ				!FREQUENCY FOR WRITING THE RESIDUALS
INTEGER::IRS					!IMPLICIT RESIDUAL SMOOTHING VERSION
INTEGER::GREENGO				!GRADIENT APPROXIMATION TECHNIQUES
INTEGER::LMACH					!LOW MACH PRECONDITIONING
INTEGER::ISPAL					!TYPE OF SPALART ALLMARAS MODIFICATION	
INTEGER::RELAX					!RELAXATION SCHEMES GAUSS SEIDEL, JACOBIAN ETC
INTEGER::ICONG					!INDEX FOR CONSIDERED CELL
INTEGER::ILOOP					!INDEX FOR CONSIDERED CELL
INTEGER::CFLRAMP				!CFL RAMPING ACTIVATED FOR IMPLICIT TIME STEPPING
INTEGER::IBFC					!FARFIELD DETERMINING FLAG SUPERSONIC SUBSONIC
INTEGER::AVERAGING				!FLAG FOR ACTIVATING AVERAGING OF TRANSIENT DATA
INTEGER::AVERAGE_RESTART			!FLAG FOR HAVING A RESTART FILE WITH THE AVERAGED SOLUTION
INTEGER::PREV_TURBMODEL				!FLAG OF PREVIOUS TURBULENCE MODEL IN CASE OF A RESTART FILE
INTEGER::IFORCE					!INDEX ON HOW OFTEN TO COMPUTE THE FORCES
INTEGER::BOUNDTYPE				!TYPE OF BOUNDARY CONDITION SUPERSONIC,  SUBSONIC
! INTEGER::RANK					
! INTEGER::RC
INTEGER::NPROC					!NUMBER OF CPUS							
INTEGER::INITCOND				!INITIAL CONDITION TYPE
INTEGER::WENWRT					!WENO WRT TO WHICH VARIABLE CONSERVED, CHARACTERISTICS ETC
INTEGER::POLY					!INTERPOLATING POLYNOMIALS 1 GENERIC, 2 LEGENDRE
INTEGER::IVORTEX				!Q CRITERION COM PUTATION
INTEGER::ICARLOS1				!INDEX FOR CONSIDERED ELEMENT PASSIVE SCALARS, COMPLICATED INFLOW CONDITION
INTEGER::ICARLOS2				!INDEX FOR CONSIDERED FACE PASSIVE SCALARS, COMPLICATED INFLOW CONDITION
INTEGER::IMAXE					!TOTAL NUMBER OF ELEMENTS OF THE GRID
INTEGER::NTMAX					!MAXIMUM NUMBER OF ITERATIONS
INTEGER::IHAX1					!TEMPORARY INTEGER USED AS POINTER FOR OPERATIONS REGARDING HEXAHEDRAL ELEMENTS					
INTEGER::LIMITER				!SLOPE LIMITER
INTEGER::IEXTEND				!EXTEND PARAMETER FOR CENTRAL BIG STENCIL ONLY FOR WENO CASES
INTEGER::IDEGFREE,IMAX,INUM,IDEG,inump,INUMO,idegfree2,imax2,inum2,ideg2,inump2,inumo2		!DEGREES OF FREEDOM OF POLYNOMIAL IT WILL BECOME LOCA	L
INTEGER::OUTSURF				!OUTSURF STANDS FOR COMPUTING FORCES 
INTEGER::UNWOU					!TYPE OF OUTPUT FILES TO WRITE ALL PARTITIONS TO ONE FILE ETC
INTEGER::IGQRULES				!GAUSSIAN QUADRATURE RULE
INTEGER::IMAXDEGFREE,IMAXDEGFREE2				!MAXIMUM NUMBER OF NEIGHBOURS
INTEGER::QP_HEXA,QP_TETRA,QP_PYRA,QP_PRISM,QP_QUAD,QP_TRIANGLE,QP_LINE,qp_line_n,reduce_comp,QP_QUAD_n,QP_TRIANGLE_n !VOLUME GAUSSIAN QUADRATURE POINTS
INTEGER::NUMBEROFPOINTS,NUMBEROFPOINTS2				
INTEGER::RESCOUNTER				!COUNTER FOR RESIDUALS
INTEGER::RESCOUNTERT				!COUNTER FOR TURBULENCE RESIDUALS
INTEGER::ILX					!DEGREES OF FREEDOM FOR REQUIRED ORDER OF ACCURACY
INTEGER::IMAXB					!TOTAL NUMBER OF BOUNDARY CONDITIONS
INTEGER::IMAXN					!TOTAL NUMBER OF NODES PRESENT IN THE GRID
INTEGER::IN					!INDEX FOR CONSIDERED CELL
INTEGER::IORDER,IORDER2					!ORDER OF ACCURACY (SPATIAL)
INTEGER::IOVERST				! NUMBER OF ELEMENTS FOR THE STENCIL OVERDETERMINED MATRIX REQUIRED FOR AVOIDING ILL CONDITIONS
INTEGER::IOVERTO				! NUMBER OF ELEMENTS FOR THE ESTAB STENCILS OVERDETERMINED MATRIX REQUIRED FOR AVOIDING ILL CONDITIONS
INTEGER::QRDE					!TYPE OF SOLUTION FOR THE LEAST SQUARES PROBLEM
INTEGER::RUNGEKUTTA     			!TIME STEPPING SCHEME TYPE
INTEGER::ISCHEME 				!TYPE OF SCHEME TO BE USED
INTEGER::ISPLIT					!UNSPLIT FINIT VOLUME SCHEME
INTEGER::ISELEM					!MAXIMUM NUMBER OF ELEMENTS REQUIRED FOR THE STENCIL DEPENDENT ON THE ORDER OF ACCURACY
INTEGER::ISTN					!VARIABLE THAT TAKES EACH TIME THE VALUE OF THE CONSIDERED ELEMENT  TO FIND NEIGHBOURS IN THE STENCIL
INTEGER::ITT,wenoz					!INTEGER VARIABLE USED FOR OPENING FILES
INTEGER::ITESTCASE
INTEGER::ITTT					!INTEGER OF LOGICAL OPERATION WHEN CONDITION IS SATISFIED AND THE ELEMENT IS SAVED IN THE ARRAY
INTEGER::IWEIGHTLSQR    			!WEIGHTED LEAST SQURES OPTION OF INVERTED DISTANCE
INTEGER::TYPESTEN				!NUMBER OF STENCILS FOR WENO
INTEGER::IPERIODICITY				!PERIODICITY DETECTED IN DOMAIN	
INTEGER::IWENO					!TYPE OF SCHEMES WENO, MUSCL, UNLIMITED
INTEGER::TURBULENCE				!TURBULENCE EQUATIONS
INTEGER::TURBULENCEMODEL			!WHICH MODEL
INTEGER::TURBULENCEEQUATIONS			!HOW MANY EQUATIONS TO SOLVE
INTEGER::ICOUPLETURB				!COUPLED TURBULENCE MODEL
INTEGER::IRIEMANN				!RIEMANN SOLVER
INTEGER::FIRSTORDER				!FIRST ORDER SCHEME ACTIVE
INTEGER::PASSIVESCALAR				!ADDITIONAL TRANSPORT EQUATIONS
INTEGER::QSAS_MODEL				!QSAS MODEL
INTEGER::VORT_MODEL				!VORTICITY MODEL
INTEGER::ZERO_TURB_INIT				!FLAG FOR TYPE OF INITIALIZATION FOR K-OMEGA
INTEGER::DES_MODEL 				!INTEGER SWITCHES FOR SST
INTEGER:: NPROBES,totwalls,NOF_INTERIOR,NOF_BOUNDED				!NUMBER OF PROBES FOR TRANSIENT DATA

!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.2.   INTEGER ALLOCATABLE VARIABLES HERE        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!

INTEGER,ALLOCATABLE,DIMENSION(:,:)::PROBEI	!probe positions
INTEGER,ALLOCATABLE,DIMENSION(:,:)::GLNEIGH	!GLOBALIST OF ALL THE NEIGHBOURS IN THE GRID
INTEGER,ALLOCATABLE,DIMENSION(:)::IWHICHSTEN,XSIZE,XGO,CHUNK_SIZE	!ALLOCATABLE INDEX FOR DESCRIBING WHICH STENCIL IS CONSIDERED WITHIN THE DIRECTIONAL STENCIL CONSTRUCTION ROUTINE
INTEGER,ALLOCATABLE,DIMENSION(:)::ISATISFIED	!ALLOCATABLE INDEX FOR DESCRIBING IF THE GEOMETRICAL CONDITIONS HAVE BEEN SATISFIED IN THE DIRECTIONAL STENCIL CONSTRUCTION ROUTINE
INTEGER,ALLOCATABLE,DIMENSION(:)::ISHYAPE,IBOUND_T,ibound_t2	!ALLOCATABLE INDEX FOR DESCRIBING THE SHYAPE OF THE CONSIDERED CELL
INTEGER,ALLOCATABLE,DIMENSION(:)::ISELEMT	!total number of elements in each stencil (extended one)
INTEGER,ALLOCATABLE,DIMENSION(:)::IX,XMPIALL,OFFSET,xmpiwall,woffset,xmpi_re,xmpi_wre		!allocatable index FOR STENCIL ROUTINE
INTEGER,ALLOCATABLE,DIMENSION(:)::IISTART	!allocatable index FOR STENCIL ROUTINE
INTEGER,ALLOCATABLE,DIMENSION(:)::IFSAT		!allocatable index FOR STENCIL ROUTINE
INTEGER,ALLOCATABLE,DIMENSION(:)::ISOSA,EL_INT,EL_BND
INTEGER,ALLOCATABLE,DIMENSION(:)::PARE,DOSE,PAREEL,PARES
INTEGER,ALLOCATABLE,DIMENSION(:,:)::DOSEEL,SOSEEL
INTEGER,ALLOCATABLE,DIMENSION(:,:,:,:)::ILOCALSTENCIL	!4-D ARRAY FOR STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:,:,:,:)::ILOCALALLELG	!4-D ARRAY FOR STENCILS 
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPIE			!GLOBAL LIST OF NUMBER OF ELEMENTS THAT BELONG TO EACH CPU
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPIL			!LOCAL LIST OF NUMBER OF ELEMENTS THAT BELONG TO EACH CPU
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPIN			!NOT USED CAN GET RID OF
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPIELRANK		!NUMBER OF ELEMENTS IN THIS CPU
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPINRANK		!NOT USED CAN GET RID OF
INTEGER,ALLOCATABLE,DIMENSION(:,:,:)::XMPINNUMBER	!NOT USED CAN GET RID OF
INTEGER,ALLOCATABLE,DIMENSION(:)::STCON			!DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:)::STCONC		!DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:)::STCONS		!DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:)::STCONG,LIST,INEB,IPERB,NODELIST		!DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:,:,:,:)::ILOCALALLS      !DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.3.   REAL VARIABLES HERE        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!
REAL::wenocentralweight,TIMESTEP,UPPERLIMIT,oo2,zero,voltemp,SHEAR_TEMP,forcex,forcey,forcez,extf,vorder
REAL::XD1		  	  		!X COORDINATES USED FOR THE POLYNOMIALS DERIVATIVES
REAL::YD1		  	  		!Y COORDINATES USED FOR THE POLYNOMIALS DERIVATIVES
REAL::ZD1		  	  		!Z COORDINATES USED FOR THE POLYNOMIALS DERIVATIVES
REAL::ANGLEFACEY				!ANGLE OF A FACE WITH RESPECT TO SPHERICAL COORDINATES THETA
REAL::ANGLEFACEX				!ANGLE OF A FACE WITH RESPECT TO SPHERICAL COORDINATES PHI
REAL::PI					!PI TRIGONOMETRI
REAL::X1,ax,ay,az,nx,ny,nz,nnx,nny,nnz					!X1 COORDINATE FOR BASIS FUNCTION COMPUTATION OF POLYNOMIALS
REAL::Y1					!Y1 COORDINATE FOR BASIS FUNCTION COMPUTATION OF POLYNOMIALS
REAL::Z1					!Z1 COORDINATE FOR BASIS FUNCTION COMPUTATION OF POLYNOMIALS
REAL::TAYLOR					!ONLY TO BE USED FOR TAYLOR GREEN VORTEX
REAL::VOLL					!TOTAL VOLUME OF THE DOMAIN	
REAL::UPTURBLIMIT				!UPPER TURBULENCE VISCOSITY RATIO
REAL::HYBRIDIST					!UPPER TURBULENCE VISCOSITY RATIO
REAL::VISCOTS					!EFFECTIVE VISCOCITY
REAL::REYNOLDS					!REYNOLDS NUMBER
REAL::CFLMAX					!MAXIMUM NUMBER OF ALLOWABLE CFL TO BE USED ONLY WITH IMPLICIT
REAL::PREVRES					!PREVIOUS RESIDUAL IN ORDER TO DETERMINE RAMPING STRATEGY
REAL::VECTORX					!SETTING UP WITH RESPECT TO WHICH PLANE THE AOA IS DEFINED X
REAL::VECTORY					!SETTING UP WITH RESPECT TO WHICH PLANE THE AOA IS DEFINED Y
REAL::VECTORZ					!SETTING UP WITH RESPECT TO WHICH PLANE THE AOA IS DEFINED Z
REAL::GRIDAR1					!ASPECT RATIO OF GRID
REAL::GRIDAR2					!MAXIMUM VOLUME ASPECT RATIO OF STENCILS
REAL::T						!TIME	
REAL::TOTALVOLUME				!TOTAL VOLUME OF DOMAIN
REAL::RESLIMIT       				!LIMIT TO STOP THE SIMULATION
REAL::ANGLE1					!ANGLE
REAL::ANGLE2					!ANGLE
REAL::RES_TIME					!RESTART_TIME
REAL::IEVERY2					!HOW OFTEN TO WRITE OUTPUT
REAL::WALLC					!WALL CLOCK LIMIT IN SECONDS
REAL::BETAAS					!BETAAS OF SUTHERLAND EXPONENT
REAL::SUTHER					!SUTHERLAND NON DIMENSIONAL CONSTANT OF TEMPERATURE
REAL::PRANDTL					!PRANDTL NUMBER
REAL::SCALER					!FOR SCALING THE MESH 
REAL::LWCI1					!LINEAR WENO WEIGHT OF CENTRAL STENCILS				!
REAL::RESMAX					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::RESMAXT					!RESIDUAL DIMENSIONAL TURBULENCE
REAL::CFL					!CFL NUMBER
REAL::IEVERY,MODEIO					!HOW OFTEN TO WRITE OUTPUT
REAL::IEVERYAV					!HOW OFTEN TO WRITE OUTPUT OF AVERAGE SOLUTION
REAL:: FIRSTRESU				!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESV					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESW					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESE					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESR					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTREST					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESK					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESOMEGA				!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESPASS				!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::GAMMA 					!GAS CONSTANT
REAL::UVEL					!U VELOCITY
REAL::UFREESTREAM				!U VELOCITY
REAL::VVEL					!V-VELOCITY
REAL::WVEL					!W-VELOCITY
REAL::PRES					!PRESSURE
REAL::RRES					!DENSITY
REAL::SPOS					!SPEED OF SOUND
REAL::ETOT					!TOTAL ENERGY
REAL::SPKIN					!SPECIFIC KINETIC ENERGY
REAL::LAM					!HEAT CONDUCTIVITY (WATT/(MK))
REAL::VISC					!VISCOSITY
REAL::LAMX					!FLAGS TO BE USED FOR RESTARTING
REAL::LAMY					!FLAGS TO BE USED FOR RESTARTING
REAL::LAMZ					!FLAGS TO BE USED FOR RESTARTING
					!FLAGS TO BE USED FOR RESTARTING
REAL::OUT_TIME					!FINAL TIME TO WRITE OUTPUT FOR UNSTEADY SIMULATIONS
REAL::XPER					!PERIODICITY IN X AXIS
REAL::YPER					!PERIODICITY IN Y AXIS
REAL::ZPER					!PERIODICITY IN Z AXIS
REAL::AOA					!ANGLE OF ATTACK	
REAL::CHARLENGTH				!CHARACTERISTIC LENGTH IF UNDEFINED, AND REYNOLDS UNDEFINED THE FREE STREAM WILL BE USED FOR AIR
						!TURBULENCE MODEL constants
REAL::TURBINIT				!TURBULENCE INITIAL VALUE VT/V
REAL::CB1
REAL::CB2
REAL::SIGMA
REAL::KAPPA
REAL::CW1
REAL::CW2
REAL::CW3
REAL::CV1
REAL::CT1
REAL::CT2
REAL::CT3
REAL::CT4
REAL::PRTU
REAL::TWALL


REAL::SIGMA_K1
REAL::SIGMA_K2
REAL::SIGMA_OM1
REAL::SIGMA_OM2
REAL::AA_1
REAL::BETA_I1
REAL::BETA_I2
REAL::ALPHA_STARINF
REAL::ALPHA_0
REAL::BETA_STARINF
REAL::R_BETA
REAL::R_K_SST
REAL::BETA_T
REAL::KAPPA_SST
REAL::R_OM_SST
REAL::ZETA_STAR
REAL::M_T0
REAL::C_SMG
REAL::ETA2_SAS
REAL::SIGMA_PHI
REAL::C_SAS
REAL::ALPHA_INF1
REAL::ALPHA_INF2
REAL::ALPHA_STAR0
REAL::C_MU_INLET   						!FUNCTIONS FOR SST
REAL::L_TURB_INLET
REAL::I_TURB_INLET
REAL::INIT_MU_RATIO
REAL::C_DES_SA
REAL::C_DES_SST
REAL:: SCHMIDT_LAM
REAL::SCHMIDT_TURB
real::tolsmall,TOLBIG,allresdt,tz1
REAL,DIMENSION(7)::ALLRES,INITIALRES
!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.4.   REAL ALLOCATABLE VARIABLES HERE        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!
INTEGER,ALLOCATABLE,DIMENSION(:,:)::ILOCALALLELG3
REAL,ALLOCATABLE,DIMENSION(:,:)::ILOCALALLELGD,b_char,x_Char
REAL,ALLOCATABLE,DIMENSION(:,:,:)::ba_char,a_char
real::a_rot,c_rot,b_rot,root_rot,sheartemp
REAL,ALLOCATABLE,DIMENSION(:)::WEIGHT_T2
!$OMP THREADPRIVATE(b_char,x_Char,INSTEN,llx,varcons,pointx,ba_char,a_char,ICONS_S,ICONS_E,compwrt,ILOCALALLELGD,ILOCALALLELG3,STCON,STCONC,STCONS,STCONG,ISOSA,IX,IFSAT,IISTART,SHEARTEMP,IMAX,NUMBER_OF_NEI,b_code,INUM,angle1,angle2,IDEG,n_node,inump,INUMO,inumo2,ideg2,m2,inump2,imax2,A_ROT,C_ROT,B_ROT,ROOT_ROT,ANGLEFACEX,ANGLEFACEY,voltemp)
REAL,ALLOCATABLE,DIMENSION(:,:)::VVA,VVA1,lscqm1,xxder,yyder,zzder
REAL,ALLOCATABLE,DIMENSION(:)::B1_imp,DU1,DU2,DUMMY12,C1_imp,DUR,DUL,DURR,DULR,DUT1,B1T,DUMMY12T,SOURCE_T,sb,DETA,UTMIN,UTMAX,VVr1,VVr2,VVr3,VVR4,VVwg,VVnpox,VVnpoy,VVnpoz,VVwpox,VVwpoy,VVwpoz,VVnxi,VVneta,VVnzeta,VVxi,VVeta,VVzeta,VVnallx,VVnally,VVnallz,VVB,VVC,VVD,VVE,VVF,vvjacobsurf,vvjacobvolume
!$OMP THREADPRIVATE(sb,IBFC,lamx,lamy,lamz,number_of_dog,WEIGHT_T2,lscqm1,B1_imp,DU1,DU2,DUMMY12,xxder,yyder,zzder,C1_imp,DUR,DUL,DURR,DULR,DUT1,B1T,DUMMY12T,SOURCE_T,UTMIN,UTMAX,ax,ay,az,nx,ny,nz,nnx,nny,nnz,VVA,DETA,VVA1,VVr1,VVr2,VVr3,VVR4,VVwg,VVnpox,VVnpoy,VVnpoz,VVwpox,VVwpoy,VVwpoz,VVnxi,VVneta,VVnzeta,VVxi,VVeta,VVzeta,VVnallx,VVnally,VVnallz,VVB,VVC,VVD,VVE,VVF,vvjacobsurf,vvjacobvolume)

	
REAL,ALLOCATABLE,DIMENSION(:)::CLEFT,lamc 	   	!VALUE OF THE RECONSTRUCTED SOLUTION REFERING TO MY CELL (I) CONSERVED VARIABLE
REAL,ALLOCATABLE,DIMENSION(:)::CLEFT_ROT 	!VALUE OF THE RECONSTRUCTED SOLUTION REFERING TO MY CELL (I) ROTATED WITH RESPECT TO ITS  FACE CONSERVED VARIABLE
REAL,ALLOCATABLE,DIMENSION(:)::CRIGHT		!VALUE OF THE RECONSTRUCTED SOLUTION REFERING TO THE NEIGHBOUR OF MY CELL (I) CONSERVED VARIABLE
REAL,ALLOCATABLE,DIMENSION(:)::CRIGHT_ROT	!VALUE OF THE RECONSTRUCTED SOLUTION REFERING TO THE NEIGHBOUR OF MY CELL (I) ROTATED WITH RESPECT TO ITS  FACE CONSERVED VARIABLE
REAL,ALLOCATABLE,DIMENSION(:)::SL		!WAVE SPEED ESTIMATE OF LEFT STATE OF THE SOLUTION OF A FACE 
REAL,ALLOCATABLE,DIMENSION(:)::SR		!WAVE SPEED ESTIMATE OF RIGHT STATE OF THE SOLUTION OF A FACE 
REAL,ALLOCATABLE,DIMENSION(:)::SM		!WAVE SPEED ESTIMATE OF STAR REGION ACCORDING TO RIEMANN SOLVER FAN
REAL,ALLOCATABLE,DIMENSION(:)::CTURBL		!VALUE OF THE RECONSTRUCTED SOLUTION OF ADDITIONAL EQUATIONS REFERING TO MY CELL (I)  PRIMITIVE VARIABLE
REAL,ALLOCATABLE,DIMENSION(:)::CTURBR		!VALUE OF THE RECONSTRUCTED SOLUTION OF ADDITIONAL EQUATIONS REFERING TO  THE NEIGHBOUR OF MY CELL (I)  PRIMITIVE VARIABLE
REAL,ALLOCATABLE,DIMENSION(:)::ROTVL		!VALUE OF THE RECONSTRUCTED SOLUTION REFERING TO MY CELL (I) ROTATED WITH RESPECT TO ITS  FACE PRIMITIVE VARIABLE
REAL,ALLOCATABLE,DIMENSION(:)::ROTVR		!VALUE OF THE RECONSTRUCTED SOLUTION REFERING TO THE NEIGHBOUR OF MY CELL (I) ROTATED WITH RESPECT TO ITS  FACE PRIMITIVE VARIABLE
REAL,ALLOCATABLE,DIMENSION(:)::HLLCFLUX		!VALUE OF THE RIEMANN SOLUTION  NORMAL TO FACE DIRECTION 
REAL,ALLOCATABLE,DIMENSION(:)::RHLLCFLUX	!VALUE OF THE RIEMANN SOLUTION AT CARTESIAN COORDINATES
REAL::L1NORM		!L1 NORM OF SOLUTION FOR GRID CONVERGENCE STUDIES OF EULER AND LINEAR ADVECTION EQUATIONS
REAL::L2NORM		!L2 NORM OF SOLUTION FOR GRID CONVERGENCE STUDIES OF EULER AND LINEAR ADVECTION EQUATIONS
REAL::L0NORM,STENNORM		!L0 NORM OF SOLUTION FOR GRID CONVERGENCE STUDIES OF EULER AND LINEAR ADVECTION EQUATIONS
REAL::DT 					!REAL TIME STEP SIZE       
REAL,ALLOCATABLE,DIMENSION(:)::GODFLUX		!THE FLUX FOR THE GODUNOV ONLY TO BE USED WITH LINEAR ADVECTION EQUATION
REAL,ALLOCATABLE,DIMENSION(:,:)::WEFF		!GEOMETRIC SMOOTHNESS INDICATOR FOR WENO SCHEMES  SEE PAPER TSOUTSANIS ET AL
REAL,ALLOCATABLE,DIMENSION(:)::AVRG		!TEMPORARY SOLUTION AVERAGES
REAL,ALLOCATABLE,DIMENSION(:)::POX		!POSITION COORDINATES X
REAL,ALLOCATABLE,DIMENSION(:)::POY		!POSITION COORDINATES Y
REAL,ALLOCATABLE,DIMENSION(:)::POZ		!POSITION COORDINATES Z
REAL,ALLOCATABLE,DIMENSION(:,:)::JAC		!jacobians
REAL,ALLOCATABLE,DIMENSION(:,:)::INVERSEJAC	!inverse jacobians
REAL,ALLOCATABLE,DIMENSION(:)::DETERJAC		!determinant jacobians
REAL,ALLOCATABLE,DIMENSION(:,:)::PROBEC		!probe positions
REAL,ALLOCATABLE,DIMENSION(:,:)::JACS		!jacobians
REAL,ALLOCATABLE,DIMENSION(:,:)::INVERSEJACS	!inverse jacobians
REAL,ALLOCATABLE,DIMENSION(:)::DETERJACS	!determinant jacobians
REAL,ALLOCATABLE,DIMENSION(:)::EDDYFL		!EDDY VISCOSITY CALCULATION INPUT LEFT STATE
REAL,ALLOCATABLE,DIMENSION(:)::EDDYFR		!EDDY VISCOSITY CALCULATION INPUT RIGHT STATE
REAL,ALLOCATABLE,DIMENSION(:,:)::IMPDU		!IMPLICIT ONLY CHANGE OF SOLUTION
REAL,ALLOCATABLE,DIMENSION(:,:)::TRI		!MATRIX FOR TRANSFORMATION
REAL,ALLOCATABLE,DIMENSION(:,:,:)::IMPDIAG	!IMPLICIT ONLY DIAGONAL MATRIX D
REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::IMPOFF	!IMPLICIT ONLY OFF DIAGONAL MATRIX D
REAL,ALLOCATABLE,DIMENSION(:,:,:)::IMPOFFT	!IMPLICIT ONLY OFF DIAGONAL MATRIX D FOR TURBULENCE
REAL,ALLOCATABLE,DIMENSION(:,:)::IMPDIAGT	!IMPLICIT ONLY  DIAGONAL MATRIX D FOR TURBULENCE
REAL,ALLOCATABLE,DIMENSION(:,:)::SHT		!IMPLICIT ONLY  SORUCE TERM JACOBIAN
REAL,ALLOCATABLE,DIMENSION(:,:)::INVTRI		!INVERSE MATRIX FOR TRANSFORMATION
REAL,ALLOCATABLE,DIMENSION(:)::ROTVECT		!ROTATED VECTOR OF CONSERVED VARIABLES
REAL,ALLOCATABLE,DIMENSION(:)::VECTCO		! VECTOR OF CONSERVED VARIABLES
REAL,ALLOCATABLE,DIMENSION(:)::XMIN		!SE
REAL,ALLOCATABLE,DIMENSION(:)::XMAX		!SE
REAL,ALLOCATABLE,DIMENSION(:)::YMIN		!SE
REAL,ALLOCATABLE,DIMENSION(:)::YMAX		!SE
REAL,ALLOCATABLE,DIMENSION(:)::ZMIN		!SE
REAL,ALLOCATABLE,DIMENSION(:)::ZMAX		!SE
REAL,ALLOCATABLE,DIMENSION(:)::LEFTV		!LEFT STATE VARIABLES
REAL,ALLOCATABLE,DIMENSION(:)::RIGHTV		!RIGHT STATE VARIABLES
REAL,ALLOCATABLE,DIMENSION(:)::VISCL		!LAMINAR VISCOSITY ACCORDING TO SUTHERLAND
REAL,ALLOCATABLE,DIMENSION(:)::LAML		!HEAT CONDUCTIVITY ACCORDING TO SUTHERLAND
REAL,ALLOCATABLE,DIMENSION(:)::ETVM		!EDDY VISCOSITY
REAL,ALLOCATABLE,DIMENSION(:)::TURBMV		!ADVECTED TURBULENCE PARAMETER
REAL::NORMALVECT	!NORMAL VECTOR
REAL,ALLOCATABLE,DIMENSION(:)::CPUX1		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX2		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX3		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX4		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX5		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX6		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX7		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX1		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX2		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX3		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX4		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX5		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX6		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::VEIGL		! VECTOR OF CHARACTERISTIC VARIABLES LEFT STATE
REAL,ALLOCATABLE,DIMENSION(:)::VEIGR		! VECTOR OF CHARACTERISTIC VARIABLES RIGHT STATE
REAL,ALLOCATABLE,DIMENSION(:)::RVEIGL		! ROTATED VECTOR OF CHARACTERISTIC VARIABLES LEFT STATE
REAL,ALLOCATABLE,DIMENSION(:)::RVEIGR		! ROTATED VECTOR OF CHARACTERISTIC VARIABLES RIGHT STATE
REAL,ALLOCATABLE,DIMENSION(:,:)::EIGVL		!EIGENVECTOR MATRIX 
REAL,ALLOCATABLE,DIMENSION(:,:)::EIGVR		!INVERSE EIGENVECTOR MATRIX
REAL,ALLOCATABLE,DIMENSION(:,:)::VEXT		!VERTICES ARRAY
REAL,ALLOCATABLE,DIMENSION(:,:)::IFIN		!TEMPORARY POINTER FOR SYNC OUTPUT
REAL,ALLOCATABLE,DIMENSION(:,:)::TFIN		!TEMPORARY POINTER FOR SYNC OUTPUT
REAL,ALLOCATABLE,DIMENSION(:,:)::CENTERR	!FOR DIRECTIONAL STENCILS	
REAL,ALLOCATABLE,DIMENSION(:,:)::BC		!FOR DIRECTIONAL STENCILS
REAL,ALLOCATABLE,DIMENSION(:,:)::VG		!FOR DIRECTIONAL STENCILS
REAL,ALLOCATABLE,DIMENSION(:,:,:)::VC		!FOR DIRECTIONAL STENCILS
REAL,ALLOCATABLE,DIMENSION(:)::VECCOS,turbc1,turbc2,tempflux2,SUBSON1,SUBSON2,SUBSON3		!VECTOR OF CONSERVED VARIABLES
REAL,ALLOCATABLE,DIMENSION(:)::TEMPFL,TEMPFR,FLSTAR,FRSTAR,ULSTAR,UrSTAR,TEMPUL,TEMPUR,FL,FR,RML,RMR
REAL,ALLOCATABLE,DIMENSION(:)::WEQUA3D		!WEIGHTS OF GAUSSIAN QUADRATURE POINTS 3D
REAL,ALLOCATABLE,DIMENSION(:)::WEQUA2D		!WEIGHTS OF GAUSSIAN QUADRATURE POINTS 2D
REAL,ALLOCATABLE,DIMENSION(:,:)::QPOINTS2D	!GUASSIAN OF GAUSSIAN QUADRATURE POINTS 2D
REAL,ALLOCATABLE,DIMENSION(:,:)::QPOINTS	!WEIGHTS OF GAUSSIAN QUADRATURE POINTS 2D
!$OMP THREADPRIVATE(WEQUA3D,WEQUA2D,QPOINTS2D,QPOINTS)
REAL,ALLOCATABLE,DIMENSION(:)::CORDS
REAL,ALLOCATABLE,DIMENSION(:,:)::NODES_LIST
REAL,ALLOCATABLE,DIMENSION(:,:,:)::ELEM_LISTD
!$OMP THREADPRIVATE(TEMPFL,lamc,TEMPFR,FLSTAR,FRSTAR,ULSTAR,UrSTAR,TEMPUL,TEMPUR,FL,FR,RML,RMR,NODES_LIST,VEXT,ELTYPE,ELEM_DEC,ELEM_LISTD,DETERJACS,JACS,INVERSEJACS,LEFTV,RIGHTV,CORDS,VISCL,LAML,ETVM,TURBMV)
REAL,ALLOCATABLE,DIMENSION(:)::XCC,vgg
integer, allocatable,dimension(:)::cand,CANDS,CANDR
integer, allocatable,dimension(:,:)::CANDXR,candxS,CAND2S
integer, allocatable,dimension(:,:,:)::CAND2R
REAL, allocatable,dimension(:,:)::XAND2S
REAL, allocatable,dimension(:,:,:)::XAND2R

real,allocatable,dimension(:,:)::PQR,SIND1,SIND2,SIND3,SIND4,SIND5,SIND6,MATRIX_A,LSQM,VELLSQMAT,MATRIX_SOLUTION,MATRIXFACE,JUSTCHECK,Q,R,QT,INVR,LSCQM,LSCQM2
real,allocatable,dimension(:,:)::QFF,RFF,QTFF,INVRFF,AINVJT
real,allocatable,dimension(:)::VQR,VQR1,XQR,MATRIX_B,MATRIX_X,BASEFACEVAL,BASEFACGVAL,MOMENT,WEIGHTINV,VECTOR,INTBS,XDER,YDER,ZDER
integer,allocatable,dimension(:)::permutation,permutationg

!$OMP THREADPRIVATE(NORMALVECT,Q,R,QT,WEFF,MATRIX_A,LSQM,XCC,vgg,VELLSQMAT,MATRIX_SOLUTION,MATRIXFACE,JUSTCHECK,PDIM,XQR,VQR,VQR1,PQR,INVR,LSCQM,LSCQM2,ivgt)
!$OMP THREADPRIVATE(QFF,RFF,QTFF,INVRFF,AINVJT,MATRIX_B,MATRIX_X,BASEFACEVAL,BASEFACGVAL,MOMENT,WEIGHTINV,VECTOR,INTBS,PERMUTATION,PERMUTATIONG,XDER,YDER,ZDER)


!$OMP THREADPRIVATE(IXX,JXX,KXX,LXX1,NUMBER,ICONSIDERED,X1,Y1,Z1,facex,ixxff,iconsi,lxx,VECCOS)

!$OMP THREADPRIVATE(CLEFT,cleft_rot,cright,cright_rot,sl,sr,sm,HLLCFLUX)
!$OMP THREADPRIVATE(RHLLCFLUX,ROTVL,ROTVR,SUBSON1,SUBSON2,SUBSON3,CTURBL,CTURBr)
!$OMP THREADPRIVATE(turbc1,turbc2,tempflux2,TRI,INVTRI,ROTVECT,VECTCO,VEIGL,VEIGR,RVEIGL,RVEIGR,EIGVL,EIGVR,POX,POY,POZ)

REAL,ALLOCATABLE,DIMENSION(:)::GRADSV,VORTEM1,VERTF1,vertex1,DERIVTURB1,UGRADLOC,GRADVEL,GRADTEM,GRAD1AL,grad3al,INDICATEMATRIXAL,SMOOTHINDICATORAL,LAMBDAAL,OMEGAATILDEL,OMEGAAL,SUMOMEGATILDE
REAL,ALLOCATABLE,DIMENSION(:)::VECL,VECR,CFAST,LSOLP,RSOLP,SUMGGU,SUMGGV,SUMGGW,SUMGGP,SUMGGT,SUMGGT2
REAL,ALLOCATABLE,DIMENSION(:)::MATRIX_BN3,MATRIX_BN4,MATRIX_BN5,MATRIX_B1,MATRIX_B2,MATRIX_B3,MATRIX_B4,MATRIX_B5,Xxx
REAL,ALLOCATABLE,DIMENSION(:)::X2,MATRIX_BWC,MATRIX_BN,MATRIX_BN1,MATRIX_BN2
REAL,ALLOCATABLE,DIMENSION(:,:)::GRADSS,VORTET1,consmatrix,consmatrixc,RFFAST,RRFFAST,tempsc,UTEMP
REAL,ALLOCATABLE,DIMENSION(:,:)::GRAD1,GRAD2,grad5alc,INDICATEMATRIX,GRADCHAR,LIMITEDDW,WENOO,WENO,WENO2,GRADSSL,RESSOLUTION
REAL,ALLOCATABLE,DIMENSION(:,:,:)::USOL,PSI,GRADCHARV,LIMITEDDW_CHAR
REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::FINDW,SMOOTHINDICATOR,LAMBDA,OMEGATILDE,OMEGA,WENOOS,OMEGAATILDE
REAL,ALLOCATABLE,DIMENSION(:,:,:,:,:)::FINDW_CHAR
!$OMP THREADPRIVATE(GRADSV,VORTEM1,VERTF1,vertex1,DERIVTURB1,UGRADLOC,GRADVEL,GRADTEM,GRAD1AL,INDICATEMATRIXAL,OMEGAATILDE,SMOOTHINDICATORAL,LAMBDAAL,OMEGAATILDEL,OMEGAAL,SUMOMEGATILDE,RESSOLUTION)
!$OMP THREADPRIVATE(VECL,VECR,CFAST,LSOLP,RSOLP,SUMGGU,SUMGGV,SUMGGW,SUMGGP,SUMGGT,SUMGGT2)
!$OMP THREADPRIVATE(MATRIX_BN3,MATRIX_BN4,MATRIX_BN5,MATRIX_B1,MATRIX_B2,MATRIX_B3,MATRIX_B4,MATRIX_B5,Xxx)
!$OMP THREADPRIVATE(X2,MATRIX_BWC,MATRIX_BN,MATRIX_BN1,MATRIX_BN2)
!$OMP THREADPRIVATE(GRADSS,VORTET1,consmatrix,consmatrixc,RFFAST,RRFFAST,tempsc,UTEMP)
!$OMP THREADPRIVATE(GRAD1,GRAD2,grad5alc,grad3al,INDICATEMATRIX,GRADCHAR,LIMITEDDW,LIMITEDDW_CHAR,WENOO,WENO,WENO2,GRADSSL)
!$OMP THREADPRIVATE(USOL,PSI,GRADCHARV)
!$OMP THREADPRIVATE(FINDW,SMOOTHINDICATOR,FINDW_CHAR,LAMBDA,OMEGATILDE,OMEGA,WENOOS,ISHYAPE,ISATISFIED,IWHICHSTEN,VG,VC,BC)



!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.5.   DATA TYPE VARIABLES HERE        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!



TYPE::U_CENTRE					!DATA TYPE THAT HOLDS THE CELL CENTER VALUES FOR THE EQUATIONS TO BE SOLVED
	REAL,ALLOCATABLE,DIMENSION(:,:)::VAL	!ACTUAL VALUES (FIRST INDEX CORRESPONDS TO RUNGE-KUTTA STAGE,THE SECOND ONE CORRESPONDS TO NUMBER OF VARIABLES FOR MEAN FLOW EQUATIONS)
	REAL,ALLOCATABLE,DIMENSION(:)::RMS	!RMS VALUES OF THE CONSERVED VECTOR IN CASE OF TRANSIENT SIMULATIONS
END TYPE U_CENTRE

TYPE::FACE_D
	INTEGER,ALLOCATABLE,DIMENSION(:)::Q_MAPL,QMAPD
END TYPE FACE_D

TYPE(U_CENTRE),ALLOCATABLE,DIMENSION(:)::U_C 	!1-D ARRAY FOR TYPE FOR SOLUTION OF MEAN FLOW EQUATIONS
TYPE(U_CENTRE),ALLOCATABLE,DIMENSION(:)::U_CT 	!1-D ARRAY FOR TYPE FOR SOLUTION OF TURBULENT EQUATIONS 


TYPE::U_EXACT					!DATA TYPE THAT HOLDS THE CELL CENTER VALUES OF THE EXACT SOLUTION FOR LINEAR ADVECTION OF EULER EQUATIONS IF AN EXACT SOLUTION EXISTS
	REAL,ALLOCATABLE,DIMENSION(:,:)::VAL	!VALUES OF THE EXACT SOLUTION
END TYPE U_EXACT
TYPE(U_EXACT),ALLOCATABLE,DIMENSION(:)::U_E	!1-D ARRAY FOR TYPE FOR EXACT SOLUTION OF MEAN FLOW EQUATIONS


TYPE::SUMFLUXES					!DATA TYPE FOR THE FLUXES CONTRIBUTION
	REAL,ALLOCATABLE,DIMENSION(:)::VAL	!NUMBER OF VALUES FOR THE FLUXES
END TYPE SUMFLUXES
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SUMCONFLUX	!CONVECTIVE FLUXES MEAN FLOW EQUATIONS
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SUMVISCFLUX	!VISCOUS FLUXES MEAN FLOW EQUATIONS
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SOURCETERM	!SOURCETERM
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SUMCONFLUXT	!CONVECTIVE FLUXES ADDITIONAL EQUATIONS
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SUMVISCFLUXT  !VISCOUS FLUXES ADDITIONAL EQUATIONS
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::RHS		!RIGHT HAND SIDE OF THE MEAN FLOW EQUATIONS (SUM OF ALL FLUXES CONTRIBUTIONS)
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::RHST		!RIGHT HAND SIDE OF THE ADDITIONAL FLOW EQUATIONS (SUM OF ALL FLUXES CONTRIBUTIONS)


TYPE INTEGRALBASIS 
	REAL,allocatable,dimension(:)::VALUE,VALUEc
END TYPE INTEGRALBASIS
TYPE(INTEGRALBASIS),ALLOCATABLE,DIMENSION(:)::INTEG_BASIS


TYPE LOCAL_ELEMENT
	INTEGER::IADMIS
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXG
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXL
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXB
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXN
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::ISHAPE
	REAL,ALLOCATABLE,DIMENSION(:,:)::XXC
	REAL,ALLOCATABLE,DIMENSION(:,:)::YYC
	REAL,ALLOCATABLE,DIMENSION(:,:)::ZZC
	REAL,ALLOCATABLE,DIMENSION(:,:)::VOLUME
END TYPE LOCAL_ELEMENT



TYPE(LOCAL_ELEMENT),ALLOCATABLE,DIMENSION(:)::ILOCAL_ELEM

TYPE LOCAL_NODE
	INTEGER::IADMIS
	INTEGER,ALLOCATABLE,DIMENSION(:,:,:)::NODCOUNT
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::X
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::Y
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::Z
END TYPE LOCAL_NODE

TYPE(LOCAL_NODE),ALLOCATABLE,DIMENSION(:)::ILOCAL_NODE
!$OMP THREADPRIVATE(ILOCAL_NODE,ILOCAL_ELEM)
TYPE LOCAL_RECON3
	INTEGER::LOCAL
	REAL,ALLOCATABLE,DIMENSION(:)::cond
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXG,IHEXGc
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXL,IHEXLc
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXB,ihexbc
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXN,ihexnc
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::GRADIENTS,GRADIENTSc
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::GRADIENTSTURB
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::GRADIENTSTURB_wall
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::GRADIENTS2,GRADIENTSC2
	REAL,ALLOCATABLE,DIMENSION(:)::GRADIENTSTEMP
	REAL,ALLOCATABLE,DIMENSION(:,:)::GRADIENTSTEMP_wall
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::CGRADIENTSTEMP
	REAL,ALLOCATABLE,DIMENSION(:,:)::VELOCITYDOF
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::VELOCITYDOF_wall
	REAL,ALLOCATABLE,DIMENSION(:,:)::INVCCJAC
	REAL,ALLOCATABLE,DIMENSION(:,:)::INVCTJAC
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::CVELOCITYDOF
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::STENCILS,STENCILSc
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::INVMAT
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::INVMAT_STENCILT,INVMAT_STENCILTc
	REAL,ALLOCATABLE,DIMENSION(:,:)::VOLUME,VOLUMEc
	REAL,ALLOCATABLE,DIMENSION(:,:)::GRADS,GRADSAV
	REAL,ALLOCATABLE,DIMENSION(:,:)::WALLD
	REAL,ALLOCATABLE,DIMENSION(:,:)::VERTEX
	REAL,ALLOCATABLE,DIMENSION(:,:)::FACESCORD
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::ULEFT
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::QPOINTS
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::ULEFTTURB
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::ULEFTV
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::ULEFTTURBV
	REAL,ALLOCATABLE,DIMENSION(:,:)::WENO
	REAL,ALLOCATABLE,DIMENSION(:,:)::WENO2
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::WENOS
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::FINDW
	REAL,ALLOCATABLE,DIMENSION(:,:)::INDICATOR,INDICATORC
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::WGAUSS
	REAL,ALLOCATABLE,DIMENSION(:,:)::TRIAP
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::VERT
	REAL,ALLOCATABLE,DIMENSION(:,:)::INDIC
	REAL,ALLOCATABLE,DIMENSION(:,:)::TEMPSQ
	REAL,ALLOCATABLE,DIMENSION(:,:)::TEMPSQMAT,TEMPSQMAT2
	REAL,ALLOCATABLE,DIMENSION(:,:)::VELLSQ
	REAL,ALLOCATABLE,DIMENSION(:,:)::VELINVLSQMAT,VELINVLSQMAT2
	REAL,ALLOCATABLE,DIMENSION(:)::WALLCOEFF
	REAL,ALLOCATABLE,DIMENSION(:)::WALLCOEFG
	INTEGER,ALLOCATABLE,DIMENSION(:)::send_cpu,send_side
	INTEGER::G0
	INTEGER::K0
	REAL,ALLOCATABLE,DIMENSION(:)::VEXT_REF
END TYPE LOCAL_RECON3

TYPE::NEIXX
      INTEGER::CPU
      INTEGER,ALLOCATABLE,DIMENSION(:,:)::ELEM1
      REAL,ALLOCATABLE,DIMENSION(:)::CENTERS
END TYPE NEIXX



TYPE(LOCAL_RECON3),ALLOCATABLE,DIMENSION(:)::ILOCAL_RECON3
TYPE(NEIXX),ALLOCATABLE,DIMENSION(:)::NEIX1,NEIX2,NEIX3,NEIX4,NEIX5
TYPE(LOCAL_RECON3),ALLOCATABLE,DIMENSION(:)::ILOCAL_RECON4,ILOCAL_RECON5

TYPE EXCHANGE_CORD
	INTEGER::PROCID
	INTEGER::HOWMANY
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::NODECORD
END TYPE EXCHANGE_CORD

TYPE(EXCHANGE_CORD),ALLOCATABLE,DIMENSION(:)::IEXCORDR
TYPE(EXCHANGE_CORD),ALLOCATABLE,DIMENSION(:)::IEXCORDS


TYPE EXCHANGE_SOLHI
	INTEGER::PROCID
	INTEGER::IAVT
	INTEGER::IAVC
	INTEGER::FAST
	INTEGER::HOWMANY
	REAL,ALLOCATABLE,DIMENSION(:,:)::SOL
END TYPE EXCHANGE_SOLHI

TYPE(EXCHANGE_SOLHI),ALLOCATABLE,DIMENSION(:)::IEXSOLHIR
TYPE(EXCHANGE_SOLHI),ALLOCATABLE,DIMENSION(:)::IEXSOLHIS



TYPE EXCHANGE_BOUNDHI
	INTEGER::PROCID
	INTEGER::IAVT
	INTEGER::FAST
	INTEGER::HOWMANY
	REAL,ALLOCATABLE,DIMENSION(:,:)::FACESOL
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::QUADP
	integer,allocatable,dimension(:,:)::vertpp
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::VERT
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::WQUAD
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::ANGLES
	REAL,ALLOCATABLE,DIMENSION(:,:)::TRIAP
	REAL,ALLOCATABLE,DIMENSION(:,:)::NORMALS
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::FACESOLV
END TYPE EXCHANGE_BOUNDHI

TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIR
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIS
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIRi
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIsi
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIRR
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHISS


TYPE RECON_FACES3
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::NEIGH1
	REAL,DIMENSION(7)::NONLINEAR
END TYPE RECON_FACES3










TYPE::NODE_NUMBER	!NAME OF TYPE FOR THE SET OF NODES 
	INTEGER::NODEN	!IDENTIFICATION NUMBER THAT CAN BE USED AS A POINTER INSIDE AN ARRAY
	INTEGER::BLOCKN !BLOCK NUMBER OR CPU NUMBER OF THIS ELEMENT
	INTEGER::NODEGL
	REAL::X		!COORDINATES IN X AXIS
	REAL::Y		!COORDINATES IN Y AXIS
	REAL::Z		!COORDINATES IN Z AXIS
END TYPE NODE_NUMBER 


TYPE(NODE_NUMBER),ALLOCATABLE,DIMENSION(:,:)::INODE	  !1-D ARRAY FOR POINTER TYPE FOR NODES

TYPE(NODE_NUMBER)::ITEMP				  !TEMPORARY POINTER NODE ITERATION


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
TYPE::NODE_NE	!NAME OF TYPE FOR THE SET OF NODES 
! 	INTEGER::NUMBEROFNEIB
	INTEGER::itor
! 	INTEGER,allocatable,dimension(:)::NEIBIDS,xne,xneib
	real,allocatable,dimension(:)::cord
END TYPE NODE_NE
TYPE::NODE_LIT	!NAME OF TYPE FOR THE SET OF NODES 
	INTEGER::NUMBEROFNEIB
! 	INTEGER::itor
	INTEGER,allocatable,dimension(:)::NEIBIDS,xne,xneib
! 	real,allocatable,dimension(:)::cord
END TYPE NODE_LIT



TYPE(NODE_NE),ALLOCATABLE,DIMENSION(:)::INODEN,INODER
TYPE(NODE_LIT),ALLOCATABLE,DIMENSION(:)::INODER2

TYPE::NODE_OUT
	INTEGER::GLOBAL
	INTEGER::NUMBERELEMENTS
	INTEGER::TOTAL
	INTEGER,ALLOCATABLE,DIMENSION(:)::NUMBEROTHER
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::WHICHOTHER
	REAL,ALLOCATABLE,DIMENSION(:,:)::WEIGHTOTHER
	REAL,ALLOCATABLE,DIMENSION(:)::WEIGHTS
	REAL::X
	REAL::Y
	REAL::Z
	INTEGER,ALLOCATABLE,DIMENSION(:)::ELEMENTSLOCAL
END TYPE NODE_OUT

TYPE(NODE_OUT),ALLOCATABLE,DIMENSION(:,:)::INODEO


TYPE::ELEM_SHAPE	!NAME OF TYPE FOR THE SET OF NODES 
	INTEGER::ISHAPE	!IDENTIFICATION NUMBER THAT CAN BE USED AS A POINTER INSIDE AN ARRAY
END TYPE ELEM_SHAPE 

INTEGER,ALLOCATABLE,DIMENSION(:)::IESHAPE	!1-D ARRAY FOR SHAPE OF ELEMENT

TYPE::EXCHANGE
	INTEGER::PROCID					!PROCESSOR ID
	INTEGER::TOT
	INTEGER,ALLOCATABLE,DIMENSION(:)::WHATTHEYNEED   !ELEMENT NUMBERS
	INTEGER,ALLOCATABLE,DIMENSION(:)::MUCHTHEYNEED  !NUMBER OF ELEMENTS THEY NEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::MUCHINEED	!NUMBER OF ELEMENTS I NEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::WHATINEED	!ELEMENT NUMBER GLOBAL
	INTEGER,ALLOCATABLE,DIMENSION(:)::SIDEINEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::SIDEINEEDN,QINEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::SIDETHEYNEED,QTHEYNEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::SIDETHEYNEEDN
	INTEGER,ALLOCATABLE,DIMENSION(:)::LOCALREF
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::nodex
END TYPE EXCHANGE


TYPE(EXCHANGE),ALLOCATABLE,DIMENSION(:)::IEXCHANGER
TYPE(EXCHANGE),ALLOCATABLE,DIMENSION(:)::IEXCHANGES
TYPE(EXCHANGE),ALLOCATABLE,DIMENSION(:)::IEXCHANGER1
TYPE(EXCHANGE),ALLOCATABLE,DIMENSION(:)::IEXCHANGES1

TYPE::SOLEXCHANGE
	INTEGER::PROCID
	REAL,ALLOCATABLE,DIMENSION(:,:)::CENTRES
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::NODES
	REAL,ALLOCATABLE,DIMENSION(:,:)::SOL
END TYPE SOLEXCHANGE

TYPE(SOLEXCHANGE),ALLOCATABLE,DIMENSION(:)::SOLCHANGER

TYPE(SOLEXCHANGE),ALLOCATABLE,DIMENSION(:)::SOLCHANGES

TYPE::RECEX
	INTEGER::PROCID					!PROCESSOR ID
	INTEGER::TOT
	INTEGER,ALLOCATABLE,DIMENSION(:)::WHATTHEYNEED   !ELEMENT NUMBERS
	INTEGER,ALLOCATABLE,DIMENSION(:)::MUCHTHEYNEED  !NUMBER OF ELEMENTS THEY NEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::MUCHINEED	!NUMBER OF ELEMENTS I NEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::WHATINEED	!ELEMENT NUMBER GLOBAL
	INTEGER,ALLOCATABLE,DIMENSION(:)::ISHAPE
	INTEGER,ALLOCATABLE,DIMENSION(:)::LOCALREF
	REAL,ALLOCATABLE,DIMENSION(:,:)::CENTERS
END TYPE RECEX

TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::IRECEXR		!RECEIVE ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::IRECEXR1		!RECEIVE ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::irecexrg		!RECEIVE ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::irecexsg		!RECEIVE ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::IRECEXS1		!RECEIVE ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::IRECEXS		!SEBD ELEMENTS DUE TO STENCIL

TYPE::ELEMENT_NUMBER	!NAME OF TYPE FOR THE SET OF ELEMENTS
        INTEGER::IHEX	!IDENTIFICATION NUMBER THAT CAN BE USED AS A POINTER INSIDE AN ARRAY
	INTEGER::IHEXGL,full
	INTEGER::INTERIOR,VDEC,MODE
	INTEGER::GGS,idegfree,inumneighbours,nofbc,iorder
	INTEGER::ISHAPE
	INTEGER::IFCA,dec !possible to remove
	INTEGER::ADMIS
	INTEGER::hybrid,nonodes,walls
	INTEGER,ALLOCATABLE,DIMENSION(:)::NODES,TYPEs_FACES,REORIENT
	integer,allocatable,dimension(:)::num_of_wall_gqp
	TYPE(FACE_D),ALLOCATABLE,DIMENSION(:)::Q_FACE
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::NODES_FACES
	INTEGER,ALLOCATABLE,DIMENSION(:)::INDEXI
	INTEGER,ALLOCATABLE,DIMENSION(:)::ibounds,IBOUNDW
	INTEGER,ALLOCATABLE,DIMENSION(:)::INEIGH !NEIGHBOURS	
	INTEGER,ALLOCATABLE,DIMENSION(:)::INEIGHG !NEIGHBOURS
	INTEGER,ALLOCATABLE,DIMENSION(:)::INEIGHB !NEIGHBOURS	
	INTEGER,ALLOCATABLE,DIMENSION(:)::INEIGHN !NEIGHBOURS	
	INTEGER,ALLOCATABLE,DIMENSION(:)::PERCOR	!PERIODIC CORRESPONDING ELEMENT
	INTEGER,ALLOCATABLE,DIMENSION(:)::PERCORB	!PERIODIC CORRESPONDING ELEMENT
	INTEGER,ALLOCATABLE,DIMENSION(:)::PERCORG	!PERIODIC CORRESPONDING ELEMENT
	INTEGER,ALLOCATABLE,DIMENSION(:)::PERCORN	!PERIODIC CORRESPONDING ELEMENT
 	REAL::TOTVOLUME		!VOLUME OF ELEMENT 
	REAL::DTL
 	REAL::MINEDGE,CONDITION,STENCIL_DIST
 	REAL::WallDist,XXC,YYC,ZZC
! 	REAL,allocatable,dimension(:)::ref
	REAL,ALLOCATABLE,DIMENSION(:)::FACEANGLEX	!FACEANGLES X,Y
	REAL,ALLOCATABLE,DIMENSION(:)::FACEANGLEY	!FACEANGLES X,Y
	REAL,ALLOCATABLE,DIMENSION(:)::DIH,vortex,SURF
	REAL,ALLOCATABLE,DIMENSION(:,:)::DIH2
END TYPE ELEMENT_NUMBER

TYPE::FACES
  INTEGER::ISHAPE
  INTEGER,ALLOCATABLE,DIMENSION(:)::NEIGHG,NEIGHL
  INTEGER,ALLOCATABLE,DIMENSION(:)::NODES
END TYPE FACES

TYPE(ELEMENT_NUMBER),ALLOCATABLE,DIMENSION(:,:)::IELEM
TYPE(FACES),ALLOCATABLE,DIMENSION(:,:)::IFACE

TYPE::ELEMENT_NUMBER2	!NAME OF TYPE FOR THE SET OF ELEMENTS
	INTEGER::nbf !4
	INTEGER::BLOCKN	!4 !CPU OR BLOCK NUMBER OF THIS ONE
	INTEGER::INBCP	!4
	INTEGER::IBCTRUE	!BOUNDARY CHECKED (DOUBLE CHECK) 4
	INTEGER,ALLOCATABLE,DIMENSION(:)::VERTB	!32
	INTEGER,ALLOCATABLE,DIMENSION(:)::IBFACES
	REAL,ALLOCATABLE,DIMENSION(:)::SURFAREAS	!32
	REAL,ALLOCATABLE,DIMENSION(:,:)::rFACEANGLEX !64	!FACEANGLES X,Y
	REAL,ALLOCATABLE,DIMENSION(:,:)::rFACEANGLEY
END TYPE ELEMENT_NUMBER2
	
TYPE(ELEMENT_NUMBER2),ALLOCATABLE,DIMENSION(:,:)::IELEM2  !1-D ARRAY FOR TYPE FOR ELEMENTS

TYPE::BOUND_NUMBER	!NAME OF TYPE FOR THE SET OF ELEMENTS
        INTEGER::ishape,icode,inum,which,face	!IDENTIFICATION NUMBER THAT CAN BE USED AS A POINTER INSIDE AN ARRAY
        INTEGER,allocatable,dimension(:)::IBl
	INTEGER,ALLOCATABLE,DIMENSION(:)::LOCALN,CPUN
	CHARACTER(LEN=12)::description
END TYPE BOUND_NUMBER

TYPE(BOUND_NUMBER),ALLOCATABLE,DIMENSION(:,:)::IBOUND	  !1-D ARRAY FOR BOUNDARY CONDITION TYPE

TYPE::CONNX	!NAME OF TYPE FOR THE SET OF ELEMENTS
	INTEGER::PROCID	!IDENTIFICATION NUMBER THAT CAN BE USED AS A POINTER INSIDE AN ARRAY
	INTEGER,ALLOCATABLE,DIMENSION(:)::HOWMANYI	!IDENTIFICATION NUMBER OF NODE1
	INTEGER,ALLOCATABLE,DIMENSION(:)::RETM
	INTEGER,ALLOCATABLE,DIMENSION(:)::RET
	INTEGER,ALLOCATABLE,DIMENSION(:)::HOWMANYTHEY
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::WHICHI
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::WHICHTHEY
	REAL,ALLOCATABLE,DIMENSION(:,:)::FACX
END TYPE CONNX

TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONR
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONS
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONRPA
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONRPM
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONSPO
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONRPF

!$OMP THREADPRIVATE(ILOCAL_RECON5)





END MODULE DECLARATION
