

PROGRAM TRANS2
IMPLICIT NONE
	INTEGER::I,J,K,L,N,I1,I2,I3,I4,I5,I6,I7,I8,IOS,IOX,IOY,IMAXE,IMAXB,IMAXN,ICG
	real::x,y,z
	CHARACTER(LEN=12)::VRTFILE1,CELFILE1,BNDFILE1,VRTFILE2,CELFILE2,BNDFILE2
	CHARACTER(LEN=4)::cg
		CELFILE1='STAR1.cel'
		VRTFILE1='STAR1.vrt'
		BNDFILE1='STAR1.bnd'
		OPEN(8,FILE=CELFILE1,FORM='FORMATTED',STATUS='OLD',ACTION='READ',IOSTAT=IOS)
		OPEN(9,FILE=VRTFILE1,FORM='FORMATTED',STATUS='OLD',ACTION='READ',IOSTAT=IOX)
		OPEN(10,FILE=BNDFILE1,FORM='FORMATTED',STATUS='OLD',ACTION='READ',IOSTAT=IOY)
		
	I=0
	J=0
	K=0

	
	DO 
		READ(8,*,IOSTAT=IOS)I
		IF (IOS.NE.0) THEN
			EXIT
		END IF
		
	END DO
		IMAXE=i
	DO 
		READ(9,*,IOSTAT=IOX)J
		IF (IOX.NE.0) THEN
			EXIT
		END IF
		
	END DO
		IMAXN=J
	DO 
		READ(10,*,IOSTAT=IOY)K
		IF (IOY.NE.0) THEN
			EXIT
		END IF
 		
	END DO
	 		IMAXB=K
		
		CLOSE(8);CLOSE(9);CLOSE(10)
		
		
		OPEN(8,FILE=CELFILE1,FORM='FORMATTED',STATUS='OLD',ACTION='READ',IOSTAT=IOS)
		OPEN(9,FILE=VRTFILE1,FORM='FORMATTED',STATUS='OLD',ACTION='READ',IOSTAT=IOX)
		OPEN(10,FILE=BNDFILE1,FORM='FORMATTED',STATUS='OLD',ACTION='READ',IOSTAT=IOY)
		
		CELFILE2='GRID.cel'
		VRTFILE2='GRID.vrt'
		BNDFILE2='GRID.bnd'
		OPEN(18,FILE=CELFILE2,FORM='UNFORMATTED',STATUS='NEW',ACTION='WRITE')
		OPEN(19,FILE=VRTFILE2,FORM='UNFORMATTED',STATUS='NEW',ACTION='WRITE')
		OPEN(110,FILE=BNDFILE2,FORM='UNFORMATTED',STATUS='NEW',ACTION='WRITE')
		
		
 		DO I=1,IMAXE
 		    READ(8,'(I14,1X,8I9)')N,I1,I2,I3,I4,I5,I6,I7,I8
 		    WRITE(18)N,I1,I2,I3,I4,I5,I6,I7,I8
 		END DO
 		    CLOSE(8);CLOSE(18)
		
 		DO I=1,IMAXN
 		    READ(9,'(SS,I14,1X,SP,3ES16.9)')N,X,Y,Z
		    WRITE(19)N,X,Y,Z
 		END DO
 		CLOSE(9);CLOSE(19)


		DO I=1,IMAXb
 		    READ(10,'(I14,1X,6I9,1X,A4)')N,i1,i2,i3,i4,i5,i6,cg
		    WRITE(120,*)N,i1,i2,i3,i4,i5,i6,cg
		    if ((cg.eq.'PRES').OR.(cg.eq.'TRAN'))ICG=6
		    if ((cg.eq.'SYMP').OR.(cg.eq.'SYMM'))ICG=3
		    if (cg.eq.'WALL')ICG=4
		    if (cg.eq.'OUTL')ICG=2
		    if (cg.eq.'INLE')ICG=1
                    if (cg.eq.'CYCL')ICG=5
		    WRITE(110)N,i1,i2,i3,i4,icg
 		END DO
 		CLOSE(10);CLOSE(110)
		
		    
		
		    
		
		
		
END PROGRAM TRANS2


