MODULE ADVANCE
USE LIBRARY
USE TRANSFORM
USE FLUXES
USE SOURCE
USE INITIALISATION
USE BOUNDARY
USE RECON
USE LOCAL
USE FLOW_OPERATIONS
USE COMMUNICATIONS
USE implicit_time
USE implicit_FLUXES
! USE FLUXES_V
USE IO
IMPLICIT NONE

 CONTAINS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!---------------------------------------------------------------------------------------------!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!SUBROUTINE CALLED TO CALCULATE CFL NUMBER DEPENDING ON THE SCHEME!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!EMPLOYED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SUBROUTINE CALCULATE_CFL(N)
!> @brief
!> subroutine for computing the global time step size in 3D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::I,K,L,KMAXE,J,INGTMAX,INGTMIN,WHGU,WHGL
REAL::SUVI,SUV3,maxU,MINU
REAL::CCFL,VELN,AGRT
KMAXE=XMPIELRANK(N)
       
        CCFL=(CFL/3.0d0)
        
        DT=tolbig
	IF (ITESTCASE.LT.3)THEN
	!$OMP DO REDUCTION (MIN:DT)
        DO I=1,KMAXE
		VELN=MAX(ABS(LAMx),ABS(LAMy),ABS(LAMz))
		DT=MIN(DT,CCFL*((IELEM(N,I)%MINEDGE)/(ABS(VELN))))
	END DO
	!$OMP END DO
	END IF
	
	IF (ITESTCASE.EQ.3)THEN
	!$OMP DO REDUCTION (MIN:DT)
        DO I=1,KMAXE
		LEFTV(1:NOF_vARIABLES)=U_C(I)%VAL(1,1:NOF_vARIABLES)
		
		CALL CONS2PRIM(N)
		AGRT=SQRT(LEFTV(5)*GAMMA/LEFTV(1))
		VELN=MAX(ABS(LEFTV(2)),ABS(LEFTV(3)),ABS(LEFTV(4)))+AGRT
		DT=MIN(DT,CCFL*((IELEM(N,I)%MINEDGE)/(ABS(VELN))))
	END DO
	!$OMP END DO
	END IF
	
	
	
	IF (ITESTCASE.EQ.4)THEN
	!$OMP DO REDUCTION (MIN:DT)
        DO I=1,KMAXE
		LEFTV(1:NOF_vARIABLES)=U_C(I)%VAL(1,1:NOF_vARIABLES)
		CALL CONS2PRIM(N)
		RIGHTV(1:NOF_vARIABLES)=LEFTV(1:NOF_vARIABLES)
		CALL SUTHERLAND(N,LEFTV,RIGHTV)
		AGRT=SQRT(LEFTV(5)*GAMMA/LEFTV(1))
		VELN=MAX(ABS(LEFTV(2)),ABS(LEFTV(3)),ABS(LEFTV(4)))+AGRT
		
		IF (TURBULENCE.EQ.1)THEN
		IF (TURBULENCEMODEL.EQ.1)THEN
		TURBMV(1)=U_CT(I)%VAL(1,1);  TURBMV(2)=U_CT(I)%VAL(1,1);
		eddyfl(2)=turbmv(1); eddyfr(2)=turbmv(2)
		Call EDDYVISCO(N,VISCL,LAML,TURBMV,ETVM,EDDYFL,EDDYFR)
		LAML(1)=LAML(1)+LAML(3)
		VISCL(1)=VISCL(1)+VISCL(3)
		END IF
		END IF
		
		
		
		
		
         DT=MIN(DT,CCFL*(1.0D0/((ABS(VELN)/((IELEM(N,I)%MINEDGE))) + (0.5D0*(LAML(1)+VISCL(1))/((IELEM(N,I)%MINEDGE))**2))))
                             
	END DO
	!$OMP END DO
	END IF
	
	
        RETURN
        
END SUBROUTINE CALCULATE_CFL

SUBROUTINE CALCULATE_CFLL(N)
!> @brief
!> subroutine for computing the time step size for each cell in 3D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::I,K,L,KMAXE,J,INGTMAX,INGTMIN,WHGU,WHGL
REAL::SUVI,SUV3,maxU,MINU
REAL::CCFL,VELN,AGRT
KMAXE=XMPIELRANK(N)
       
        CCFL=(CFL/3.0d0)
        
        
	IF (ITESTCASE.LT.3)THEN
	!$OMP DO SCHEDULE (STATIC)
        DO I=1,KMAXE
		VELN=MAX(ABS(LAMx),ABS(LAMy),ABS(LAMz))
		IELEM(N,I)%DTL=CCFL*((IELEM(N,I)%MINEDGE)/(ABS(VELN)))
	END DO
	!$OMP END DO
	END IF
	
	IF (ITESTCASE.EQ.3)THEN
	!$OMP DO
        DO I=1,KMAXE
		LEFTV(1:NOF_vARIABLES)=U_C(I)%VAL(1,1:NOF_vARIABLES)
		
		CALL CONS2PRIM(N)
		AGRT=SQRT(LEFTV(5)*GAMMA/LEFTV(1))
		VELN=MAX(ABS(LEFTV(2)),ABS(LEFTV(3)),ABS(LEFTV(4)))+AGRT
		IELEM(N,I)%DTL=CCFL*((IELEM(N,I)%MINEDGE)/(ABS(VELN)))
	END DO
	!$OMP END DO
	END IF
	
	
	
	IF (ITESTCASE.EQ.4)THEN
	!$OMP DO SCHEDULE (STATIC)
        DO I=1,KMAXE
		LEFTV(1:NOF_vARIABLES)=U_C(I)%VAL(1,1:NOF_vARIABLES)
		CALL CONS2PRIM(N)
		RIGHTV(1:NOF_vARIABLES)=LEFTV(1:NOF_vARIABLES)
		CALL SUTHERLAND(N,LEFTV,RIGHTV)
		AGRT=SQRT(LEFTV(5)*GAMMA/LEFTV(1))
		VELN=MAX(ABS(LEFTV(2)),ABS(LEFTV(3)),ABS(LEFTV(4)))+AGRT
		IF (TURBULENCE.EQ.1)THEN
		IF (TURBULENCEMODEL.EQ.1)THEN
		TURBMV(1)=U_CT(I)%VAL(1,1);  TURBMV(2)=U_CT(I)%VAL(1,1);
		eddyfl(2)=turbmv(1); eddyfr(2)=turbmv(2)
		Call EDDYVISCO(N,VISCL,LAML,TURBMV,ETVM,EDDYFL,EDDYFR)
		LAML(1)=LAML(1)+LAML(3)
		VISCL(1)=VISCL(1)+VISCL(3)
		END IF
		END IF
		
		
		
		
		IELEM(N,I)%DTL=CCFL*(1.0D0/((ABS(VELN)/((IELEM(N,I)%MINEDGE))) + (0.5D0*(LAML(1)+VISCL(1))/((IELEM(N,I)%MINEDGE))**2)))
		
	END DO
	!$OMP END DO
	END IF
	
	
        RETURN
        
END SUBROUTINE CALCULATE_CFLL



SUBROUTINE CALCULATE_CFL2D(N)
!> @brief
!> subroutine for computing the global time step size in 2D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::I,K,L,KMAXE,J,INGTMAX,INGTMIN,WHGU,WHGL
REAL::SUVI,SUV3,maxU,MINU,sum_DT1,sum_dt2
REAL::CCFL,VELN,AGRT
KMAXE=XMPIELRANK(N)
       
        CCFL=(CFL/2.0d0)
        
        DT=tolbig
        
        
        
        
	IF (ITESTCASE.LT.3)THEN
	!$OMP DO REDUCTION (MIN:DT)
        DO I=1,KMAXE
        
				if (initcond.eq.3)then
				  lamx=-ielem(n,i)%yyc+0.5d0
				  lamy=ielem(n,i)%xxc-0.5
				  end if
        
        
		VELN=MAX(ABS(LAMx),ABS(LAMy))
		DT=MIN(DT,CCFL*((IELEM(N,I)%MINEDGE)/(ABS(VELN))))
		
	END DO
	!$OMP END DO
	END IF
	
	IF (ITESTCASE.EQ.3)THEN
	!$OMP DO REDUCTION (MIN:DT)
        DO I=1,KMAXE
		LEFTV(1:NOF_vARIABLES)=U_C(I)%VAL(1,1:NOF_vARIABLES)
		sum_dt1=zero
		sum_dt2=zero
		do j=1,ielem(n,i)%ifca
		sum_dt1=sum_dt1+0.5d0*abs(IELEM(N,I)%FACEANGLEX(j))*IELEM(N,I)%SURF(j)
		sum_dt2=sum_dt2+0.5d0*abs(IELEM(N,I)%FACEANGLEy(j))*IELEM(N,I)%SURF(j)
		end do
		CALL CONS2PRIM2D(N)
		AGRT=SQRT(LEFTV(4)*GAMMA/LEFTV(1))
		veln=((abs(leftv(2))+agrt)*sum_dt1)+((abs(leftv(3))+agrt)*sum_dt2)
		
		
		DT=MIN(DT,CCFL*(ielem(n,i)%totvolume/veln))
	END DO
	!$OMP END DO
	END IF
	
	
	
	IF (ITESTCASE.EQ.4)THEN
	!$OMP DO REDUCTION (MIN:DT)
        DO I=1,KMAXE
		LEFTV(1:NOF_vARIABLES)=U_C(I)%VAL(1,1:NOF_vARIABLES)
		CALL CONS2PRIM2d2(N)
		RIGHTV(1:NOF_vARIABLES)=LEFTV(1:NOF_vARIABLES)
		CALL SUTHERLAND2D(N,LEFTV,RIGHTV)
		AGRT=SQRT(LEFTV(4)*GAMMA/LEFTV(1))
		VELN=MAX(ABS(LEFTV(2)),ABS(LEFTV(3)))+AGRT
		IF (TURBULENCE.EQ.1)THEN
		IF (TURBULENCEMODEL.EQ.1)THEN
		TURBMV(1)=U_CT(I)%VAL(1,1);  TURBMV(2)=U_CT(I)%VAL(1,1);
		eddyfl(2)=turbmv(1); eddyfr(2)=turbmv(2)
		Call EDDYVISCO2D(N,VISCL,LAML,TURBMV,ETVM,EDDYFL,EDDYFR)
		LAML(1)=LAML(1)+LAML(3)
		VISCL(1)=VISCL(1)+VISCL(3)
		END IF
		END IF
		
		DT=MIN(DT,CCFL*(1.0D0/((ABS(VELN)/((IELEM(N,I)%MINEDGE))) + (0.5D0*(LAML(1)+VISCL(1))/((IELEM(N,I)%MINEDGE))**2))))
	END DO
	!$OMP END DO
	END IF
	
	
        RETURN
        
END SUBROUTINE CALCULATE_CFL2D


SUBROUTINE CALCULATE_CFLL2D(N)
!> @brief
!> subroutine for computing the time step size for each cell in 2D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::I,K,L,KMAXE,J,INGTMAX,INGTMIN,WHGU,WHGL
REAL::SUVI,SUV3,maxU,MINU
REAL::CCFL,VELN,AGRT
KMAXE=XMPIELRANK(N)
       
        CCFL=(CFL/2.0d0)
        
        
	IF (ITESTCASE.LT.3)THEN
	!$OMP DO SCHEDULE (STATIC)
        DO I=1,KMAXE
		VELN=MAX(ABS(LAMx),ABS(LAMy))
		IELEM(N,I)%DTL=CCFL*((IELEM(N,I)%MINEDGE)/(ABS(VELN)))
	END DO
	!$OMP END DO
	END IF
	
	IF (ITESTCASE.EQ.3)THEN
	!$OMP DO SCHEDULE (STATIC)
        DO I=1,KMAXE
		LEFTV(1:NOF_vARIABLES)=U_C(I)%VAL(1,1:NOF_vARIABLES)
		
		CALL CONS2PRIM2D(N)
		AGRT=SQRT(LEFTV(4)*GAMMA/LEFTV(1))
		VELN=MAX(ABS(LEFTV(2)),ABS(LEFTV(3)))+AGRT
		IELEM(N,I)%DTL=CCFL*((IELEM(N,I)%MINEDGE)/(ABS(VELN)))
	END DO
	!$OMP END DO
	END IF
	
	
	
	IF (ITESTCASE.EQ.4)THEN
	!$OMP DO SCHEDULE (STATIC)
        DO I=1,KMAXE
		LEFTV(1:NOF_vARIABLES)=U_C(I)%VAL(1,1:NOF_vARIABLES)
		CALL CONS2PRIM2d2(N)
		RIGHTV(1:NOF_vARIABLES)=LEFTV(1:NOF_vARIABLES)
		CALL SUTHERLAND2D(N,LEFTV,RIGHTV)
		AGRT=SQRT(LEFTV(4)*GAMMA/LEFTV(1))
		VELN=MAX(ABS(LEFTV(2)),ABS(LEFTV(3)))+AGRT
		IF (TURBULENCE.EQ.1)THEN
		IF (TURBULENCEMODEL.EQ.1)THEN
		TURBMV(1)=U_CT(I)%VAL(1,1);  TURBMV(2)=U_CT(I)%VAL(1,1);
		eddyfl(2)=turbmv(1); eddyfr(2)=turbmv(2)
		Call EDDYVISCO2D(N,VISCL,LAML,TURBMV,ETVM,EDDYFL,EDDYFR)
		LAML(1)=LAML(1)+LAML(3)
		VISCL(1)=VISCL(1)+VISCL(3)
		END IF
		END IF
		
		IELEM(N,I)%DTL=CCFL*(1.0D0/((ABS(VELN)/((IELEM(N,I)%MINEDGE))) + (0.5D0*(LAML(1)+VISCL(1))/((IELEM(N,I)%MINEDGE))**2)))
	END DO
	!$OMP END DO
	END IF
	
	
        RETURN
        
END SUBROUTINE CALCULATE_CFLL2D


! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! ! !---------------------------------------------------------------------------------------------!
! ! !---------------------------------------------------------------------------------------------!
! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! ! !!!!!!!!!!!!!!!!!!SUBROUTINE CALLED TO ADVANCE SOLUTION BY ONE TIME STEP SIZE!!!!!!!!!!!!!!!!!!
! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SUBROUTINE RUNGE_KUTTA3(N)
!> @brief
!> SSP RUNGE KUTTA 3RD-ORDER SCHEME
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
KMAXE=XMPIELRANK(N)
TO4=3.0D0/4.0D0
OO4=1.0D0/4.0D0
TO3=2.0D0/3.0D0
OO3=1.0D0/3.0D0	

IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    
    END SELECT
END IF


!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(2,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(2,1:NOF_VARIABLES)-(DT*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)-(DT*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
END DO
!$OMP END DO
 end if
 
IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
END IF

!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(3,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(TO4*U_C(I)%VAL(2,1:NOF_VARIABLES))+(OO4*U_C(I)%VAL(3,1:NOF_VARIABLES))-(((OO4))*((DT)*&
((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(3,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(TO4*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(OO4*U_Ct(I)%VAL(3,1:turbulenceequations+passivescalar))-(((OO4))*((DT)*&
((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
END DO
!$OMP END DO
 end if



IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    call VORTEXCALC(N)
    END SELECT
END IF
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(1,1:NOF_VARIABLES)=((OO3)*U_C(I)%VAL(2,1:NOF_VARIABLES))+((TO3)*U_C(I)%VAL(1,1:NOF_VARIABLES))-(((TO3))*&
((DT)*((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=((OO3)*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+((TO3)*U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar))-(((TO3))*&
((DT)*((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
END DO
!$OMP END DO
 end if



IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF





                        
END SUBROUTINE RUNGE_KUTTA3

SUBROUTINE RUNGE_KUTTA1(N)
!> @brief
!> SSP FORWARD EULER SCHEME
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
reaL::t1,t2,t3
KMAXE=XMPIELRANK(N)




IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
   
    
    CALL EXCHANGE_HIGHER(N)
       CALL ARBITRARY_ORDER3(N)
   
    CALL EXHBOUNDHIGHER(N)
    
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    call VORTEXCALC(N)
    END SELECT
END IF



!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)-(DT*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
  
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)-(DT*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
END DO
!$OMP END DO
 end if




IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF





                        
END SUBROUTINE RUNGE_KUTTA1



SUBROUTINE RUNGE_KUTTA2(N)
!> @brief
!> SSP RUNGE KUTTA 2ND-ORDER SCHEME
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
KMAXE=XMPIELRANK(N)
TO4=3.0D0/4.0D0
OO4=1.0D0/4.0D0
TO3=2.0D0/3.0D0
OO3=1.0D0/3.0D0	

IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
END IF


!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(2,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)-(DT*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
  
END DO
!$OMP END DO
if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)-(DT*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
END DO
!$OMP END DO
 end if



IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    call VORTEXCALC(N)
    END SELECT
END IF

!$OMP DO
DO I=1,KMAXE
 OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(oo2*U_C(I)%VAL(2,1:NOF_VARIABLES))+(oo2*U_C(I)%VAL(1,1:NOF_VARIABLES))-(dt*oo2*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(oo2*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(oo2*U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar))-(dt*oo2*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if







IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF





                        
END SUBROUTINE RUNGE_KUTTA2


SUBROUTINE RUNGE_KUTTA5(N)
!> @brief
!> SSP RUNGE KUTTA 2ND-ORDER SCHEME FOR LOCAL TIME STEPPING
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
KMAXE=XMPIELRANK(N)


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
END IF


!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(2,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)-(ielem(n,i)%dtl*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
  
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)-(ielem(n,i)%dtl*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    call VORTEXCALC(N)
    END SELECT
END IF

!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(oo2*U_C(I)%VAL(2,1:NOF_VARIABLES))+(oo2*U_C(I)%VAL(1,1:NOF_VARIABLES))-(ielem(n,i)%dtl*oo2*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(oo2*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(oo2*U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar))-(ielem(n,i)%dtl*oo2*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if


IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF





                        
END SUBROUTINE RUNGE_KUTTA5

SUBROUTINE RUNGE_KUTTA5_2D(N)
!> @brief
!> SSP RUNGE KUTTA 2ND-ORDER SCHEME FOR LOCAL TIME STEPPING IN 2D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
KMAXE=XMPIELRANK(N)


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF


!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(2,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)-(ielem(n,i)%dtl*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
  
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)-(ielem(n,i)%dtl*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if



IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    call VORTEXCALC2D(N)
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    call VORTEXCALC2D(N)
    END SELECT
END IF

!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(oo2*U_C(I)%VAL(2,1:NOF_VARIABLES))+(oo2*U_C(I)%VAL(1,1:NOF_VARIABLES))-(ielem(n,i)%dtl*oo2*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(oo2*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(oo2*U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar))-(ielem(n,i)%dtl*oo2*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if



IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF





                        
END SUBROUTINE RUNGE_KUTTA5_2D


SUBROUTINE RUNGE_KUTTA2_2D(N)
!> @brief
!> SSP RUNGE KUTTA 2ND-ORDER SCHEME IN 2D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
KMAXE=XMPIELRANK(N)


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF


!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(2,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(2,1:NOF_VARIABLES)-(dt*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
  
END DO
!$OMP END DO


if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)-(dt*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    call VORTEXCALC2D(N)
    END SELECT
END IF

!$OMP DO
DO I=1,KMAXE
 OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(oo2*U_C(I)%VAL(2,1:NOF_VARIABLES))+(oo2*U_C(I)%VAL(1,1:NOF_VARIABLES))-(dt*oo2*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))-(dt*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if



IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF





                        
END SUBROUTINE RUNGE_KUTTA2_2D



SUBROUTINE RUNGE_KUTTA1_2D(N)
!> @brief
!> SSP FORWARD EULER SCHEME IN 2D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
KMAXE=XMPIELRANK(N)


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2D(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    call VORTEXCALC2D(N)
    END SELECT
END IF



!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)-(dt*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
  
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)-(dt*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if



IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF





                        
END SUBROUTINE RUNGE_KUTTA1_2D


SUBROUTINE RUNGE_KUTTA3_2D(N)
!> @brief
!> SSP RUNGE KUTTA 3RD-ORDER SCHEME IN 2D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
KMAXE=XMPIELRANK(N)
TO4=3.0D0/4.0D0
OO4=1.0D0/4.0D0
TO3=2.0D0/3.0D0
OO3=1.0D0/3.0D0	

IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF


!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(2,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(2,1:NOF_VARIABLES)-(DT*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
  
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)-(DT*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF

!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(3,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(TO4*U_C(I)%VAL(2,1:NOF_VARIABLES))+(OO4*U_C(I)%VAL(3,1:NOF_VARIABLES))-(((OO4))*((DT)*&
((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(3,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(TO4*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(OO4*U_Ct(I)%VAL(3,1:turbulenceequations+passivescalar))-(((OO4))*((DT)*&
((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
  END DO
!$OMP END DO
 end if



IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    call VORTEXCALC2D(N)
    END SELECT
END IF
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(1,1:NOF_VARIABLES)=((OO3)*U_C(I)%VAL(2,1:NOF_VARIABLES))+((TO3)*U_C(I)%VAL(1,1:NOF_VARIABLES))-(((TO3))*&
((DT)*((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO


if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=((OO3)*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+((TO3)*U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar))-(((TO3))*&
((DT)*((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
  END DO
!$OMP END DO
 end if




IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF


END SUBROUTINE RUNGE_KUTTA3_2D



SUBROUTINE RUNGE_KUTTA4(N)
!> @brief
!> SSP RUNGE KUTTA 4TH-ORDER SCHEME
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
real::prace_t1,prace_t2,prace_t3,prace_t4,prace_t5,prace_t6,prace_t7,prace_t8,prace_t9,pr_t1,pr_t2,pr_t3,pr_t4,PR_T5,PR_T6,PR_T7,PR_T8
REAL::DUMPRACEIN,DUMPRACEOUT,flops_count
KMAXE=XMPIELRANK(N)
TO4=3.0D0/4.0D0
OO4=1.0D0/4.0D0
TO3=2.0D0/3.0D0
OO3=1.0D0/3.0D0	

IF (FASTEST.EQ.1)THEN

    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    if (statistics.eq.1)then
    !$OMP BARRIER 
    !$OMP MASTER
    pr_T1=MPI_Wtime()
     !$OMP END MASTER
     !$OMP BARRIER
    end if
    
     
    CALL EXCHANGE_HIGHER(N)
    if (statistics.eq.1)then
    !$OMP BARRIER 
    !$OMP MASTER
    pr_t2=MPI_Wtime()
    prace_t1=pr_t2-pr_t1
    !$OMP END MASTER
     !$OMP BARRIER
    end if
    
    CALL ARBITRARY_ORDER3(N)
    if (statistics.eq.1)then
    !$OMP BARRIER 
    !$OMP MASTER
    pr_t3=MPI_Wtime()
    prace_t2=pr_t3-pr_t2
    !$OMP END MASTER
     !$OMP BARRIER
    end if
    
    
    
    CALL EXHBOUNDHIGHER(N)
    if (statistics.eq.1)then
    !$OMP BARRIER 
    !$OMP MASTER
    pr_t4=MPI_Wtime()
    prace_t3=pr_t4-pr_t3
    !$OMP END MASTER
     !$OMP BARRIER
    end if
    
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
    
    
    if (statistics.eq.1)then
    !$OMP BARRIER 
    !$OMP MASTER
    pr_t5=MPI_Wtime()
    prace_t4=pr_t5-pr_t4
    !$OMP END MASTER
     !$OMP BARRIER
    end if
    
    
    
END IF


    



!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(2,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(2,1:NOF_VARIABLES)-(DT*0.391752226571890*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
  
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)-(DT*0.391752226571890*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if
 
 
    if (statistics.eq.1)then
    !$OMP BARRIER 
    !$OMP MASTER
    pr_t6=MPI_Wtime()
    prace_t5=pr_t6-pr_t5
    
    !RECONSTRUCTION TIME=prace_t2
    !COMMUNICATION TIME OF EXBOUNDHIGHER=prace_t3
    !COMMUNICATION TIME OF HALO CELLS=prace_t1
    !FLUXES=prace_t4
    !UPDATE OF SOLUTION=prace_t5
    !TOTAL COMMUNICATION TIME=PRACE_T1+PRACE_T3=PRACE_T6
    !TOTAL COMPUTATIONALS TIME=PRACE_T2+PRACE_T4+PRACE_T5=PRACE_T7
    !TOTAL TIME=TOTAL COMMUNICATION TIME+TOTAL COMPUTATIONALS TIME=PRACE_T8
   PRACE_T6=PRACE_T1+PRACE_T3
   PRACE_T7=PRACE_T2+PRACE_T4+PRACE_T5
   PRACE_T8=PRACE_T7+PRACE_T6
   
   DUMPRACEIN=PRACE_t1
 CALL MPI_ALLREDUCE(DUMPRACEIN,DUMPRACEOUT,1,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERROR)
   PRACE_t1=DUMPRACEOUT
   DUMPRACEIN=PRACE_t2
 CALL MPI_ALLREDUCE(DUMPRACEIN,DUMPRACEOUT,1,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERROR)
   PRACE_t2=DUMPRACEOUT
   DUMPRACEIN=PRACE_t3
 CALL MPI_ALLREDUCE(DUMPRACEIN,DUMPRACEOUT,1,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERROR)
   PRACE_t3=DUMPRACEOUT
   DUMPRACEIN=PRACE_t4
 CALL MPI_ALLREDUCE(DUMPRACEIN,DUMPRACEOUT,1,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERROR)
   PRACE_t4=DUMPRACEOUT
   DUMPRACEIN=PRACE_t5
 CALL MPI_ALLREDUCE(DUMPRACEIN,DUMPRACEOUT,1,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERROR)
   PRACE_t5=DUMPRACEOUT
!    DUMPRACEIN=PRACE_t6
!  CALL MPI_ALLREDUCE(DUMPRACEIN,DUMPRACEOUT,1,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERROR)
!    PRACE_t6=DUMPRACEOUT
!    DUMPRACEIN=PRACE_t7
!  CALL MPI_ALLREDUCE(DUMPRACEIN,DUMPRACEOUT,1,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERROR)
!    PRACE_t7=DUMPRACEOUT
!    DUMPRACEIN=PRACE_t8
!  CALL MPI_ALLREDUCE(DUMPRACEIN,DUMPRACEOUT,1,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERROR)
!    PRACE_t8=DUMPRACEOUT
    PRACE_T6=PRACE_T1+PRACE_T3
   PRACE_T7=PRACE_T2+PRACE_T4+PRACE_T5
   PRACE_T8=PRACE_T7+PRACE_T6

   FLOPS_COUNT=(((2*idegfree*nof_Variables*(imaxdegfree+1)*5)+(2*nof_Variables*nof_variables*idegfree*4)+(2*idegfree*nof_Variables*nof_variables*5)+(2*idegfree*nof_Variables*idegfree*5)+&
                (QP_QUAD*2*6*3*3*3)+(QP_QUAD*3*2*5*6*5*5)+(5*5*5*2*QP_QUAD*6)+(QP_QUAD*nof_Variables*6*2)+(QP_QUAD*2*6)+(idegfree*QP_QUAD*6*iorder)+(20+300*IORDER*QP_QUAD*6+200+12000*QP_QUAD*6*2))/prace_t8)*1e-9*imaxe


   
    IF (N.EQ.0)THEN
    OPEN(133,FILE='STATISTICS.txt',FORM='FORMATTED',STATUS='old',ACTION='WRITE',POSITION='APPEND')
    WRITE(133,'(I14,1X,E14.7,1X,E14.7,1X,E14.7,1X,E14.7,1X,E14.7,1X,E14.7,1X,E14.7,1X,E14.7,1X,E14.7)')it,PRACE_T8,PRACE_T6,PRACE_T1,PRACE_T3,PRACE_T7,prace_t2,prace_t4,prace_t5,flops_count
    CLOSE(133)
    END IF
    
    
    !$OMP END MASTER
     !$OMP BARRIER
    
    end if


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
END IF

!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(3,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(0.444370493651235*U_C(I)%VAL(2,1:NOF_VARIABLES))+(0.555629506348765*U_C(I)%VAL(3,1:NOF_VARIABLES))-(((0.368410593050371))*((DT)*&
((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
    U_Ct(I)%VAL(3,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(0.444370493651235*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(0.555629506348765*U_Ct(I)%VAL(3,1:turbulenceequations+passivescalar))-(((0.368410593050371))*((DT)*&
((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
END DO
!$OMP END DO
 end if




IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
END IF
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(4,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(0.620101851488403*U_C(I)%VAL(2,1:NOF_VARIABLES))+(0.379898148511597*U_C(I)%VAL(4,1:NOF_VARIABLES))-(((0.251891774271694))*((DT)*&
((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO


if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(4,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(0.620101851488403*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(0.379898148511597*U_Ct(I)%VAL(4,1:turbulenceequations+passivescalar))-(((0.251891774271694))*((DT)*&
((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
END DO
!$OMP END DO
 end if


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
END IF
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(5,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(6,1:NOF_VARIABLES)=-((DT)*((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME)))
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(0.178079954393132*U_C(I)%VAL(2,1:NOF_VARIABLES))+(0.821920045606868*U_C(I)%VAL(5,1:NOF_VARIABLES))-(((0.544974750228521))*((DT)*&
((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
    U_Ct(I)%VAL(5,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(6,1:turbulenceequations+passivescalar)=-((DT)*((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME)))
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(0.178079954393132*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(0.821920045606868*U_Ct(I)%VAL(5,1:turbulenceequations+passivescalar))-(((0.544974750228521))*((DT)*&
((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
END DO
!$OMP END DO
 end if



IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_DIFFUSIVE(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    call VORTEXCALC(N)
    END SELECT
END IF
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(0.00683325884039*U_C(I)%VAL(2,1:NOF_VARIABLES))+(0.517231671970585*U_C(I)%VAL(4,1:NOF_VARIABLES))+&
				(0.12759831133288*U_C(I)%VAL(5,1:NOF_VARIABLES))+(0.34833675773694*U_C(I)%VAL(1,1:NOF_VARIABLES))+&
				(0.08460416338212*U_C(I)%VAL(6,1:NOF_VARIABLES))-(0.22600748319395*(DT)*((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME)))
END DO
!$OMP END DO


if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
   U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(0.00683325884039*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(0.517231671970585*U_Ct(I)%VAL(4,1:turbulenceequations+passivescalar))+&
				(0.12759831133288*U_Ct(I)%VAL(5,1:turbulenceequations+passivescalar))+(0.34833675773694*U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar))+&
				(0.08460416338212*U_Ct(I)%VAL(6,1:turbulenceequations+passivescalar))-(0.22600748319395*(DT)*((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME)))
END DO
!$OMP END DO
 end if


IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF


END SUBROUTINE RUNGE_KUTTA4



SUBROUTINE RUNGE_KUTTA4_2D(N)
!> @brief
!> SSP RUNGE KUTTA 4TH-ORDER SCHEME IN 2D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::IAVR,nvar,I,KMAXE
REAL::AVRGS,OOVOLUME,TO4,OO4,TO3,OO3
KMAXE=XMPIELRANK(N)
TO4=3.0D0/4.0D0
OO4=1.0D0/4.0D0
TO3=2.0D0/3.0D0
OO3=1.0D0/3.0D0	

IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
     if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF

!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(2,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=U_C(I)%VAL(2,1:NOF_VARIABLES)-(DT*0.391752226571890*(RHS(I)%VAL(1:NOF_VARIABLES)*OOVOLUME))
  
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar)-(DT*0.391752226571890*(RHSt(I)%VAL(1:turbulenceequations+passivescalar)*OOVOLUME))
  END DO
!$OMP END DO
 end if


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF

!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(3,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(0.444370493651235*U_C(I)%VAL(2,1:NOF_VARIABLES))+(0.555629506348765*U_C(I)%VAL(3,1:NOF_VARIABLES))-(((0.368410593050371))*((DT)*&
((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
    U_Ct(I)%VAL(3,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(0.444370493651235*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(0.555629506348765*U_Ct(I)%VAL(3,1:turbulenceequations+passivescalar))-(((0.368410593050371))*((DT)*&
((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
END DO
!$OMP END DO
 end if


IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(4,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(0.620101851488403*U_C(I)%VAL(2,1:NOF_VARIABLES))+(0.379898148511597*U_C(I)%VAL(4,1:NOF_VARIABLES))-(((0.251891774271694))*((DT)*&
((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_Ct(I)%VAL(4,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(0.620101851488403*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(0.379898148511597*U_Ct(I)%VAL(4,1:turbulenceequations+passivescalar))-(((0.251891774271694))*((DT)*&
((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
END DO
!$OMP END DO
 end if
 
IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(5,1:NOF_VARIABLES)=U_C(I)%VAL(1,1:NOF_VARIABLES)
  U_C(I)%VAL(6,1:NOF_VARIABLES)=-((DT)*((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME)))
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(0.178079954393132*U_C(I)%VAL(2,1:NOF_VARIABLES))+(0.821920045606868*U_C(I)%VAL(5,1:NOF_VARIABLES))-(((0.544974750228521))*((DT)*&
((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME))))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
    U_Ct(I)%VAL(5,1:turbulenceequations+passivescalar)=U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)
  U_Ct(I)%VAL(6,1:turbulenceequations+passivescalar)=-((DT)*((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME)))
  U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(0.178079954393132*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(0.821920045606868*U_Ct(I)%VAL(5,1:turbulenceequations+passivescalar))-(((0.544974750228521))*((DT)*&
((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME))))
END DO
!$OMP END DO
 end if
 
IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2D(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    IF (ITESTCASE.EQ.4)THEN
    call VORTEXCALC2D(N)
    END IF
    END SELECT
END IF
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
  U_C(I)%VAL(1,1:NOF_VARIABLES)=(0.00683325884039*U_C(I)%VAL(2,1:NOF_VARIABLES))+(0.517231671970585*U_C(I)%VAL(4,1:NOF_VARIABLES))+&
				(0.12759831133288*U_C(I)%VAL(5,1:NOF_VARIABLES))+(0.34833675773694*U_C(I)%VAL(1,1:NOF_VARIABLES))+&
				(0.08460416338212*U_C(I)%VAL(6,1:NOF_VARIABLES))-(0.22600748319395*(DT)*((RHS(I)%VAL(1:NOF_VARIABLES))*(OOVOLUME)))
END DO
!$OMP END DO

if ((turbulence.gt.0).or.(passivescalar.gt.0))then
!$OMP DO
DO I=1,KMAXE
  OOVOLUME=1.0D0/IELEM(N,I)%TOTVOLUME
   U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar)=(0.00683325884039*U_Ct(I)%VAL(2,1:turbulenceequations+passivescalar))+(0.517231671970585*U_Ct(I)%VAL(4,1:turbulenceequations+passivescalar))+&
				(0.12759831133288*U_Ct(I)%VAL(5,1:turbulenceequations+passivescalar))+(0.34833675773694*U_Ct(I)%VAL(1,1:turbulenceequations+passivescalar))+&
				(0.08460416338212*U_Ct(I)%VAL(6,1:turbulenceequations+passivescalar))-(0.22600748319395*(DT)*((RHSt(I)%VAL(1:turbulenceequations+passivescalar))*(OOVOLUME)))
END DO
!$OMP END DO
 end if

IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF



END SUBROUTINE RUNGE_KUTTA4_2D




SUBROUTINE IMPLICIT_TIMEs(N)
!> @brief
!> IMPLICIT APPROXIMATELY FACTORED TIME STEPPING SCHEME
IMPLICIT NONE
INTEGER::I,K,KMAXE,nvar,kill_nan
INTEGER,INTENT(IN)::N
reaL::verysmall
verysmall = tolsmall


KMAXE=XMPIELRANK(N)
IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_diffusive(N)
    call VORTEXCALC(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_diffusive(N)
    call VORTEXCALC(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
END IF


  
if (lowmemory.eq.0)then
   
 call RELAXATION(N)
   
 else
 
 call RELAXATION_lm(N)
 
 end if
   
  

 kill_nan=0
 
!$OMP DO
DO I=1,KMAXE
    If ((impdu(i,1).ne.impdu(i,1)).or.(impdu(i,2).ne.impdu(i,2)).or.(impdu(i,3).ne.impdu(i,3)).or.(impdu(i,4).ne.impdu(i,4)).or.(impdu(i,5).ne.impdu(i,5)))then
        write(600+n,*)"nan present",ielem(n,i)%ihexgl,ielem(n,i)%ishape,ielem(n,i)%xxc, ielem(n,i)%yyc,ielem(n,i)%zzc
        write(600+n,*)ielem(n,i)%dih(:)
        kill_nan=1
    end if
  U_C(I)%VAL(1,1:5)=U_C(I)%VAL(1,1:5)+IMPDU(I,1:5)
END DO
!$OMP END DO
    if (kill_nan.eq.1)then
        stop
    end if

IF ((PASSIVESCALAR.GT.0).OR.(TURBULENCE.GT.0))THEN
!$OMP DO
  DO I=1,KMAXE
  do k=1,turbulenceequations+passivescalar
  if (U_CT(I)%VAL(1,k)+IMPDU(I,5+k).ge.zero)then
  U_CT(I)%VAL(1,k)=U_CT(I)%VAL(1,k)+IMPDU(i,5+k)
  end if
  end do
END DO
!$OMP END DO
END IF









  
END SUBROUTINE IMPLICIT_TIMEs


SUBROUTINE IMPLICIT_TIMEs_2d(N) 
!> @brief
!> IMPLICIT APPROXIMATELY FACTORED TIME STEPPING SCHEME 2D
IMPLICIT NONE
INTEGER::I,K,KMAXE,nvar,kill_nan
INTEGER,INTENT(IN)::N
reaL::verysmall
verysmall = tolsmall


KMAXE=XMPIELRANK(N)
IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2d(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
   ! call VORTEXCALC2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2d(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    !call VORTEXCALC2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF



  
 if (lowmemory.eq.0)then
   
 call RELAXATION2d(N)
   
 else
 
 call RELAXATION_lm2d(N)
 
 end if
  

 kill_nan=0
!$OMP DO
DO I=1,KMAXE

    If ((impdu(i,1).ne.impdu(i,1)).or.(impdu(i,2).ne.impdu(i,2)).or.(impdu(i,3).ne.impdu(i,3)).or.(impdu(i,4).ne.impdu(i,4)))then
        write(600+n,*)"nan present",ielem(n,i)%ihexgl,ielem(n,i)%ishape,ielem(n,i)%xxc, ielem(n,i)%yyc
        write(600+n,*)ielem(n,i)%dih(:)
        kill_nan=1
    end if

    
    
    

  U_C(I)%VAL(1,1:4)=U_C(I)%VAL(1,1:4)+IMPDU(I,1:4)
END DO
!$OMP END DO

    if (kill_nan.eq.1)then
        stop
    end if



IF ((PASSIVESCALAR.GT.0).OR.(TURBULENCE.GT.0))THEN
!$OMP DO
  DO I=1,KMAXE
  do k=1,turbulenceequations+passivescalar
  if (ispal.eq.1)then
  if (U_CT(I)%VAL(1,k)+IMPDU(I,4+k).ge.zero)then
  U_CT(I)%VAL(1,k)=U_CT(I)%VAL(1,k)+IMPDU(i,4+k)
   end if
   else
   U_CT(I)%VAL(1,k)=U_CT(I)%VAL(1,k)+IMPDU(i,4+k)
   
   end if
  end do
END DO
!$OMP END DO

!   if (kill_nan.eq.2)then
!         stop
!     end if



END IF









  
END SUBROUTINE IMPLICIT_TIMEs_2d


SUBROUTINE DUAL_TIME(N)
!> @brief
!> DUAL TIME STEPPING
IMPLICIT NONE
INTEGER::I,K,KMAXE,nvar,jj
INTEGER,INTENT(IN)::N
reaL::verysmall
real::firsti,resmaxi,rsumfacei,suml2ri,dummy3i,inner_tol
verysmall = tolsmall

inner_tol=reslimit

KMAXE=XMPIELRANK(N)

 !$OMP MASTER
 dt=dt*1.5d0
 !$OMP END MASTER
 
!$OMP BARRIER 
!$OMP DO
DO I=1,KMAXE
  U_C(I)%VAL(2,1:nof_variables)=U_C(I)%VAL(1,1:nof_variables)
  if (u_c(i)%val(1,1).ne.u_c(i)%val(1,1))then
  stop
  end if
  U_C(I)%VAL(3,1:nof_variables)=U_C(I)%VAL(2,1:nof_variables)-IMPDU(I,1:nof_variables)
END DO
!$OMP END DO



IF ((PASSIVESCALAR.GT.0).OR.(TURBULENCE.GT.0))THEN
  !$OMP DO SCHEDULE (STATIC)
  DO I=1,KMAXE
  do k=1,turbulenceequations+passivescalar
  
  U_CT(I)%VAL(2,k)=U_CT(I)%VAL(1,k)
  
  end do
  END DO
  !$OMP END DO
END IF








IF ((PASSIVESCALAR.GT.0).OR.(TURBULENCE.GT.0))THEN
 !$OMP DO SCHEDULE (STATIC)
  DO I=1,KMAXE
  do k=1,turbulenceequations+passivescalar
  if (U_CT(I)%VAL(2,k)-IMPDU(I,nof_variables+k).ge.zero)then
  U_CT(I)%VAL(3,k)=U_CT(I)%VAL(2,k)+IMPDU(i,nof_variables+k)
  end if
  end do
  END DO
   !$OMP END DO
END IF


firsti=0.0d0
DO JJ=1,upperlimit
      rsumfacei=zero;allresdt=zero;dummy3i=zero; 
if (jj.le.2)then
  iscoun=1
else
  iscoun=jj
end if
      
IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_diffusive(N)
    call VORTEXCALC(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER3(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE(N)
    CALL CALCULATE_FLUXESHI_diffusive(N)
    call VORTEXCALC(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION(N)
    end if
    END SELECT
END IF

if (lowmemory.eq.0)then
   
 call RELAXATION(N)
   
 else
 
 call RELAXATION_lm(N)
 
 end if

!$OMP BARRIER 
!$OMP DO SCHEDULE(GUIDED) REDUCTION(+:allresdt)
DO I=1,KMAXE
      rsumfacei=sqrt(((IMPDU(I,1))**2)+((IMPDU(I,2))**2)+((IMPDU(I,3))**2)+((IMPDU(I,4))**2)+((IMPDU(I,5))**2))
      allresdt=allresdt+(rsumfacei*ielem(n,i)%totvolume)
end do
!$OMP END DO

!$OMP BARRIER 
!$OMP MASTER
DUMMY3I=zero







CALL MPI_ALLREDUCE(allresdt,DUMMY3i,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERROR)
allresdt=dummy3i/TOTALVOLUME

if (allresdt.gt.firsti)then
firsti=allresdt
end if

allresdt=allresdt/firsti
!$OMP END MASTER
!$OMP BARRIER 



  if ((allresdt.le.inner_tol).or.(jj.eq.upperlimit))then
 !$OMP DO SCHEDULE (STATIC)
  DO I=1,KMAXE
 U_C(I)%VAL(1,1:nof_Variables)=U_C(I)%VAL(1,1:nof_Variables)+IMPDU(I,1:nof_Variables)
    if ((turbulence.gt.0).or.(passivescalar.gt.0))then
    do k=1,turbulenceequations+passivescalar
	if (U_CT(I)%VAL(1,k)+IMPDU(I,nof_Variables+k).ge.zero)then
  U_CT(I)%VAL(1,k)=U_CT(I)%VAL(1,k)+IMPDU(i,nof_Variables+k)
	end if
    end do
    end if
  end DO
!$OMP END DO
  exit

else
 !$OMP DO SCHEDULE (STATIC)
 DO I=1,KMAXE
 U_C(I)%VAL(1,1:nof_Variables)=U_C(I)%VAL(1,1:nof_Variables)+IMPDU(I,1:nof_Variables)
    if ((turbulence.gt.0).or.(passivescalar.gt.0))then
    do k=1,turbulenceequations+passivescalar
	if (U_CT(I)%VAL(1,k)+IMPDU(I,nof_Variables+k).ge.zero)then
  U_CT(I)%VAL(1,k)=U_CT(I)%VAL(1,k)+IMPDU(i,nof_Variables+k)
	end if
    end do
    end if
  end DO
!$OMP END DO

end if


END DO

 !$OMP BARRIER 
 !$OMP MASTER
 dt=dt/1.5d0
 !$OMP END MASTER
 !$OMP BARRIER 

IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF










  
END SUBROUTINE dual_time



SUBROUTINE DUAL_TIME_2d(N)
!> @brief
!> DUAL TIME STEPPING 2D
IMPLICIT NONE
INTEGER::I,K,KMAXE,nvar,jj
INTEGER,INTENT(IN)::N
reaL::verysmall
real::firsti,resmaxi,rsumfacei,suml2ri,dummy3i,inner_tol
verysmall = tolsmall

inner_tol=reslimit

KMAXE=XMPIELRANK(N)
dt=dt*1.5d0

!$OMP DO
DO I=1,KMAXE
  U_C(I)%VAL(2,1:nof_variables)=U_C(I)%VAL(1,1:nof_variables)
  U_C(I)%VAL(3,1:nof_variables)=U_C(I)%VAL(2,1:nof_variables)-IMPDU(I,1:nof_variables)
END DO
!$OMP END DO



IF ((PASSIVESCALAR.GT.0).OR.(TURBULENCE.GT.0))THEN
  !$OMP DO SCHEDULE (STATIC)
  DO I=1,KMAXE
  do k=1,turbulenceequations+passivescalar
  
  U_CT(I)%VAL(2,k)=U_CT(I)%VAL(1,k)
  
  end do
  END DO
  !$OMP END DO
END IF








IF ((PASSIVESCALAR.GT.0).OR.(TURBULENCE.GT.0))THEN
 !$OMP DO SCHEDULE (STATIC)
  DO I=1,KMAXE
  do k=1,turbulenceequations+passivescalar
  if (U_CT(I)%VAL(2,k)-IMPDU(I,nof_variables+k).ge.zero)then
  U_CT(I)%VAL(3,k)=U_CT(I)%VAL(2,k)+IMPDU(i,nof_variables+k)
  end if
  end do
  END DO
   !$OMP END DO
END IF


firsti=0.0d0
DO JJ=1,upperlimit
      rsumfacei=zero;allresdt=zero;dummy3i=zero; 
if (jj.le.2)then
  iscoun=1
else
  iscoun=jj
end if
      
IF (FASTEST.EQ.1)THEN
    CALL EXCHANGE_LOWER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2d(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    call VORTEXCALC2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
    
ELSE
    CALL EXCHANGE_HIGHER(N)
    CALL ARBITRARY_ORDER2(N)
    CALL EXHBOUNDHIGHER(N)
    SELECT CASE(ITESTCASE)
    CASE(1,2)
    CALL CALCULATE_FLUXESHI2d(N)
    CASE(3)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CASE(4)
    CALL CALCULATE_FLUXESHI_CONVECTIVE2d(N)
    CALL CALCULATE_FLUXESHI_diffusive2d(N)
    call VORTEXCALC2D(N)
    if (turbulence.eq.1)then
    call SOURCES_COMPUTATION2d(N)
    end if
    END SELECT
END IF

if (lowmemory.eq.0)then
   
 call RELAXATION2d(N)
   
 else
 
 call RELAXATION_lm2d(N)
 
 end if

!$OMP BARRIER 
!$OMP DO SCHEDULE(GUIDED) REDUCTION(+:allresdt)
DO I=1,KMAXE
      rsumfacei=sqrt(((IMPDU(I,1))**2)+((IMPDU(I,2))**2)+((IMPDU(I,3))**2)+((IMPDU(I,4))**2))
      allresdt=allresdt+(rsumfacei*ielem(n,i)%totvolume)
end do
!$OMP END DO

!$OMP BARRIER 
!$OMP MASTER
DUMMY3I=zero

CALL MPI_ALLREDUCE(SUML2ri,DUMMY3i,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERROR)
allresdt=dummy3i/TOTALVOLUME



if (allresdt.gt.firsti)then
firsti=allresdt
end if

allresdt=allresdt/firsti
!$OMP END MASTER
!$OMP BARRIER 



  if ((allresdt.le.inner_tol).or.(jj.eq.upperlimit))then
 !$OMP DO SCHEDULE (STATIC)
  DO I=1,KMAXE
 U_C(I)%VAL(1,1:nof_Variables)=U_C(I)%VAL(1,1:nof_Variables)+IMPDU(I,1:nof_Variables)
    if ((turbulence.gt.0).or.(passivescalar.gt.0))then
    do k=1,turbulenceequations+passivescalar
	if (U_CT(I)%VAL(1,k)+IMPDU(I,nof_Variables+k).ge.zero)then
  U_CT(I)%VAL(1,k)=U_CT(I)%VAL(1,k)+IMPDU(i,nof_Variables+k)
	end if
    end do
    end if
  end DO
!$OMP END DO
  exit

else
 !$OMP DO SCHEDULE (STATIC)
 DO I=1,KMAXE
 U_C(I)%VAL(1,1:nof_Variables)=U_C(I)%VAL(1,1:nof_Variables)+IMPDU(I,1:nof_Variables)
    if ((turbulence.gt.0).or.(passivescalar.gt.0))then
    do k=1,turbulenceequations+passivescalar
	if (U_CT(I)%VAL(1,k)+IMPDU(I,nof_Variables+k).ge.zero)then
  U_CT(I)%VAL(1,k)=U_CT(I)%VAL(1,k)+IMPDU(i,nof_Variables+k)
	end if
    end do
    end if
  end DO
!$OMP END DO

end if


END DO


dt=dt/1.5d0



IF (AVERAGING.EQ.1)THEN

 CALL AVERAGING_T(N)
 
END IF










  
END SUBROUTINE dual_time_2d







SUBROUTINE AVERAGING_T(N)
!> @brief
!> TEMPORAL AVERAGING FOR UNSTEADY SIMULATIONS
IMPLICIT NONE
INTEGER,INTENT(IN)::N
INTEGER::I,KMAXE,nvar
integer::ind1
KMAXE=XMPIELRANK(N)

  !$OMP MASTER
  IF (RUNGEKUTTA.EQ.11)THEN
  dt=dt*1.5
  END IF
   !$OMP END MASTER

IF (DIMENSIONA.EQ.3)THEN
if (rungekutta.eq.4)then
ind1=7
else
ind1=5
end if

  if (tz1.gt.zero)then
 !$OMP DO
  DO I=1,KMAXE
    U_C(I)%val(ind1,:)=(((Tz1-dt)/(Tz1))*U_C(I)%val(ind1,:))+((dt*U_C(I)%VAL(1,:))/Tz1)
      IF ((TURBULENCE.EQ.1).OR.(PASSIVESCALAR.GT.0))THEN
    DO NVAR=1,TURBULENCEEQUATIONS+PASSIVESCALAR
    
    U_CT(I)%val(ind1,NVAR)=(((Tz1-dt)/(Tz1))*U_CT(I)%val(ind1,NVAR))+((dt*U_CT(I)%VAL(1,NVAR))/(Tz1*U_C(I)%val(ind1,1)))
    
    END DO
    END IF
    !U,V,W,UV,UW,WV,PS
    U_C(I)%RMS(1)=SQRT(abs(((U_C(I)%RMS(1)**2)*((Tz1-dt)/(Tz1)))+(((U_C(I)%VAL(1,2)/U_C(I)%VAL(1,1)-U_C(I)%val(ind1,2)/U_C(I)%val(ind1,1))**2)*dt/Tz1)))
    U_C(I)%RMS(2)=SQRT(abs(((U_C(I)%RMS(2)**2)*((Tz1-dt)/(Tz1)))+(((U_C(I)%VAL(1,3)/U_C(I)%VAL(1,1)-U_C(I)%val(ind1,3)/U_C(I)%val(ind1,1))**2)*dt/Tz1)))
    U_C(I)%RMS(3)=SQRT(abs(((U_C(I)%RMS(3)**2)*((Tz1-dt)/(Tz1)))+(((U_C(I)%VAL(1,4)/U_C(I)%VAL(1,1)-U_C(I)%val(ind1,4)/U_C(I)%val(ind1,1))**2)*dt/Tz1)))
    
    
    
    
   
    U_C(I)%RMS(4)=(((U_C(I)%RMS(4))*((Tz1-DT)/(Tz1)))+&
(((((U_C(I)%VAL(1,2)/U_C(I)%VAL(1,1))-(U_C(I)%val(ind1,2)/U_C(I)%val(ind1,1)))*((U_C(I)%VAL(1,3)/U_C(I)%VAL(1,1))-(U_C(I)%val(ind1,3)/U_C(I)%val(ind1,1)))))*DT/Tz1))
    U_C(I)%RMS(5)=(((U_C(I)%RMS(5))*((Tz1-DT)/(Tz1)))+&
(((((U_C(I)%VAL(1,2)/U_C(I)%VAL(1,1))-(U_C(I)%val(ind1,2)/U_C(I)%val(ind1,1)))*((U_C(I)%VAL(1,4)/U_C(I)%VAL(1,1))-(U_C(I)%val(ind1,4)/U_C(I)%val(ind1,1)))))*DT/Tz1))
    U_C(I)%RMS(6)=(((U_C(I)%RMS(6))*((Tz1-DT)/(Tz1)))+&
(((((U_C(I)%VAL(1,3)/U_C(I)%VAL(1,1))-(U_C(I)%val(ind1,3)/U_C(I)%val(ind1,1)))*((U_C(I)%VAL(1,4)/U_C(I)%VAL(1,1))-(U_C(I)%val(ind1,4)/U_C(I)%val(ind1,1)))))*DT/Tz1))
    IF ((PASSIVESCALAR.GT.0))THEN
    U_C(I)%RMS(7)=SQRT(abs(((U_C(I)%RMS(7)**2)*((Tz1-DT)/(Tz1)))+(((U_CT(I)%VAL(1,TURBULENCEEQUATIONS+1)&
-U_CT(I)%val(ind1,TURBULENCEEQUATIONS+1))**2)*DT/Tz1)))
    end if
   
   
   
    
  END DO
  !$OMP END DO
  else
  !$OMP DO
  DO I=1,KMAXE
    U_C(I)%val(ind1,:)=ZERO;U_C(I)%RMS=zero
    IF ((TURBULENCE.EQ.1).OR.(PASSIVESCALAR.GT.0))THEN
    
    
    U_CT(I)%val(ind1,:)=ZERO
    
    
    END IF
  
  END DO
  !$OMP END DO
  end if

ELSE
if (t.gt.0.0)then
  !$OMP DO
  DO I=1,KMAXE
    U_C(I)%val(ind1,:)=(((Tz1-dt)/(Tz1))*U_C(I)%val(ind1,:))+((dt*U_C(I)%VAL(1,:))/Tz1)
      IF ((TURBULENCE.EQ.1).OR.(PASSIVESCALAR.GT.0))THEN
    DO NVAR=1,TURBULENCEEQUATIONS+PASSIVESCALAR
    
    U_CT(I)%val(ind1,NVAR)=(((Tz1-dt)/(Tz1))*U_CT(I)%val(ind1,NVAR))+((dt*U_CT(I)%VAL(1,NVAR))/(Tz1*U_C(I)%val(ind1,1)))
    
    END DO
    END IF
    !U,V,UV,PS
    U_C(I)%RMS(1)=SQRT(abs(((U_C(I)%RMS(1)**2)*((Tz1-dt)/(Tz1)))+(((U_C(I)%VAL(1,2)-U_C(I)%val(ind1,2))**2)*dt/Tz1)))/U_C(I)%val(ind1,1)
    U_C(I)%RMS(2)=SQRT(abs(((U_C(I)%RMS(2)**2)*((Tz1-dt)/(Tz1)))+(((U_C(I)%VAL(1,3)-U_C(I)%val(ind1,3))**2)*dt/Tz1)))/U_C(I)%val(ind1,1)
    
   
    U_C(I)%RMS(3)=(((U_C(I)%RMS(4))*((Tz1-dt)/(Tz1)))+&
((((U_C(I)%VAL(1,2)-U_C(I)%val(ind1,2))*(U_C(I)%VAL(1,3)-U_C(I)%val(ind1,3))))*dt/Tz1))/U_C(I)%val(ind1,1)
    
    IF ((PASSIVESCALAR.GT.0))THEN
    U_C(I)%RMS(4)=SQRT(abs(((U_C(I)%RMS(4)**2)*((Tz1-dt)/(Tz1)))+(((U_CT(I)%VAL(1,TURBULENCEEQUATIONS+1)&
-U_CT(I)%val(ind1,TURBULENCEEQUATIONS+1))**2)*dt/Tz1)))/U_C(I)%val(ind1,1)
    end if
    
  END DO
  !$OMP END DO
  else
  !$OMP DO
  DO I=1,KMAXE
    U_C(I)%val(ind1,:)=ZERO
    IF ((TURBULENCE.EQ.1).OR.(PASSIVESCALAR.GT.0))THEN
    
    
    U_CT(I)%val(ind1,:)=ZERO
    
    
    END IF
  
  END DO
  !$OMP END DO
  end if
 END IF

 !$OMP MASTER
  IF (RUNGEKUTTA.EQ.11)THEN
  dt=dt/1.5
  END IF
   !$OMP END MASTER
   
   IF (OUTSURF.EQ.1)THEN
   CALL EXCHANGE_HIGHER_AV(N)
   CALL AVERAGE_STRESSES(N)
   END IF
   
   



END SUBROUTINE AVERAGING_T


! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! ! !---------------------------------------------------------------------------------------------!
! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! ! !!!!!!!!!!!!!!!!!!SUBROUTINE CALLED TO ADVANCE SOLUTION BY ONE TIME STEP SIZE!!!!!!!!!!!!!!!!!!
! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! ! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

SUBROUTINE TIME_MARCHING(N)
!> @brief
!> TIME MARCHING SUBROUTINE 3D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
real,dimension(1:5)::DUMMYOUT,DUMMYIN
INTEGER::I,KMAXE
REAL::CPUT1,CPUT2,CPUT3,CPUT4,CPUT5,CPUT6,CPUT8,timec3,TIMEC1,TIMEC4,TIMEC8,TOTV1,TOTV2,DUMEtg1,DUMEtg2,TOTK
      kill=0
      T=RES_TIME
      iscoun=1

!$OMP BARRIER
!$OMP MASTER 
	CPUT1=CPUX1(1)
	CPUT4=CPUX1(1)
	CPUT5=CPUX1(1)
	CPUT8=CPUX1(1)
!$OMP END MASTER 
!$OMP BARRIER
      
	      			
	IT=RESTART
      
!$OMP BARRIER
!$OMP MASTER 
      CALL GRID_WRITE
      if ((Average_restart.eq.0).and.(averaging.eq.1)) then
				Tz1=0.0
				else
				tz1=t
		end if
      
      
!$OMP END MASTER 
!$OMP BARRIER
      


!$OMP BARRIER
!$OMP MASTER
	CALL VOLUME_SOLUTION_WRITE
	IF (OUTSURF.EQ.1)THEN
	CALL SURF_WRITE
	END IF
!$OMP END MASTER
!$OMP BARRIER
      		
             
      
      
      
      
     DO 
		    CALL CALCULATE_CFL(N)
		    
		    IF (RUNGEKUTTA.GE.5)CALL CALCULATE_CFLL(N)
			!$OMP MASTER
			DUMMYOUT(1)=DT
			CPUT2=MPI_WTIME()
			TIMEC8=CPUT2-CPUT8
			TIMEC1=CPUT2-CPUT1
		        dummyout(2)=TIMEC1
			DUMMYIN=0.0
			timec3=cput2-cput4
			dummyout(3)=TIMEC3
			TIMEC4=CPUT2-CPUT5
			dummyout(4)=TIMEC4
			DUMMYOUT(5)=TIMEC8
			
			CALL MPI_ALLREDUCE(DUMMYOUT,DUMMYIN,5,MPI_DOUBLE_PRECISION,MPI_MIN,MPI_COMM_WORLD,IERROR)
			
			DT=DUMMYIN(1)
			TIMEC1=DUMMYIN(2)
			TIMEC3=DUMMYIN(3)
			TIMEC4=DUMMYIN(4)
			TIMEC8=DUMMYIN(5)
				   IF (N.EQ.0)THEN
				  OPEN(63,FILE='history.txt',FORM='FORMATTED',STATUS='old',ACTION='WRITE',POSITION='APPEND')
				  WRITE(63,*)DT,it,"TIME STEP SIZE",T
				  CLOSE(63)
				  END IF
					
					
					IF (INITCOND.eq.95)THEN                    
 				TOTK=0
 				DO I=1,xmpielrank(n)
					TOTK=TOTK+IELEM(N,I)%TOTVOLUME*U_C(I)%VAL(1,1)*(1.0/2.0)*&
(((U_C(I)%VAL(1,2)/U_C(I)%VAL(1,1))**2)+((U_C(I)%VAL(1,3)/U_C(I)%VAL(1,1))**2)+((U_C(I)%VAL(1,4)/U_C(I)%VAL(1,1))**2))
				END DO
! 				
 				DUMEtg1=TOTK
 				DUMEtg2=0.0
 				CALL MPI_BARRIER(MPI_COMM_WORLD,IERROR)
 				CALL MPI_ALLREDUCE(DUMEtg1,DUMEtg2,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERROR)
 				TOTK=DUMEtg2
 				IF (N.EQ.0)THEN
 				TOTV1=TOTK/((2.0*PI)**3)
					if (it.eq.0)then
					TAYLOR=TOTK
					end if
					
				
				
				END IF
 				
 				
!  				CALL MPI_BARRIER(MPI_COMM_WORLD,IERROR)
 				

! 				end if
			    end if
					
					
					
					
					
					
					
					
			!$OMP END MASTER 
			!$OMP BARRIER		
			
			
			if (rungekutta.eq.11)then
			dt=timestep
			DT=MIN(DT,OUT_TIME-T)
			else
			DT=MIN(DT,OUT_TIME-T)
			end if
			
			
			
			SELECT CASE(RUNGEKUTTA)
			
			CASE(1)
			CALL RUNGE_KUTTA1(N)
			
			CASE(2)
			CALL RUNGE_KUTTA2(N)
			
			CASE(3)
			CALL RUNGE_KUTTA3(N)
			
			CASE(4)
			CALL RUNGE_KUTTA4(N)
			
			CASE(5)
			CALL RUNGE_KUTTA5(N)
			
			case(10)
			call IMPLICIT_TIMEs(N)
			
			
			case(11)
			call dual_TIME(N)
			
			END SELECT
			
			!$OMP BARRIER
			!$OMP MASTER
			
			if (rungekutta.eq.11)then
 			 T=T+(DT)
 			  Tz1=Tz1+(DT)

			else
                       T=T+DT
			tz1=tz1+DT
			  end if
			  
			
			
! 			IF (N.EQ.0)THEN
! 				  OPEN(63,FILE='history.txt',FORM='FORMATTED',STATUS='old',ACTION='WRITE',POSITION='APPEND')
! 				  if (rungekutta.eq.11)then
! 				  WRITE(63,*)DT,it,"TIME STEP SIZE",T
! 				  end if
! 				  CLOSE(63)
! 				  END IF
			
			
			
			
			
			
			
			
			IF (INITCOND.eq.95)THEN                    
 				TOTK=0
 				DO I=1,xmpielrank(n)
					TOTK=TOTK+IELEM(N,I)%TOTVOLUME*U_C(I)%VAL(1,1)*(1.0/2.0)*&
(((U_C(I)%VAL(1,2)/U_C(I)%VAL(1,1))**2)+((U_C(I)%VAL(1,3)/U_C(I)%VAL(1,1))**2)+((U_C(I)%VAL(1,4)/U_C(I)%VAL(1,1))**2))
				END DO
! 				
 				DUMEtg1=TOTK
 				DUMEtg2=0.0
 				CALL MPI_BARRIER(MPI_COMM_WORLD,IERROR)
 				CALL MPI_ALLREDUCE(DUMEtg1,DUMEtg2,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERROR)
 				TOTK=DUMEtg2
 				IF (N.EQ.0)THEN
 				TOTV2=TOTK/((2.0*PI)**3)
					if (it.eq.0)then
					TAYLOR=TOTK
					end if
					
				IF (IT.EQ.0)THEN
				OPEN(73,FILE='ENERGY.dat',FORM='FORMATTED',STATUS='NEW',ACTION='WRITE',POSITION='APPEND')
				ELSE
				OPEN(73,FILE='ENERGY.dat',FORM='FORMATTED',STATUS='old',ACTION='WRITE',POSITION='APPEND')
				end if
				WRITE(73,*)T,TOTK/TAYLOR,-(TOTV2-TOTV1)/DT
				CLOSE(73)
				END IF
 				
 				
 				CALL MPI_BARRIER(MPI_COMM_WORLD,IERROR)
 				

! 				end if
			    end if
			
			
			
			
			!$OMP END MASTER 
			!$OMP BARRIER
			
			if ( mod(it, iforce) .eq. 0) then
			IF (OUTSURF.EQ.1) THEN   
				  CALL forces
			end if
			end if
			
			if ((rungekutta.ge.5).and.(rungekutta.ne.11))then
			if ( mod(it, residualfreq) .eq. 0) then
                               Call RESIDUAL_COMPUTE
			end if
			end if
			
			!$OMP MASTER
			IF (NPROBES.GT.0) call PROBING
					
			
			IF (TIMEC1.GE.IEVERY)THEN
			    CALL VOLUME_SOLUTION_WRITE
			     if (outsurf.eq.1)then
			    call surface_SOLUTION_WRITE
			    end if
			CPUT1=MPI_WTIME()
			END IF
			
			
			
			IF (TIMEC8.GE.IEVERYAV)THEN
			IF (AVERAGING.EQ.1)THEN
			call VOLUME_SOLUTION_WRITE_av
			   if (outsurf.eq.1)then
			  call surface_SOLUTION_WRITE_av
			  end if
			end if
			CPUT8=MPI_WTIME()
			end if
			
			
			
			IF (TIMEC4.GE.IEVERY2)THEN
			    call CHECKPOINTING
			      IF (AVERAGING.EQ.1)THEN
				call CHECKPOINTING_av
			      end if
	
			  CPUT5=MPI_WTIME()
			  
			END IF
			  
			
			!$OMP END MASTER 
			!$OMP BARRIER
			
			
			
			!$OMP MASTER
			IT=IT+1
			
			IF ((IT.EQ.NTMAX).OR.(TIMEC3.GE.WALLC))THEN
			 KILL=1
			END IF
			
			if ((rungekutta.lt.5).or.(rungekutta.eq.11))then
			IF (T.GE.OUT_TIME)THEN
			KILL=1
			END IF
			END IF
			!$OMP END MASTER 
			!$OMP BARRIER

			  
			!$OMP MASTER
			if (kill.eq.1)then
			    CALL VOLUME_SOLUTION_WRITE
			      if (outsurf.eq.1)then
			      call surface_SOLUTION_WRITE
			      end if
			    call CHECKPOINTING
			      IF (AVERAGING.EQ.1)THEN
			      call VOLUME_SOLUTION_WRITE_av
				if (outsurf.eq.1)then
				  call surface_SOLUTION_WRITE_av
				end if	    
				call CHECKPOINTING_av
			      end if
			end if
			
			
			
			
			!$OMP END MASTER
			!$OMP BARRIER
			
			if (kill.eq.1)then
			if (itestcase.le.3)then   
			call CALCULATE_ERROR(n)
			end if
			  
			  
			  
			  
			  
			  
			  
			  
			  
			  
			return
			end if

			
			
			
end do
		      
END SUBROUTINE TIME_MARCHING





SUBROUTINE TIME_MARCHING2(N)
!> @brief
!> TIME MARCHING SUBROUTINE 2D
IMPLICIT NONE
INTEGER,INTENT(IN)::N
real,dimension(1:5)::DUMMYOUT,DUMMYIN
INTEGER::I,KMAXE
REAL::CPUT1,CPUT2,CPUT3,CPUT4,CPUT5,CPUT6,CPUT8,timec3,TIMEC1,TIMEC4,TIMEC8,TOTV1,TOTV2,DUMEtg1,DUMEtg2,TOTK
kmaxe=XMPIELRANK(n)
      kill=0
      T=res_time
      iscoun=1
	!$OMP MASTER 
	CPUT1=CPUX1(1)
	CPUT4=CPUX1(1)
	CPUT5=CPUX1(1)
	CPUT8=CPUX1(1)
	!$OMP END MASTER 
         !$OMP BARRIER
      
	      			
	IT=RESTART
      
      !$OMP MASTER 
      CALL GRID_WRITE
      CALL VOLUME_SOLUTION_WRITE
       if (outsurf.eq.1)then
      call SURF_WRITE
      end if
      if ((Average_restart.eq.0).and.(averaging.eq.1)) then
				Tz1=0.0
				else
				tz1=t
		end if
      !$OMP END MASTER 
      !$OMP BARRIER
      
     DO 
		    CALL CALCULATE_CFL2D(N)
		    IF (RUNGEKUTTA.GE.5)CALL CALCULATE_CFLL2d(N)
		    
			!$OMP MASTER
			DUMMYOUT(1)=DT
			CPUT2=MPI_WTIME()
			TIMEC8=CPUT2-CPUT8
			TIMEC1=CPUT2-CPUT1
		        dummyout(2)=TIMEC1
			DUMMYIN=0.0d0
			timec3=cput2-cput4
			dummyout(3)=TIMEC3
			TIMEC4=CPUT2-CPUT5
			dummyout(4)=TIMEC4
			DUMMYOUT(5)=TIMEC8
			
			CALL MPI_ALLREDUCE(DUMMYOUT,DUMMYIN,5,MPI_DOUBLE_PRECISION,MPI_MIN,MPI_COMM_WORLD,IERROR)
			
			DT=DUMMYIN(1)
			TIMEC1=DUMMYIN(2)
			TIMEC3=DUMMYIN(3)
			TIMEC4=DUMMYIN(4)
			TIMEC8=DUMMYIN(5)
				  IF (N.EQ.0)THEN
				  OPEN(63,FILE='history.txt',FORM='FORMATTED',STATUS='old',ACTION='WRITE',POSITION='APPEND')
				  WRITE(63,*)DT,it,"TIME STEP SIZE",T
				  CLOSE(63)
				  END IF
				  
			IF (INITCOND.eq.95)THEN                    
 				TOTK=0
 				DO I=1,KMAXE
					TOTK=TOTK+IELEM(N,I)%TOTVOLUME*(1.0/2.0)*&
(((U_C(I)%VAL(1,2)/U_C(I)%VAL(1,1))**2)+((U_C(I)%VAL(1,3)/U_C(I)%VAL(1,1))**2))
				END DO
! 				
 				DUMEtg1=TOTK
 				DUMEtg2=0.0
 				CALL MPI_BARRIER(MPI_COMM_WORLD,IERROR)
 				CALL MPI_ALLREDUCE(DUMEtg1,DUMEtg2,1,MPI_DOUBLE_PRECISION,MPI_SUM,MPI_COMM_WORLD,IERROR)
 				TOTK=DUMEtg2
 				IF (N.EQ.0)THEN
!  				TOTV2=TOTK/((2.0*PI)**3)
! 					if (it.eq.0)then
! 					TAYLOR=TOTK
! 					end if
					
				IF (IT.EQ.0)THEN
				OPEN(73,FILE='ENERGY.dat',FORM='FORMATTED',STATUS='NEW',ACTION='WRITE',POSITION='APPEND')
				ELSE
				OPEN(73,FILE='ENERGY.dat',FORM='FORMATTED',STATUS='old',ACTION='WRITE',POSITION='APPEND')
				end if
				WRITE(73,*)T,TOTK
				CLOSE(73)
				END IF
 				
 				
 				CALL MPI_BARRIER(MPI_COMM_WORLD,IERROR)
 				

! 				end if
			    end if
			
			
			
			!$OMP END MASTER 
			!$OMP BARRIER
			
			if (rungekutta.eq.11)then
			dt=timestep
                      DT=MIN(DT,OUT_TIME-T)
		      else
		      DT=MIN(DT,OUT_TIME-T)
		      end if
			
			SELECT CASE(RUNGEKUTTA)
			
			CASE(1)
			CALL RUNGE_KUTTA1_2d(N)
			
			CASE(2)
			CALL RUNGE_KUTTA2_2d(N)
			
			CASE(3)
			CALL RUNGE_KUTTA3_2D(N)
			
			CASE(4)
			CALL RUNGE_KUTTA4_2D(N)
			
			CASE(5)
			CALL RUNGE_KUTTA5_2D(N)
			
			
			case(10)
			call IMPLICIT_TIMEs_2d(N)
			
			
			case(11)
			call dual_TIME_2d(N)
			
			END SELECT
			
			!$OMP MASTER
			if (rungekutta.eq.11)then
 			 T=T+(DT)
 			  Tz1=Tz1+(DT)

			else
                       T=T+DT
			tz1=tz1+DT
			  end if
			  
			  
			  
			  
			  
			  
			  
			  
			!$OMP END MASTER 
			!$OMP BARRIER
			if ( mod(it, iforce) .eq. 0) then
			IF (OUTSURF.EQ.1) THEN   
				  CALL forces
			end if
			end if
			
			if ((rungekutta.ge.5).and.(rungekutta.ne.11))then
			if ( mod(it, residualfreq) .eq. 0) then
                               Call RESIDUAL_COMPUTE
			end if
			end if
			
			!$OMP MASTER
			IF (NPROBES.GT.0) call PROBING2D
					
			
			IF (TIMEC1.GE.IEVERY)THEN
			    CALL VOLUME_SOLUTION_WRITE
			     if (outsurf.eq.1)then
			    call surface_SOLUTION_WRITE
			    end if
			CPUT1=MPI_WTIME()
			END IF
			
			
			
			IF (TIMEC8.GE.IEVERYAV)THEN
			IF (AVERAGING.EQ.1)THEN
			call VOLUME_SOLUTION_WRITE_av
			   if (outsurf.eq.1)then
			  call surface_SOLUTION_WRITE_av
			  end if
			end if
			CPUT8=MPI_WTIME()
			end if
			
			
			
			IF ((TIMEC4.GE.IEVERY2).OR.(TIMEC3.GE.WALLC)) THEN
			  CPUT5=MPI_WTIME()
				IF (TIMEC3.GE.WALLC) THEN
				  KILL=1
				END IF
				
			  if (kill.eq.1)then
			  CALL VOLUME_SOLUTION_WRITE
			   if (outsurf.eq.1)then
			    call surface_SOLUTION_WRITE
			    
			    end if
			  
			  call CHECKPOINTING
			  
			
			IF (AVERAGING.EQ.1)THEN
			  call CHECKPOINTING_av
			end if
			else
			
			  CALL VOLUME_SOLUTION_WRITE
			    if (outsurf.eq.1)then
			      call surface_SOLUTION_WRITE
			      
			      end if
			  IF (AVERAGING.EQ.1)THEN
			    call CHECKPOINTING_av
			  end if

			end if
			end if
			if ((rungekutta.lt.5).or.(rungekutta.eq.11))then
			IF (T.GE.OUT_TIME)THEN
 			  KILL=1
			  
			  CALL VOLUME_SOLUTION_WRITE
			   if (outsurf.eq.1)then
			    call surface_SOLUTION_WRITE
			    end if
			  
			  call CHECKPOINTING
			 
			  if (averaging .eq.1) then
			  call VOLUME_SOLUTION_WRITE_av
			   if (outsurf.eq.1)then
			  call surface_SOLUTION_WRITE_av
			  end if
			  call CHECKPOINTING_av
			  end if			
			END IF
			end if
			!$OMP END MASTER 
			!$OMP BARRIER
			
			
			
			!$OMP MASTER
			IT=IT+1
			IF (IT.EQ.NTMAX)THEN
			 KILL=1
			END IF
			!$OMP END MASTER 
			!$OMP BARRIER
		    
			if (kill.eq.1)then
			IF (OUTSURF.EQ.1) THEN   
				  CALL forces
			  end if
			
			!$OMP MASTER
			if ((rungekutta.eq.5).or.(rungekutta.eq.10))then
			  CALL VOLUME_SOLUTION_WRITE
			   if (outsurf.eq.1)then
			    call surface_SOLUTION_WRITE
			    
			    end if
			  
			  call CHECKPOINTING
			end if
			!$OMP END MASTER
			!$OMP BARRIER
			
			if (itestcase.le.3)then   
			call CALCULATE_ERROR(n)
			end if
			
			
			return
			end if
			
			
			
end do
		      
END SUBROUTINE TIME_MARCHING2





!---------------------------------------------------------------------------------------------!
END MODULE ADVANCE
