MODULE DECLARATION	
!--------------------------------------------------------------------------------------------------------------------------!
!HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH!
!_____________________________________________ START HEADER OF MODULE______________________________________________________!
!FUNCTION: IS TO COLLECT ALL THE GLOBAL VARIABLES, AND DATA TYPES OF THE CODE IN ONE MODULE
!////////////////////////////////////RESPONSIBLE TSOUTSANIS PANAGIOTIS/////////////////////////////////////////////////////! 
!**************************************************************************************************************************!
!_____________________________________________ END HEADER OF MODULE________________________________________________________!
!--------------------------------------------------------------------------------------------------------------------------!

IMPLICIT NONE

#if defined(WENOWEIGHTS_GPU_KERNEL) || defined(LEASTSQUARES_GPU_KERNEL)
!$omp declare target(adda_filter_strong, adda_filter_weak, adda_type, angle_per, cavitation, dg, dimensiona, dt, ees, gamma, gamma_in, governingequations, ibound, idegfree, idegfree2, iorder, iorder2, iscoun, it, lwci1, mp_pinf, multispecies, nof_species, nof_variables, numberofpoints2, oo2, passivescalar, per_rot, qp_array, qp_line, qp_quad, qp_triangle, rungekutta, turbulenceequations, typesten, viscous_s, wenoz, wenwrt, zero)


!$omp declare target(beta_i1, bleed_end, bleed_plenum, bleed_porosity, bleed_start, boundtype, initcond, itestcase, i_turb_inlet, kinit_srf, mp_a_in, mp_r_in, pi, pres, press_outlet, rres, swirl, t, tolsmall, turbinit, turbulence, turbulencemodel, ufreestream, uvel, visc, vvel, wvel)

!$omp declare target(poly,numneighbours2)
#endif
!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.1.   INTEGER  VARIABLES HERE                  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!

INTEGER::CASCADE,MOOD,MOOD_MODE,kmaxn,multispecies,nof_species,DIMENSIONA,LOWMEM,binio,nof_variables,CHUNK_N,dims,IRES_TURB,CODE_PROFILE,IRES_UNSTEADY,LAMPS,itotalb,totiw,ICOMPACT,EES,iscoun,itold,lmach_style,WEIGHT_LSQR	!DIMENSIONS OF PROBLEM
integer::governingequations,FILTERING,guassianquadra,temporder,iboundary,wenocnschar,required,nodes_i,SWIRL,IADAPT,TECPLOT,STENCIL_IO,SURFSHEAR,ISSF,n_boundaries,FASTEST_Q,STATISTICS,ADDA,ALLS
integer,allocatable,DIMENSION(:,:)::jtot1,jtot2,jtot3,jtot,el_connect
integer::jtotAL,JTOTAL1,JTOTAL2,JTOTAL3,fastmovie,movement,TYP_COUNTN_GLOBAL,TYP_COUNTN,TYP_COUNTN_GLOBAL_W,TYP_COUNTN_w
INTEGER::FILTER_TYPE,fil_nc,fil_s,fil_alpha		!FILTER VALUES
INTEGER::ADDA_TYPE,ADDA_alpha_1,ADDA_alpha_2,ADDA_1_S,ADDA_2_S,ADDA_1,ADDA_2		!FILTER VALUES
INTEGER::KILL			 ! FLAG FOR KILLING A SIMULATION
INTEGER::NDERIVATIVE		  	! INDEX OF THE NUMBERING OF THE COMPONENT OF THE POLYNOMIALS 
REAL::output_freq				!OUTPUT FREQUENCY IN SIMULATION TIME
INTEGER::EXTENDED_BOUNDS		!BOUNDS STRICT OR RELAXED
INTEGER::ICONSR					! INDEX FOR IDENTIFYING THE CONSIDERED ELEMENT 
INTEGER::INWHICHEL				! INDEX FOR IDENTIFYING THE CONSIDERED ELEMENT WITHIN A STENCIL 
INTEGER::SUBDIV					! INDEX FOR THE NUMBER OF SUBDIVISIONS OF A FACE
INTEGER::ICONSGVQ				! INDEX FOR CONSIDERED CELL
INTEGER::IGIANAGRAPS				!INDEX FOR CONSIDERED CELL
INTEGER::IT					! NUMBER OF ITERATIONS
INTEGER::ICONIMP				!INDEX FOR CONSIDERED CELL
INTEGER::IBCODE					! INDEX FOR BOUNDARY CONDITION CODE
INTEGER::IBSIDE					! INDEX FOR WHICH SIDE OF CELL IS BOUNDED
INTEGER::CFW					!INDEX FOR DETERMINING FROM THE WHICH SECTION THE BOUNDARY SUBROUTINE IS CALLED
INTEGER::DG, BR2_YN                     ! FLAG FOR DG DISCRETISATION
REAL:: BR2_DAMPING
INTEGER::LOWMEMORY				! MEMORY USAGE FLAG
INTEGER::FASTEST				! FASTEST MODE FLAG FOR THE CODE
INTEGER::EMETIS					! TYPE OF METIS PARTITIONING
INTEGER::ALLNODESGLOBALL			! TOTAL NUMBER OF NODES IN THE DOMAIN
INTEGER::SPATILADISCRET				! SPATIAL DISCRETISATION
INTEGER::SPATIALORDER    			! SPATIAL ORDER
INTEGER::JK					!INDEX
INTEGER::NUMNEIGHBOURS,NUMNEIGHBOURS2				! NUMBER OF NEIGHBOURS IN THE STENCILS 
INTEGER::RESTART				! FLAG FOR DETERMINING IF A RESTART FILE IS PRESENT			
INTEGER::IHYBRID				!HYBRID MODE WHERE SOME PART OF THE DOMAIN IS SOLVED WITH LOWER ORDER AND ANOTHER WITH HIGHER ORDER SCHEMES	
integer::UPPERLIMIT !
INTEGER::RESIDUALFREQ				!FREQUENCY FOR WRITING THE RESIDUALS
INTEGER::IRS					!IMPLICIT RESIDUAL SMOOTHING VERSION
INTEGER::GREENGO				!GRADIENT APPROXIMATION TECHNIQUES
INTEGER::LMACH					!LOW MACH PRECONDITIONING
INTEGER::ISPAL					!TYPE OF SPALART ALLMARAS MODIFICATION	
INTEGER::RELAX					!RELAXATION SCHEMES GAUSS SEIDEL, JACOBIAN ETC
INTEGER::ICONG					!INDEX FOR CONSIDERED CELL
INTEGER::ILOOP					!INDEX FOR CONSIDERED CELL
INTEGER::CFLRAMP				!CFL RAMPING ACTIVATED FOR IMPLICIT TIME STEPPING
INTEGER::AVERAGING				!FLAG FOR ACTIVATING AVERAGING OF TRANSIENT DATA
INTEGER::AVERAGE_RESTART			!FLAG FOR HAVING A RESTART FILE WITH THE AVERAGED SOLUTION
INTEGER::PREV_TURBMODEL				!FLAG OF PREVIOUS TURBULENCE MODEL IN CASE OF A RESTART FILE
INTEGER::IFORCE					!INDEX ON HOW OFTEN TO COMPUTE THE FORCES
INTEGER::BOUNDTYPE				!TYPE OF BOUNDARY CONDITION SUPERSONIC,  SUBSONIC
INTEGER::NPROC					!NUMBER OF CPUS							
INTEGER::INITCOND				!INITIAL CONDITION TYPE
INTEGER::WENWRT					!WENO WRT TO WHICH VARIABLE CONSERVED, CHARACTERISTICS ETC
INTEGER::POLY					!INTERPOLATING POLYNOMIALS 1 GENERIC, 2 LEGENDRE
INTEGER::IVORTEX				!Q CRITERION COM PUTATION
INTEGER::ICARLOS1				!INDEX FOR CONSIDERED ELEMENT PASSIVE SCALARS, COMPLICATED INFLOW CONDITION
INTEGER::ICARLOS2				!INDEX FOR CONSIDERED FACE PASSIVE SCALARS, COMPLICATED INFLOW CONDITION
INTEGER::IMAXE					!TOTAL NUMBER OF ELEMENTS OF THE GRID
INTEGER::NTMAX					!MAXIMUM NUMBER OF ITERATIONS
INTEGER::IHAX1					!TEMPORARY INTEGER USED AS POINTER FOR OPERATIONS REGARDING HEXAHEDRAL ELEMENTS					
INTEGER::LIMITER				!SLOPE LIMITER
INTEGER::IEXTEND				!EXTEND PARAMETER FOR CENTRAL BIG STENCIL ONLY FOR WENO CASES
INTEGER::IDEGFREE,idegfree2,inum2,idegfree3		!DEGREES OF FREEDOM OF POLYNOMIAL IT WILL BECOME LOCA	L
INTEGER::OUTSURF				!OUTSURF STANDS FOR COMPUTING FORCES 
INTEGER::UNWOU					!TYPE OF OUTPUT FILES TO WRITE ALL PARTITIONS TO ONE FILE ETC
INTEGER::IGQRULES				!GAUSSIAN QUADRATURE RULE
INTEGER::IMAXDEGFREE,IMAXDEGFREE2				!MAXIMUM NUMBER OF NEIGHBOURS
INTEGER::QP_HEXA,QP_TETRA,QP_PYRA,QP_PRISM,QP_QUAD,QP_TRIANGLE,QP_LINE,qp_line_n,reduce_comp,QP_QUAD_n,QP_TRIANGLE_n !VOLUME GAUSSIAN QUADRATURE POINTS
!> Number of points allocated to QPOINTS, WEQUA (Coords and weights for quadrature points)
INTEGER::NUMBEROFPOINTS,NUMBEROFPOINTS2
INTEGER::RESCOUNTER				!COUNTER FOR RESIDUALS
INTEGER::RESCOUNTERT				!COUNTER FOR TURBULENCE RESIDUALS
INTEGER::ILX					!DEGREES OF FREEDOM FOR REQUIRED ORDER OF ACCURACY
INTEGER::IMAXB					!TOTAL NUMBER OF BOUNDARY CONDITIONS
INTEGER::IMAXN					!TOTAL NUMBER OF NODES PRESENT IN THE GRID
INTEGER::IN					!INDEX FOR CONSIDERED CELL
INTEGER::IORDER,IORDER2					!ORDER OF ACCURACY (SPATIAL)
INTEGER::IOVERST				! NUMBER OF ELEMENTS FOR THE STENCIL OVERDETERMINED MATRIX REQUIRED FOR AVOIDING ILL CONDITIONS
INTEGER::IOVERTO				! NUMBER OF ELEMENTS FOR THE ESTAB STENCILS OVERDETERMINED MATRIX REQUIRED FOR AVOIDING ILL CONDITIONS
INTEGER::QRDE					!TYPE OF SOLUTION FOR THE LEAST SQUARES PROBLEM
INTEGER::RUNGEKUTTA     			!TIME STEPPING SCHEME TYPE
INTEGER::ISCHEME 				!TYPE OF SCHEME TO BE USED
INTEGER::ISPLIT					!UNSPLIT FINIT VOLUME SCHEME
INTEGER::ISELEM					!MAXIMUM NUMBER OF ELEMENTS REQUIRED FOR THE STENCIL DEPENDENT ON THE ORDER OF ACCURACY
INTEGER::ISTN					!VARIABLE THAT TAKES EACH TIME THE VALUE OF THE CONSIDERED ELEMENT  TO FIND NEIGHBOURS IN THE STENCIL
INTEGER::ITT,wenoz					!INTEGER VARIABLE USED FOR OPENING FILES
INTEGER::ITESTCASE              !TYPES OF EQUATIONS TO BE SOLVED
INTEGER::IWEIGHTLSQR    			!WEIGHTED LEAST SQURES OPTION OF INVERTED DISTANCE
INTEGER::TYPESTEN				!NUMBER OF STENCILS FOR WENO
INTEGER::IPERIODICITY				!PERIODICITY DETECTED IN DOMAIN	
INTEGER::IWENO					!TYPE OF SCHEMES WENO, MUSCL, UNLIMITED
INTEGER::TURBULENCE				!TURBULENCE EQUATIONS
INTEGER::TURBULENCEMODEL			!WHICH MODEL
INTEGER::TURBULENCEEQUATIONS			!HOW MANY EQUATIONS TO SOLVE
INTEGER::ICOUPLETURB				!COUPLED TURBULENCE MODEL
INTEGER::IRIEMANN				!RIEMANN SOLVER
INTEGER::FIRSTORDER				!FIRST ORDER SCHEME ACTIVE
INTEGER::PASSIVESCALAR				!ADDITIONAL TRANSPORT EQUATIONS
INTEGER::QSAS_MODEL				!QSAS MODEL
INTEGER::VORT_MODEL				!VORTICITY MODEL
INTEGER::ZERO_TURB_INIT				!FLAG FOR TYPE OF INITIALIZATION FOR K-OMEGA
INTEGER::DES_MODEL 				!INTEGER SWITCHES FOR SST
INTEGER:: NPROBES,totwalls,NOF_INTERIOR,NOF_BOUNDED,MRF			!NUMBER OF PROBES FOR TRANSIENT DATA
INTEGER:: ROT_CORR,D_CORR   !integer for turbulence corrections
!--------------------- variables for parallel partitioned output-------!
INTEGER,ALLOCATABLE,DIMENSION(:)::DISPART1,DISPART2,DISPART3,DISPART4,DISPART5,TYP_NODESN,TYP_NODESN_w
INTEGER,ALLOCATABLE,DIMENSION(:)::iARRAY_PART1,iARRAY_PART2,iARRAY_PART3,iARRAY_PART4,iARRAY_PART5,i_ARRAY_PART2x
REAL,ALLOCATABLE,DIMENSION(:)::rARRAY_PART4,rARRAY_PART2,rARRAY_PART3,rARRAY_PART5
INTEGER,ALLOCATABLE,DIMENSION(:)::WDISPART1,WDISPART2,WDISPART3,WDISPART4,WDISPART5,WALLCOUNT_CPU_L,WALLCOUNT_CPU_G
INTEGER,ALLOCATABLE,DIMENSION(:)::WiARRAY_PART1,WiARRAY_PART2,WiARRAY_PART3,WiARRAY_PART4,WiARRAY_PART5
INTEGER,ALLOCATABLE,DIMENSION(:)::offset_vtu,connect_vtu,type_vtu,offset_vtu_W,connect_vtu_W,type_vtu_W
REAL,ALLOCATABLE,DIMENSION(:,:)::sol_vtu,sol_vtu_W
REAL,ALLOCATABLE,DIMENSION(:)::nodes_vtu,nodes_vtu_W
REAL,ALLOCATABLE,DIMENSION(:)::WrARRAY_PART4,WrARRAY_PART2,WrARRAY_PART3,WrARRAY_PART5
REAL,ALLOCATABLE,DIMENSION(:,:)::rARRAY_PART1,WrARRAY_PART1
INTEGER::PART1_end,PART2_end,PART3_end,PART4_end,PART5_end
INTEGER::WPART1_end,WPART2_end,WPART3_end,WPART4_end,WPART5_end
INTEGER::KDUM1,KDUM2,write_variables,write_variables_av,NODES_PART
INTEGER::WKDUM1,WKDUM2,write_variables_W,write_variables_av_W,WNODES_PART
INTEGER::DATATYPEX,DATATYPEy,DATATYPEz,DATATYPEXx,DATATYPEyy,DATATYPEINT
INTEGER,DIMENSION(1)::KDUM3
CHARACTER(LEN=25)::Variable_names(15),Variable_names_av(15)
INTEGER::WDATATYPEX,WDATATYPEy,WDATATYPEz,WDATATYPEXx,WDATATYPEyy,WDATATYPEINT
INTEGER,DIMENSION(1)::WKDUM3
CHARACTER(LEN=25)::Variable_names_W(15),Variable_names_av_W(15)
integer::kloopx,iloopx,totwallsc,IWMAXE
iNTEGER,ALLOCATABLE,DIMENSION(:)::WALLIT,OFFSETWALL,WALL_NODES,WALLCX,OFFSETWC,OFFSETWC_G,WALLCX_g,WALLSHAPE,WALLSHAPE_G,WALLSHAPE_G2
iNTEGER,ALLOCATABLE,DIMENSION(:,:)::WALL_L
!--------------------- end of variables for parallel partitioned output-------!
REAL,DIMENSION(3)::SRF_ORIGIN,SRF_VELOCITY
REAL::PRESS_OUTLET
INTEGER::RFRAME,SOURCE_ACTIVE
REAL::PER_ROT,ANGLE_PER,V_REF,KINIT_SRF,SRFG,TOL_PER
REAL,ALLOCATABLE,DIMENSION(:,:)::POINT1_GL,POINT2_GL
REAL,ALLOCATABLE,DIMENSION(:)::Radius_GL,MRF_ROT_GL
INTEGER:: NROTORS
INTEGER::NUM_DG_DOFS !NUMBER OF DEGREES OF FREEDOM FOR DG POLYNOMIAL APPROXIMATION
INTEGER::NUM_DG_RECONSTRUCT_DOFS !NUMBER OF DEGREES OF FREEDOM FOR DG ORDER + 1, NOT INCLUDING NUM_DG_DOFS
integer::INDICATOR_TYPE                !TROUBLED INDICATOR TYPE
integer::viscous_s,jump_cond1,jump_cond2,jump_cond3
INTEGER::CAVITATION
REAL::INDICATOR_PAR1,INDICATOR_PAR2,INDICATOR_PAR3, Bound_lim  !TROUBLED INDICATOR PARAMETERS
real::rhc1,rhc2,rhc3,rhc4
real::prace_t1,prace_t2,prace_t3,prace_t4,prace_t5,prace_t6,prace_t7,prace_t8,prace_t9,pr_t1,pr_t2,pr_t3,pr_t4,PR_T5,PR_T6,PR_T7,PR_T8,PRACE_TX1,PRACE_TX2,PRACE_TX3
!------------------START BLEED PARAMETERS-------------------!
INTEGER::BLEED_NUMBER,BLEED,BLEED_TYPE
REAL,ALLOCATABLE,DIMENSION(:,:)::bleed_start,bleed_end
REAL,ALLOCATABLE,DIMENSION(:)::BLEED_PLENUM,BLEED_POROSITY
!------------------END BLEED PARAMETERS-------------------!
!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.2.   INTEGER ALLOCATABLE VARIABLES HERE        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!

INTEGER,ALLOCATABLE,DIMENSION(:,:)::PROBEI	!probe positions
INTEGER,ALLOCATABLE,DIMENSION(:)::nodes_offset_local,nodes_offset_local2,nodes_offset_localW,nodes_offset_local2W	!offsets for the nodes for each cell in my cpu from the global list
INTEGER,ALLOCATABLE,DIMENSION(:)::nodes_offset,nodes_offset2,nodes_offsetW,nodes_offsetW2	!offsets for the nodes for each cell  globally
INTEGER,ALLOCATABLE,DIMENSION(:,:)::GLNEIGH	!GLOBALIST OF ALL THE NEIGHBOURS IN THE GRID
INTEGER,ALLOCATABLE,DIMENSION(:,:)::GLNEIGHPER	!GLOBALIST OF ALL THE ROTATIONAL PERIODIC NEIGHBOURS IN THE GRID
INTEGER,ALLOCATABLE,DIMENSION(:)::XSIZE,XGO,xgo_v,CHUNK_SIZE	!ALLOCATABLE INDEX FOR DESCRIBING WHICH STENCIL IS CONSIDERED WITHIN THE DIRECTIONAL STENCIL CONSTRUCTION ROUTINE
integer,allocatable,dimension(:)::my_nodesl,my_nodesg	!allocatable arrays for local and global indexing of nodes belonging to each cpu (no duplications)

INTEGER,ALLOCATABLE,DIMENSION(:)::IBOUND_T,ibound_t2	!ALLOCATABLE INDEX FOR DESCRIBING THE SHYAPE OF THE CONSIDERED CELL
INTEGER,ALLOCATABLE,DIMENSION(:)::ISELEMT	!total number of elements in each stencil (extended one)
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPIALL,OFFSET,xmpiwall,woffset,xmpi_re,xmpi_wre,offset_v,XMPIALL_v		!allocatable index FOR STENCIL ROUTINE


INTEGER,ALLOCATABLE,DIMENSION(:)::EL_INT,EL_BND
INTEGER,ALLOCATABLE,DIMENSION(:)::PARE,DOSE,PAREEL,PARES
INTEGER,ALLOCATABLE,DIMENSION(:,:)::DOSEEL,SOSEEL
INTEGER,ALLOCATABLE,DIMENSION(:,:,:,:)::ILOCALSTENCIL	!4-D ARRAY FOR STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:,:,:,:)::ILOCALSTENCILPER	!4-D ARRAY FOR ROTATIONAL PERIODIC STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:,:,:,:)::ILOCALALLELG	!4-D ARRAY FOR STENCILS 
INTEGER,ALLOCATABLE,DIMENSION(:,:,:,:)::ILOCALALLELGPER	    !4-D ARRAY FOR ROTATIONAL PERIODIC STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPIE			!GLOBAL LIST OF NUMBER OF ELEMENTS THAT BELONG TO EACH CPU
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPIL			!LOCAL LIST OF NUMBER OF ELEMENTS THAT BELONG TO EACH CPU
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPIN			!NOT USED CAN GET RID OF
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPIELRANK		!NUMBER OF ELEMENTS IN THIS CPU
INTEGER,ALLOCATABLE,DIMENSION(:)::XMPINRANK		!NOT USED CAN GET RID OF
INTEGER,ALLOCATABLE,DIMENSION(:,:,:)::XMPINNUMBER	!NOT USED CAN GET RID OF
INTEGER,ALLOCATABLE,DIMENSION(:)::STCON			!DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:)::STCONC		!DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:)::STCONS		!DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:)::LIST,INEB,IPERB,NODELIST		!DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
INTEGER,ALLOCATABLE,DIMENSION(:,:,:,:)::ILOCALALLS      !DUMMY VARIABLE FOR RECURSIVE SUBROUTINE OF STENCILS
INTEGER::THERMAL,TEMP_MODEL
!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.3.   REAL VARIABLES HERE        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!
REAL::wenocentralweight,TIMESTEP,oo2,zero,forcex,forcey,forcez,extf,vorder,MOOD_VAR1,MOOD_VAR2,MOOD_VAR3,MOOD_VAR4

real,ALLOCATABLE,DIMENSION(:)::SUMVARS,MAXVARS,aver_Vars            !VARIABLES FOR BOUNDS OF TROUBLED CELL INDICATOR


REAL::PI					!PI TRIGONOMETRI
REAL::TAYLOR,taylor_ens,TAYLOR_ENSX					!ONLY TO BE USED FOR TAYLOR GREEN VORTEX
REAL::VOLL					!TOTAL VOLUME OF THE DOMAIN	
REAL::WALL_TEMP					!WALL TEMPERATURE MODEL
REAL::UPTURBLIMIT				!UPPER TURBULENCE VISCOSITY RATIO
REAL::HYBRIDIST					!UPPER TURBULENCE VISCOSITY RATIO

REAL::REYNOLDS					!REYNOLDS NUMBER
REAL::CFLMAX					!MAXIMUM NUMBER OF ALLOWABLE CFL TO BE USED ONLY WITH IMPLICIT
REAL::PREVRES					!PREVIOUS RESIDUAL IN ORDER TO DETERMINE RAMPING STRATEGY
REAL::VECTORX					!SETTING UP WITH RESPECT TO WHICH PLANE THE AOA IS DEFINED X
REAL::VECTORY					!SETTING UP WITH RESPECT TO WHICH PLANE THE AOA IS DEFINED Y
REAL::VECTORZ					!SETTING UP WITH RESPECT TO WHICH PLANE THE AOA IS DEFINED Z
REAL::GRIDAR1					!ASPECT RATIO OF GRID
REAL::GRIDAR2					!MAXIMUM VOLUME ASPECT RATIO OF STENCILS
REAL::T						!TIME	
REAL::TOTALVOLUME				!TOTAL VOLUME OF DOMAIN
REAL::RESLIMIT       				!LIMIT TO STOP THE SIMULATION

REAL::RES_TIME					!RESTART_TIME
REAL::IEVERY2					!HOW OFTEN TO WRITE OUTPUT
REAL::WALLC					!WALL CLOCK LIMIT IN SECONDS
REAL::BETAAS					!BETAAS OF SUTHERLAND EXPONENT
REAL::SUTHER					!SUTHERLAND NON DIMENSIONAL CONSTANT OF TEMPERATURE
REAL::PRANDTL					!PRANDTL NUMBER
REAL::SCALER					!FOR SCALING THE MESH 
REAL::LWCI1					!LINEAR WENO WEIGHT OF CENTRAL STENCILS				!
REAL::RESMAX					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::RESMAXT					!RESIDUAL DIMENSIONAL TURBULENCE
REAL::CFL					!CFL NUMBER
REAL::IEVERY,MODEIO					!HOW OFTEN TO WRITE OUTPUT
REAL::IEVERYAV					!HOW OFTEN TO WRITE OUTPUT OF AVERAGE SOLUTION
REAL:: FIRSTRESU				!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESV					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESW					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESE					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESR					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTREST					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESK					!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESOMEGA				!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::FIRSTRESPASS				!RESIDUAL DIMENSIONAL MEAN FLOW
REAL::GAMMA
REAL::UVEL					!U VELOCITY
REAL::UFREESTREAM				!U VELOCITY
REAL::VVEL					!V-VELOCITY
REAL::WVEL					!W-VELOCITY
REAL::PRES					!PRESSURE
REAL::RRES					!DENSITY
REAL::SPOS					!SPEED OF SOUND
REAL::ETOT					!TOTAL ENERGY
REAL::SPKIN					!SPECIFIC KINETIC ENERGY
REAL::LAM					!HEAT CONDUCTIVITY (WATT/(MK))
REAL::VISC					!VISCOSITY
REAL::LAMX					!FLAGS TO BE USED FOR RESTARTING
REAL::LAMY					!FLAGS TO BE USED FOR RESTARTING
REAL::LAMZ					!FLAGS TO BE USED FOR RESTARTING
REAL::ALPHA,BETA		!FLAGS TO BE USED FOR RESTARTING
REAL::OUT_TIME					!FINAL TIME TO WRITE OUTPUT FOR UNSTEADY SIMULATIONS
REAL::EVERY_TIME,EK_TIME					!FINAL TIME TO WRITE OUTPUT FOR UNSTEADY SIMULATIONS
REAL::XPER					!PERIODICITY IN X AXIS
REAL::YPER					!PERIODICITY IN Y AXIS
REAL::ZPER					!PERIODICITY IN Z AXIS
REAL::AOA					!ANGLE OF ATTACK	
REAL::CHARLENGTH				!CHARACTERISTIC LENGTH IF UNDEFINED, AND REYNOLDS UNDEFINED THE FREE STREAM WILL BE USED FOR AIR
						!TURBULENCE MODEL constants
REAL::TURBINIT				!TURBULENCE INITIAL VALUE VT/V
REAL::CB1
REAL::CB2
REAL::SIGMA
REAL::KAPPA
REAL::CW1
REAL::CW2
REAL::CW3
REAL::CV1
REAL::CT1
REAL::CT2
REAL::CT3
REAL::CT4
REAL::PRTU
REAL::TWALL
CHARACTER(LEN=30)::STATFILE,ST_N_CPU,ST_N_THREADS
INTEGER::THREAD_N
REAL::SIGMA_K1
REAL::SIGMA_K2
REAL::SIGMA_OM1
REAL::SIGMA_OM2
REAL::AA_1
REAL::BETA_I1
REAL::BETA_I2
REAL::ALPHA_STARINF
REAL::ALPHA_0
REAL::BETA_STARINF
REAL::R_BETA
REAL::R_K_SST
REAL::BETA_T
REAL::KAPPA_SST
REAL::R_OM_SST
REAL::ZETA_STAR
REAL::M_T0
REAL::C_SMG
REAL::ETA2_SAS
REAL::SIGMA_PHI
REAL::C_SAS
REAL::ALPHA_INF1
REAL::ALPHA_INF2
REAL::ALPHA_STAR0
REAL::C_MU_INLET   						!FUNCTIONS FOR SST
REAL::L_TURB_INLET
REAL::I_TURB_INLET
REAL::INIT_MU_RATIO
REAL::C_DES_SA
REAL::C_DES_SST
REAL:: SCHMIDT_LAM
REAL::SCHMIDT_TURB
real::tolsmall,TOLBIG,allresdt,tz1
REAL,DIMENSION(7)::ALLRES,INITIALRES
REAL,dimension(100,3)::bubble_centre
real,dimension(100)::bubble_radius
INTEGER::NOF_BUBBLES

real:: momentx,momenty,momentz
!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.4.   REAL ALLOCATABLE VARIABLES HERE        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!
REAL,ALLOCATABLE,DIMENSION(:)::gamma_IN,MP_R_IN,MP_A_IN,MP_PINF !MULTIPHASE COMPONENTS	
REAL,ALLOCATABLE,DIMENSION(:)::MODAL_FILTER,ADDA_FILTER_WEAK,ADDA_FILTER_STRONG,MODAL_FILTER_STRONG,MODAL_FILTER_WEAK
REAL::L1NORM		!L1 NORM OF SOLUTION FOR GRID CONVERGENCE STUDIES OF EULER AND LINEAR ADVECTION EQUATIONS
REAL::L2NORM		!L2 NORM OF SOLUTION FOR GRID CONVERGENCE STUDIES OF EULER AND LINEAR ADVECTION EQUATIONS
REAL::L0NORM,STENNORM		!L0 NORM OF SOLUTION FOR GRID CONVERGENCE STUDIES OF EULER AND LINEAR ADVECTION EQUATIONS
REAL::DT 					!REAL TIME STEP SIZE       
REAL,ALLOCATABLE,DIMENSION(:)::AVRG		!TEMPORARY SOLUTION AVERAGES
REAL,ALLOCATABLE,DIMENSION(:,:)::JAC		!jacobians
REAL,ALLOCATABLE,DIMENSION(:,:)::INVERSEJAC	!inverse jacobians
REAL,ALLOCATABLE,DIMENSION(:)::DETERJAC		!determinant jacobians
REAL,ALLOCATABLE,DIMENSION(:,:)::PROBEC		!probe positions


REAL,ALLOCATABLE,DIMENSION(:,:)::IMPDU		!IMPLICIT ONLY CHANGE OF SOLUTION

REAL,ALLOCATABLE,DIMENSION(:,:,:)::IMPDIAG	!IMPLICIT ONLY DIAGONAL MATRIX D
REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::IMPOFF	!IMPLICIT ONLY OFF DIAGONAL MATRIX D
REAL,ALLOCATABLE,DIMENSION(:)::IMPDIAG_MF	!IMPLICIT ONLY DIAGONAL MATRIX D
REAL,ALLOCATABLE,DIMENSION(:,:)::IMPOFF_MF	!IMPLICIT ONLY OFF DIAGONAL MATRIX D
REAL,ALLOCATABLE,DIMENSION(:,:,:)::IMPOFFT	!IMPLICIT ONLY OFF DIAGONAL MATRIX D FOR TURBULENCE
REAL,ALLOCATABLE,DIMENSION(:,:)::IMPDIAGT	!IMPLICIT ONLY  DIAGONAL MATRIX D FOR TURBULENCE
REAL,ALLOCATABLE,DIMENSION(:,:)::SHT		!IMPLICIT ONLY  SORUCE TERM JACOBIAN


REAL,ALLOCATABLE,DIMENSION(:)::maxDiff		!SE
REAL,ALLOCATABLE,DIMENSION(:)::minDiff		!SE
REAL,ALLOCATABLE,DIMENSION(:)::tmaxDiff		!SE
REAL,ALLOCATABLE,DIMENSION(:)::tminDiff		!SE
REAL,ALLOCATABLE,DIMENSION(:)::XMIN		!SE
REAL,ALLOCATABLE,DIMENSION(:)::XMAX		!SE
REAL,ALLOCATABLE,DIMENSION(:)::YMIN		!SE
REAL,ALLOCATABLE,DIMENSION(:)::YMAX		!SE
REAL,ALLOCATABLE,DIMENSION(:)::ZMIN		!SE
REAL,ALLOCATABLE,DIMENSION(:)::ZMAX		!SE
REAL,ALLOCATABLE,DIMENSION(:)::CPUX1		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX2		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX3		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX4		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX5		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX6		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::CPUX7		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX1		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX2		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX3		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX4		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX5		!TIMER
REAL,ALLOCATABLE,DIMENSION(:)::TIMEX6		!TIMER
REAL,ALLOCATABLE,DIMENSION(:,:)::IFIN		!TEMPORARY POINTER FOR SYNC OUTPUT
REAL,ALLOCATABLE,DIMENSION(:,:)::TFIN		!TEMPORARY POINTER FOR SYNC OUTPUT
REAL,ALLOCATABLE,DIMENSION(:,:)::CENTERR	!FOR DIRECTIONAL STENCILS	
integer, allocatable,dimension(:)::cand,CANDS,CANDR
integer, allocatable,dimension(:,:)::CANDXR,candxS,CAND2S,CAND2rT
integer, allocatable,dimension(:,:,:)::CAND2R
REAL, allocatable,dimension(:,:)::XAND2S,XAND2rT
REAL, allocatable,dimension(:,:,:)::XAND2R
REAL,ALLOCATABLE,DIMENSION(:)::FLUX_TERM_LEFT_Z,FLUX_TERM_LEFT_X,FLUX_TERM_LEFT_Y
REAL,ALLOCATABLE,DIMENSION(:)::FLUX_TERM_RIGHT_Z,FLUX_TERM_RIGHT_X,FLUX_TERM_RIGHT_Y
real,allocatable,dimension(:,:)::SIND1,SIND2,SIND3,SIND4,SIND5,SIND6
!--------------------------------------------------------------------------------------------------------------------------!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! S.5.   DATA TYPE VARIABLES HERE        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo!
!--------------------------------------------------------------------------------------------------------------------------!
 
TYPE::VOL_GQP
    REAL,ALLOCATABLE,DIMENSION(:)::X,Y,Z,QP_WEIGHT
END TYPE VOL_GQP

TYPE(VOL_GQP),ALLOCATABLE,DIMENSION(:)::QP_ARRAY !CELL NUM, QP NUM

TYPE::U_CENTRE					!DATA TYPE THAT HOLDS THE CELL CENTER VALUES FOR THE EQUATIONS TO BE SOLVED
	REAL,ALLOCATABLE,DIMENSION(:,:)::VAL	!ACTUAL VALUES (FIRST INDEX CORRESPONDS TO RUNGE-KUTTA STAGE,THE SECOND ONE CORRESPONDS TO NUMBER OF VARIABLES FOR MEAN FLOW EQUATIONS)
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::VALDG !ACTUAL VALUES (RK STAGE, VARIABLE NUMBER, CELL-AVERAGED SOLUTION VARIABLES AND EXPANSION COEFFICIENTS)
	REAL,ALLOCATABLE,DIMENSION(:)::RMS	!RMS VALUES OF THE CONSERVED VECTOR IN CASE OF TRANSIENT SIMULATIONS
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::BR2_AUX_VAR ! (NUM_DG_DOFS, NOF_VARIABLES, DIMENSIONA)
END TYPE U_CENTRE


TYPE::mass_matrix					!DATA TYPE THAT HOLDS THE DG_mass_matrix
	REAL,ALLOCATABLE,DIMENSION(:,:)::VAL	
END TYPE mass_matrix

TYPE::FACE_D
	INTEGER,ALLOCATABLE,DIMENSION(:)::Q_MAPL,QMAPD
END TYPE FACE_D

TYPE(U_CENTRE),ALLOCATABLE,DIMENSION(:)::U_C 	!1-D ARRAY FOR TYPE FOR SOLUTION OF MEAN FLOW EQUATIONS
TYPE(U_CENTRE),ALLOCATABLE,DIMENSION(:)::U_cx,U_CS,U_CW 	!1-D ARRAY FOR TYPE FOR SOLUTION OF MEAN FLOW EQUATIONS
TYPE(U_CENTRE),ALLOCATABLE,DIMENSION(:)::U_CT 	!1-D ARRAY FOR TYPE FOR SOLUTION OF TURBULENT EQUATIONS 
TYPE(mass_matrix),ALLOCATABLE,DIMENSION(:)::m_1 	!1-D ARRAY FOR TYPE FOR SOLUTION OF TURBULENT EQUATIONS


TYPE::U_EXACT					!DATA TYPE THAT HOLDS THE CELL CENTER VALUES OF THE EXACT SOLUTION FOR LINEAR ADVECTION OF EULER EQUATIONS IF AN EXACT SOLUTION EXISTS
	REAL,ALLOCATABLE,DIMENSION(:,:)::VAL	!VALUES OF THE EXACT SOLUTION
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::VALDG
END TYPE U_EXACT
TYPE(U_EXACT),ALLOCATABLE,DIMENSION(:)::U_E	!1-D ARRAY FOR TYPE FOR EXACT SOLUTION OF MEAN FLOW EQUATIONS


TYPE::SUMFLUXES					!DATA TYPE FOR THE FLUXES CONTRIBUTION
	REAL,ALLOCATABLE,DIMENSION(:)::VAL	!NUMBER OF VALUES FOR THE FLUXES
	REAL,ALLOCATABLE,DIMENSION(:,:)::VALDG	!NUMBER OF VALUES FOR THE FLUXES (DOFS, VARIABLE)
	REAL,ALLOCATABLE,DIMENSION(:,:)::SOL_MM_DG!NUMBER OF VALUES FOR THE FLUXES (DOFS, VARIABLE)
END TYPE SUMFLUXES
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SUMCONFLUX	!CONVECTIVE FLUXES MEAN FLOW EQUATIONS
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SUMVISCFLUX	!VISCOUS FLUXES MEAN FLOW EQUATIONS
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SOURCETERM	!SOURCETERM
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SUMCONFLUXT	!CONVECTIVE FLUXES ADDITIONAL EQUATIONS
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::SUMVISCFLUXT  !VISCOUS FLUXES ADDITIONAL EQUATIONS
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::RHS		!RIGHT HAND SIDE OF THE MEAN FLOW EQUATIONS (SUM OF ALL FLUXES CONTRIBUTIONS)
TYPE(SUMFLUXES),ALLOCATABLE,DIMENSION(:)::RHST		!RIGHT HAND SIDE OF THE ADDITIONAL FLOW EQUATIONS (SUM OF ALL FLUXES CONTRIBUTIONS)


TYPE INTEGRALBASIS !INTEGRAL BASIS FUNCTIONS
	REAL,allocatable,dimension(:)::VALUE,VALUEc !VALUES FOR THE HIGH AND LOWER-ORDER POLYNOMIALS RESPECTIVELY
END TYPE INTEGRALBASIS
TYPE(INTEGRALBASIS),ALLOCATABLE,DIMENSION(:)::INTEG_BASIS,integ_basis_dg




TYPE LOCAL_RECON3
	INTEGER::LOCAL,MRF
	REAL,ALLOCATABLE,DIMENSION(:)::cond  !dummy variable used for gradient approximation estimation 
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXG,IHEXGc !GLOBAL INDEX OF CELLS
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXL,IHEXLc !LOCAL INDEX OF CELLS
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXB,ihexbc !CPU THAT THAT EACH CELL BELONGS TO
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::IHEXN,ihexnc !INTERNAL INDEX FROM WHERE TO TAKE THE VALUES FROM COMMUNICATED MESSAGES
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::GRADIENTS,GRADIENTSc !RECONSTRUCTED GRADIENTS FOR MAIN VARIABLES
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::GRADIENTSTURB   ! UNLIMITED GRADIENTS FOR TURBULENT VARIABLES FOR 
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::GRADIENTSTURB_wall ! UNLIMITED GRADIENTS FOR TURBULENT VARIABLES FOR WALL CELLS
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::GRADIENTS2,GRADIENTSC2 ! RECONSTRUCTED GRADIENTS FOR TURBULENT VARIABLES FOR WALL CELLS
	REAL,ALLOCATABLE,DIMENSION(:)::GRADIENTSTEMP !UNLIMITED GRADIENTS FOR TEMPERATURE
	REAL,ALLOCATABLE,DIMENSION(:,:)::GRADIENTSTEMP_wall !UNLIMITED GRADIENTS FOR TEMPERATURE FOR WALL CELLS
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::CGRADIENTSTEMP !UNLIMITED GRADIENTS FOR TEMPERATURE FOR WALL CELLS
	REAL,ALLOCATABLE,DIMENSION(:,:)::VELOCITYDOF !UNLIMITED GRADIENTS FOR VELOCITY
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::VELOCITYDOF_wall !UNLIMITED GRADIENTS FOR VELOCITY FOR WALL CELLS
	REAL,ALLOCATABLE,DIMENSION(:,:)::INVCCJAC  !INVERSE JACOBIAN
	REAL,ALLOCATABLE,DIMENSION(:,:)::INVCTJAC  !INVERSE JACOBIAN TRANSPOSED
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::STENCILS,STENCILSc  !STENCILS ENTRIES FOR MATRIX A (USUALLY STORED ONLY FOR WALL BOUNDED CELLS)
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::INVMAT_STENCILT,INVMAT_STENCILTc !PSEUDO INVERSE MATRIX FOR LEAST SQUARES RECONSTRUCTION
	REAL,ALLOCATABLE,DIMENSION(:,:)::VOLUME,VOLUMEc            !VOLUME OF ELEMENTS IN THE STENCIL
	REAL,ALLOCATABLE,DIMENSION(:,:)::GRADS,GRADSAV !GRADIENTS OBTAINED FROM GREEN GAUSS APPROXIMATION
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::ULEFT,uleftx !BOUNDARY EXTRAPOLATED VALUE FOR MAIN EQUATIONS VARIABLES FOR CONSIDERED CELL
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::QPOINTS !QUADRATURE POINTS
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::ULEFTTURB !BOUNDARY EXTRAPOLATED VALUE FOR TURBULENT EQUATIONS VARIABLES FOR CONSIDERED CELL
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::ULEFTV !BOUNDARY EXTRAPOLATED VALUES FOR MAIN EQUATIONS GRADIENTS FOR CONSIDERED CELL
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::ULEFTTURBV !BOUNDARY EXTRAPOLATED VALUES FOR TURBULENT EQUATIONS GRADIENTS FOR CONSIDERED CELL
	REAL,ALLOCATABLE,DIMENSION(:,:)::WENO  !WENO WEIGHTS FOR MAIN EQUATIONS VARIABLES
	REAL,ALLOCATABLE,DIMENSION(:,:)::WENO2 !WENO WEIGHTS FOR TURBULENT EQUATIONS VARIABLES
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::WENOS !WENO WEIGHTS FOR MAIN EQUATIONS WITH RESPECT TO CHARACTERISTIC VARIABLES
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::FINDW !WENO WEIGHTS FOR MAIN EQUATIONS WITH RESPECT TO CHARACTERISTIC VARIABLES
	REAL,ALLOCATABLE,DIMENSION(:,:)::INDICATOR,INDICATORC !PRECOMPUTED SMOOTHNESS INDICATORS
	REAL,ALLOCATABLE,DIMENSION(:,:)::DG2FV,WEIGHTL
	REAL,ALLOCATABLE,DIMENSION(:,:)::TEMPSQ !CONSTRAINED LEAST SQUARES RECONSTRUCTION MATRIX FOR TEMPERATURE GRADIENT
	REAL,ALLOCATABLE,DIMENSION(:,:)::TEMPSQMAT !CONSTRAINED LEAST SQUARES RECONSTRUCTION MATRIX FOR TEMPERATURE GRADIENT
	REAL,ALLOCATABLE,DIMENSION(:,:)::VELLSQ !CONSTRAINED LEAST SQUARES RECONSTRUCTION MATRIX FOR VELOCITY GRADIENT
	REAL,ALLOCATABLE,DIMENSION(:,:)::VELINVLSQMAT !CONSTRAINED LEAST SQUARES RECONSTRUCTION MATRIX FOR VELOCITY GRADIENT
	REAL,ALLOCATABLE,DIMENSION(:)::WALLCOEFF !CONSTRAINED LEAST SQUARES GAUSSIAN ELIMINATION COMPONENT
	REAL,ALLOCATABLE,DIMENSION(:)::WALLCOEFG !CONSTRAINED LEAST SQUARES GAUSSIAN ELIMINATION COMPONENT
	INTEGER::G0 !CONSTRAINED LEAST SQUARES GAUSSIAN ELIMINATION COMPONENT
	INTEGER::K0 !CONSTRAINED LEAST SQUARES GAUSSIAN ELIMINATION COMPONENT
	REAL,ALLOCATABLE,DIMENSION(:)::VEXT_REF !REFERENCE COORDINATES OF THE VERTEX BY WHICH THE TRANSFORMATION HAS BEEN BASED UPON
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::SURF_QPOINTS ! Physical space surface quadrature points (I_FACE, I_QP, XY) relative to cell center
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::ULEFT_DG ! Boundary extrapolated solution value (VAR, I_FACE, I_QP)
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::RPOINTS,ROTVEL !RADIUS OF QPOINTS, ROTATIONAL VELOCITY
    REAL,ALLOCATABLE,DIMENSION(:)::MRF_ORIGIN,MRF_VELOCITY
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::PERIODICFLAG
	REAL,ALLOCATABLE,DIMENSION(:,:,:,:)::BR2_AUX_VAR ! (VAR, DIM, I_FACE, I_QP)
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::BR2_LOCAL_LIFT ! (VAR, DIM, I_FACE)
END TYPE LOCAL_RECON3

TYPE::NEIXX
      INTEGER::CPU                              !CPU INDEX
      INTEGER,ALLOCATABLE,DIMENSION(:,:)::ELEM1 !ELEMENTS INDEXING
      REAL,ALLOCATABLE,DIMENSION(:)::CENTERS    !CENTERS OF CELLS FOR WENO DIRECTIONALS STENCILS AND COMPACT STENCILS 
END TYPE NEIXX



TYPE(LOCAL_RECON3),ALLOCATABLE,DIMENSION(:)::ILOCAL_RECON3
TYPE(NEIXX),ALLOCATABLE,DIMENSION(:)::NEIX1,NEIX2,NEIX3,NEIX4,NEIX5
TYPE(LOCAL_RECON3),ALLOCATABLE,DIMENSION(:)::ILOCAL_RECON4,ILOCAL_RECON5,ilocal_recon6

TYPE EXCHANGE_CORD
	INTEGER::PROCID        !ID OF PROCESSOR
	INTEGER::HOWMANY       ! HOW MANY ELEMENTS ARE NEEDED
	REAL,ALLOCATABLE,DIMENSION(:,:,:)::NODECORD    !THE COORDINATES OF THE ELEMENT
END TYPE EXCHANGE_CORD

TYPE(EXCHANGE_CORD),ALLOCATABLE,DIMENSION(:)::IEXCORDR  !RECEIVING DATA TYPE     
TYPE(EXCHANGE_CORD),ALLOCATABLE,DIMENSION(:)::IEXCORDS  !SENDING DATA TYPE


TYPE EXCHANGE_SOLHI
	INTEGER::PROCID    !ID OF PROCESSOR
	INTEGER::IAVT      !NUMBER OF PROCESSORS THAT WE NEED TO RECEIVE/OR SEND DATA
	INTEGER::IAVC      !NUMBER OF PROCESSORS THAT WE NEED TO RECEIVE/OR SEND DATA
	INTEGER::FAST
	INTEGER::HOWMANY   !HOW MANY ELEMENTS ARE NEEDED
	REAL,ALLOCATABLE,DIMENSION(:,:)::SOL   !ARRAY TO HOLD THE VALUES TO BE SEND/RECEIVED
END TYPE EXCHANGE_SOLHI

TYPE(EXCHANGE_SOLHI),ALLOCATABLE,DIMENSION(:)::IEXSOLHIR,iexsolhird    !RECEIVING DATA TYPE FOR HALO CELLS OF STENCILS
TYPE(EXCHANGE_SOLHI),ALLOCATABLE,DIMENSION(:)::IEXSOLHIS,iexsolhisd    !SENDING DATA TYPE FOR HALO CELLS OF STENCILS



TYPE EXCHANGE_BOUNDHI    
	INTEGER::PROCID   !ID OF PROCESSOR
	INTEGER::IAVT     !NUMBER OF PROCESSORS THAT WE NEED TO RECEIVE/OR SEND DATA
	INTEGER::FAST
	INTEGER::HOWMANY  !HOW MANY ELEMENTS ARE NEEDED
	REAL,ALLOCATABLE,DIMENSION(:,:)::FACESOL,FACESOL_M, FACESOL_DG  !ARRAY HOLDING THE NUMBER OF VARIABLES TO BE SENT/RECEIVED
	integer,allocatable,dimension(:,:)::vertpp !VERTEX MAPPING BETWEEN DIFFERENT PROCESSES
END TYPE EXCHANGE_BOUNDHI

TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIR !RECEIVING DATA TYPE FOR BOUNDARY EXTRAPOLATED VALUES AT GAUSSIAN QUADRATURE POINTS OF INTER-PROCESSOR BOUNDARIES
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIS !SENDING DATA TYPE FOR BOUNDARY EXTRAPOLATED VALUES AT GAUSSIAN QUADRATURE POINTS OF INTER-PROCESSOR BOUNDARIES
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIRi !RECEIVING DATA TYPE FOR BOUNDARY EXTRAPOLATED VALUES AT GAUSSIAN QUADRATURE POINTS OF INTER-PROCESSOR BOUNDARIES FOR IMPLICIT TIME STEPPING
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIsi !SENDING DATA TYPE FOR BOUNDARY EXTRAPOLATED VALUES AT GAUSSIAN QUADRATURE POINTS OF INTER-PROCESSOR BOUNDARIES FOR IMPLICIT TIME STEPPING
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHIRR  !RECEIVING DATA TYPE FOR BOUNDARY EXTRAPOLATED VALUES AT GAUSSIAN QUADRATURE POINTS OF INTER-PROCESSOR BOUNDARIES FOR IMPLICIT TIME STEPPING
TYPE(EXCHANGE_BOUNDHI),ALLOCATABLE,DIMENSION(:)::IEXBOUNDHISS  !SENDING DATA TYPE FOR BOUNDARY EXTRAPOLATED VALUES AT GAUSSIAN QUADRATURE POINTS OF INTER-PROCESSOR BOUNDARIES FOR IMPLICIT TIME STEPPING



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
TYPE::NODE_NE	!NAME OF TYPE FOR THE SET OF NODES 
	INTEGER::itor  !index declaring if the coordinates of this node are needed for each cpu
	real,allocatable,dimension(:)::cord    !coordinates of the node
	INTEGER,ALLOCATABLE,DIMENSION(:)::BCT
	INTEGER::itorm	!index refering to unique list index in cells
END TYPE NODE_NE
TYPE::NODE_LIT	!NAME OF TYPE FOR THE SET OF NODES 
	INTEGER::NUMBEROFNEIB      !number of elements that share this node
	INTEGER,allocatable,dimension(:)::NEIBIDS,xne,xneib !ids of the elements, and counters
END TYPE NODE_LIT



TYPE(NODE_NE),ALLOCATABLE,DIMENSION(:)::INODEN,INODER,INODER4
TYPE(NODE_LIT),ALLOCATABLE,DIMENSION(:)::INODER2



TYPE::ELEM_SHAPE	!NAME OF TYPE FOR THE SET OF NODES 
	INTEGER::ISHAPE	!integer indicating the shape of each element
END TYPE ELEM_SHAPE 

INTEGER,ALLOCATABLE,DIMENSION(:)::IESHAPE	!1-D ARRAY FOR SHAPE OF ELEMENT

TYPE::EXCHANGE
	INTEGER::PROCID					!PROCESSOR ID
	INTEGER::TOT                    ! total number of elements
	INTEGER,ALLOCATABLE,DIMENSION(:)::WHATTHEYNEED   !ELEMENT NUMBERS
	INTEGER,ALLOCATABLE,DIMENSION(:)::MUCHTHEYNEED  !NUMBER OF ELEMENTS THEY NEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::MUCHINEED	!NUMBER OF ELEMENTS I NEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::WHATINEED	!ELEMENT NUMBER GLOBAL
	INTEGER,ALLOCATABLE,DIMENSION(:)::SIDEINEED !side that i need  
	INTEGER,ALLOCATABLE,DIMENSION(:)::SIDEINEEDN,QINEED    !from which cpu, which gaussian quadrature point order
	INTEGER,ALLOCATABLE,DIMENSION(:)::SIDETHEYNEED,QTHEYNEED !side they need, which gaussian quadrature point order
	INTEGER,ALLOCATABLE,DIMENSION(:)::SIDETHEYNEEDN    
	INTEGER,ALLOCATABLE,DIMENSION(:)::LOCALREF !local reference
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::nodex
END TYPE EXCHANGE


TYPE(EXCHANGE),ALLOCATABLE,DIMENSION(:)::IEXCHANGER !receive
TYPE(EXCHANGE),ALLOCATABLE,DIMENSION(:)::IEXCHANGES !send
TYPE(EXCHANGE),ALLOCATABLE,DIMENSION(:)::IEXCHANGER1
TYPE(EXCHANGE),ALLOCATABLE,DIMENSION(:)::IEXCHANGES1

TYPE::SOLEXCHANGE
	INTEGER::PROCID        !processor ID
	REAL,ALLOCATABLE,DIMENSION(:,:)::CENTRES   !CELL CENTRES
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::NODES  !NODES
	REAL,ALLOCATABLE,DIMENSION(:,:)::SOL,SOL_DG       !SOLUTION
END TYPE SOLEXCHANGE

TYPE(SOLEXCHANGE),ALLOCATABLE,DIMENSION(:)::SOLCHANGER  !RECEIVES

TYPE(SOLEXCHANGE),ALLOCATABLE,DIMENSION(:)::SOLCHANGES  !SENDS

TYPE::RECEX
	INTEGER::PROCID					!PROCESSOR ID
	INTEGER::TOT
	INTEGER,ALLOCATABLE,DIMENSION(:)::WHATTHEYNEED   !ELEMENT NUMBERS
	INTEGER,ALLOCATABLE,DIMENSION(:)::MUCHTHEYNEED  !NUMBER OF ELEMENTS THEY NEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::MUCHINEED	!NUMBER OF ELEMENTS I NEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::WHATINEED	!ELEMENT NUMBER GLOBAL
	INTEGER,ALLOCATABLE,DIMENSION(:)::ISHAPE   !SHAPE OF ELEMENTS
	INTEGER,ALLOCATABLE,DIMENSION(:)::LOCALREF !LOCAL REFERENCING  
	REAL,ALLOCATABLE,DIMENSION(:,:)::CENTERS   !BARYCENTRES
END TYPE RECEX

TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::IRECEXR		!RECEIVE ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::IRECEXR1		!RECEIVE ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::irecexrg		!RECEIVE ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::irecexsg		!SEND ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::IRECEXS1		!SEND ELEMENTS DUE TO STENCILS
TYPE(RECEX),ALLOCATABLE,DIMENSION(:)::IRECEXS		!SEND ELEMENTS DUE TO STENCIL


!>NAME OF TYPE FOR THE SET OF ELEMENTS
TYPE::ELEMENT_NUMBER
    INTEGER::IHEX	!LOCAL INDEX OF EACH CELL
    INTEGER::MOOD,MOOD_O	!MOOD FLAG FOR EVERY ELEMENT
    INTEGER::RECALC !FLAG FOR RECALCULATING THE SOLUTION POST-ERIORI
	INTEGER::IHEXGL !GLOBAL INDEX OF EACH CELL
	INTEGER::full   !SPECIFIES IF SUFFICIENT NUMBER OF STENCILS ARE FOUND TO PROCEED WITH WENO FOR THIS CELL
	INTEGER::INTERIOR !SPECIFIES IF THIS CELL HAS ANY SIDE BOUNDED (INTERIOR CELLS GET A VALUE OF 0, NON INTERIOR ONES GET A VALUE OF 1)
	integer::itotalpoints,TROUBLED
	INTEGER::VDEC,HALO      !NUMBER OF VOLUME DECOMPOSITIONS FOR EACH ELEMENT
	INTEGER::MODE      !SPECIFIES IF DECOMPOSITION CANBE AVOIDED FOR STRAIGHT SIDED ELEMENT (NOT IMPLEMENTED YET)
	INTEGER::GGS      ! SPECIFIES WITH WHAT ALGORITHM TO COMPUTE THE GRADIENTS (GREEN GAUSS, LEAST SQUARES OR BLEND OF THEM)
	INTEGER::idegfree  !DEGREES OF FREEDOM FOR POLYNOMIAL SELECTED
	INTEGER::inumneighbours    !NUMBER OF NEIGHBOURS IN EACH STENCIL
	INTEGER::nofbc         !NUMBER OF BOUNDED FACES 
	INTEGER::iorder    !ORDER OF POLYNOMIALS
	INTEGER::ISHAPE    !> SHAPE OF ELEMENT 1: Hex 2: Tet 3: Pyramid 4: Prism 5: Quad 6: Tri
	INTEGER::IFCA      !NUMBER OF SIDES
	INTEGER::ADMIS     !NUMBER OF ADMISSIBLE STENCILS
	INTEGER::hybrid    !FLAG FOR SWITCHING TO LOWER ORDER DISCRETISATION AS A FUNCTION OF WALL DISTANCE
	INTEGER::nonodes   !NUMBER OF NODES 
	INTEGER::walls     !FLAG TO DECLARE IF THIS IS CELL BOUNDED BY A WALL
	INTEGER::LUMP
	INTEGER::FILTERED,REDUCE
	INTEGER,ALLOCATABLE,DIMENSION(:)::BLEEDN
	INTEGER,ALLOCATABLE,DIMENSION(:)::NOJECOUNT
	INTEGER,ALLOCATABLE,DIMENSION(:)::NODES    !NODES INDEX
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::NODES_NEIGHBOURS    !NODES INDEX
	INTEGER,ALLOCATABLE,DIMENSION(:)::TYPEs_FACES !TYPE OF EACH FACE (QUADRILATERAL, TRIANGLE)
	INTEGER,ALLOCATABLE,DIMENSION(:)::REORIENT     !CONSISTENCY ACROSS INTERFACE IN TERMS OF ORDERING OF QUADRATURE POINTS
	integer,allocatable,dimension(:)::num_of_wall_gqp !NOT USED YET
	TYPE(FACE_D),ALLOCATABLE,DIMENSION(:)::Q_FACE  !QUADRATURE FACE
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::NODES_FACES,NODES_FACES_v !COUNTERCLOCKWISE NUMBERING OF THE NODES FOR EACH FACE
	INTEGER,ALLOCATABLE,DIMENSION(:)::INDEXI !INDEXING FOR THE CELLS
	INTEGER,ALLOCATABLE,DIMENSION(:)::ibounds,IBOUNDW ! BOUNDED CODES FOR EACH BOUNDED FACE
	INTEGER,ALLOCATABLE,DIMENSION(:)::INEIGH !NEIGHBOURS LOCAL NUMBERING	
	INTEGER,ALLOCATABLE,DIMENSION(:)::INEIGHG !NEIGHBOURS GLOBAL NUMBERING
	INTEGER,ALLOCATABLE,DIMENSION(:)::INEIGHB !NEIGHBOURS CPU INDEX	
	INTEGER,ALLOCATABLE,DIMENSION(:)::INEIGHN !NEIGHBOURS NUMBERING IN OTHER CPUS	
	INTEGER,ALLOCATABLE,DIMENSION(:)::NODEs_V !NODES_REARRANGED FOR OUTPUT
 	REAL::TOTVOLUME		!VOLUME OF ELEMENT 
	REAL::DTL,VISCX           !LOCAL TIME STEP SIZE
 	REAL::MINEDGE       !INSCRIBED SPHERE RADIUS
 	REAL::STENCIL_DIST    !STENCIL DISTANCE FACTOR
 	REAL::WallDist        !WALL DISTANCE
 	REAL::XXC          !CELL CENTRE COORDINATES IN X
 	REAL::YYC           !CELL CENTRE COORDINATES IN Y
 	REAL::ZZC           !CELL CENTRE COORDINATES IN Z
 	REAL::CONDITION
 	REAL::ER,er2,er1,ER2Dt,ER1DT,ER1ER2,lwcx2,DISS,ERX	!ADDA COMPONENTS
 	REAL::LINC
 	REAL,DIMENSION(1)::WCX
	REAL,ALLOCATABLE,DIMENSION(:)::FACEANGLEX	!FACEANGLE  X,Y
	REAL,ALLOCATABLE,DIMENSION(:)::FACEDISS
	REAL,ALLOCATABLE,DIMENSION(:)::FACEANGLEY	!FACEANGLES X,Y
	REAL,ALLOCATABLE,DIMENSION(:)::DIH !DISTANCE ACROSS CELL CENTRES AT EACH FACE
	REAL,ALLOCATABLE,DIMENSION(:,:)::dih2
	REAL,ALLOCATABLE,DIMENSION(:)::vortex,AVARS  !Q CRITERION
	REAL,ALLOCATABLE,DIMENSION(:)::SURF    !SURFACE AREA
	REAL,ALLOCATABLE,DIMENSION(:)::DELTA_XYZ ! 0.5(X_MAX - X_MIN),  0.5(Y_MAX - Y_MIN),  0.5(Z_MAX - Z_MIN)
	integer::condx
END TYPE ELEMENT_NUMBER

TYPE::FACES
  INTEGER::ISHAPE   !SHAPE OF EACH FACE
  INTEGER,ALLOCATABLE,DIMENSION(:)::NEIGHG,NEIGHL   !GLOBAL AND LOCAL INDEXING OF CELLS
  INTEGER,ALLOCATABLE,DIMENSION(:)::NODES           !NUMBER OF NODES
END TYPE FACES

TYPE(ELEMENT_NUMBER),ALLOCATABLE,DIMENSION(:,:)::IELEM  !ELEMENT NUMBER
TYPE(FACES),ALLOCATABLE,DIMENSION(:,:)::IFACE


TYPE::BOUND_NUMBER	!NAME OF TYPE FOR THE SET OF ELEMENTS
        INTEGER::ishape,icode,inum,which,face,IBID	!INDICES FOR THE SHAPE, BC CODE, NUMBER, AND WHICH FACE IS BOUNDED
        INTEGER,allocatable,dimension(:)::IBl   !BC FLAG
	INTEGER,ALLOCATABLE,DIMENSION(:)::LOCALN,CPUN   !LOCAL NUMBER AND CPU FOR EACH BOUNDED SURFACE
	CHARACTER(LEN=12)::description
END TYPE BOUND_NUMBER

TYPE(BOUND_NUMBER),ALLOCATABLE,DIMENSION(:,:)::IBOUND	  !1-D ARRAY FOR BOUNDARY CONDITION TYPE

TYPE::CONNX	!NAME OF TYPE FOR THE SET OF ELEMENTS
	INTEGER::PROCID	!CPU ID
	INTEGER,ALLOCATABLE,DIMENSION(:)::HOWMANYI	!HOW MANY ELEMENT I NEED
	INTEGER,ALLOCATABLE,DIMENSION(:)::RETM     !HOW MANY ENTRIES TO RECEIVE
	INTEGER,ALLOCATABLE,DIMENSION(:)::RET      !HOW MANY ENTRIES TO SEND
	INTEGER,ALLOCATABLE,DIMENSION(:)::HOWMANYTHEY !HOW MANY ELEMENT THEY NEED
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::WHICHI !WHICH ELEMENT I NEED
	INTEGER,ALLOCATABLE,DIMENSION(:,:)::WHICHTHEY  !WHICH ELEMENT THEY NEED
	REAL,ALLOCATABLE,DIMENSION(:,:)::FACX      !FAC
END TYPE CONNX

TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONR
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONS
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONRPA
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONRPM
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONSPO
TYPE(CONNX),ALLOCATABLE,DIMENSION(:)::ICONRPF



TYPE::NODE_NUMBER	!NAME OF TYPE FOR THE SET OF NODES 
	INTEGER::NODEN	!IDENTIFICATION NUMBER THAT CAN BE USED AS A POINTER INSIDE AN ARRAY
	INTEGER::BLOCKN !BLOCK NUMBER OR CPU NUMBER OF THIS ELEMENT
	INTEGER::NODEGL
	REAL::X		!COORDINATES IN X AXIS
	REAL::Y		!COORDINATES IN Y AXIS
	REAL::Z		!COORDINATES IN Z AXIS
END TYPE NODE_NUMBER 


TYPE(NODE_NUMBER),ALLOCATABLE,DIMENSION(:,:)::INODE	  !1-D ARRAY FOR POINTER TYPE FOR NODES

TYPE(NODE_NUMBER)::ITEMP				  !TEMPORARY POINTER NODE ITERATION



END MODULE DECLARATION
